---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: termixkit
  namespace: flux-system
spec:
  image: ghcr.io/jvz-devx/termixkit
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: termixkit
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: termixkit
  filterTags:
    pattern: '^main$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: termixkit-image-digest
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): update TermixKit image digest

        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps/termix
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: steve-website
  namespace: flux-system
spec:
  image: ghcr.io/jvz-devx/steve-website
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: steve-website
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: steve-website
  filterTags:
    pattern: '^main$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: steve-website-image-digest
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): update Steve website image digest

        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps/steve-website
    strategy: Setters
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: toepen
  namespace: flux-system
spec:
  image: ghcr.io/jvz-devx/toepen
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: toepen
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: toepen
  filterTags:
    pattern: '^main$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: toepen-image-digest
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): update Toepen image digest

        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps/toepen
    strategy: Setters
