# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: strikers-relay
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:J1Uvjn2Pg+YvV6P42BIzO0vewwxJiwpLEjZQW54LjVNIhkd3fpDveqS6YZUGjWdtfr3QsJWqPZTndcLQ9h0P8UqqPBJLWQwB2kPh2Jlctlmw0F5VsK5zdmFRXiD0yCrFP5PD,iv:GB7vp0qaagkduCrgSsS8MwL+NQZ7uAkdzPzj1WdgDYQ=,tag:0gUhXDa6Jh9pVGq14sWi/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBckhKYmdqT3ZyTFo5cU5C
            a3gzQndvUmhlSkwvWWRkZjVEZW1YRk43UHo0ClBYd1lleGV2ek5xTzlaUnFoM0Mw
            L0VXbzBBdWpINnJWOVB2WVNYT2twSmsKLS0tIDVSaEh1bXJDUkRhVGxjb2lUM01a
            V28zWlduWnhOa1JrNXk5OTdoTU81bjgKMbL8xd5HWWfOxFnlzTlOwjlWIKdW8HEp
            /eZ5VIbG3zKPPy17WzR0xwC+GAzb1bPA3/oE+7y9JXBLj7L+pAEZyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T20:26:43Z"
    mac: ENC[AES256_GCM,data:Wn1i7rn18fWlDadoupFf9CV76uiXpyJJboeqCRXh8imaBTOau5OchzMeBdHv5HSXXu1/DRQw/Xa1ioQCSfDRpfjHZhaCcak2kGXBZChZ+hJ5eD1vaL0jQwYLt97W+gzWwbExa10OayfVZioEFnvkf/ytfVWWjxzRTnCtmrNR+Mk=,iv:CuLswSKSBfFhKFntUuudUOKIOq2YdCStfznVl8EVSUw=,tag:yevMtw3lcBf6X+9nsga9uA==,type:str]
    version: 3.13.3
