apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: cv-web
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:orLwadI4oUDU2ZjDDD72I0NB6NrRDiEQuym1363WzzW1XmzmL1oKGZAMXomnWuCpo4/weMooPHSHTihf5rubnooM78OHO8F1FaIonpzkPt2GOLkyWFSgMyUkVYVYbaZHjbnh,iv:JweBD2VakDfr+DOhL0wcM5WCpFBr5Ylp2S2AizyxWf8=,tag:RCfisyRwIVhnMf6+n6hSmQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWThHd1VNc1JHRkNvanMr
            ZUIxRlRpbkRWdHJJcU1VVU82OFhvbW50OXhVCmRpMkJrUmdsZE5iUHdqWUZ0TXRm
            cmRVQm1GRWJtVm5qNkZiUjEvcVhXeWcKLS0tIFR3WHVZWnFKSzE1Tk5zTDhKNSto
            QUJMZTZwU2pBN0RoZVN3NEtiWW8yemcKrunqTsRKilpAhZensn84qBTBzdcT8/i/
            xdHPhcpUS0ID7qGaOaApE83Zk+i6gVoic1dOpa9YDT3etL4ibrqHjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T20:29:22Z"
    mac: ENC[AES256_GCM,data:b9ksiRYcm9axYKaHF7gJx0YVVmSM3re9x0M198mhH3AWXFSoEpDnvv9hhas4rGxdc+SbNQf/tSKrzClt+Qlv97zfNBDNQ/6joZN/FVyfqCa1I4kPFGGFdtzCupvNNOZkFTIhkzeE65tL5Zss9z5h+M7HbgIO/82TsJVy/puq6AQ=,iv:Yc34oKFxHQYLTQCrmWzUskZl8QTZsDaO9QuQF9qOjNY=,tag:jTj8/h0ivJjbZ3HD6iCf3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
