---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: docs-site
  namespace: flux-system
spec:
  image: ghcr.io/jvz-devx/docs-site
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: docs-site
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: docs-site
  filterTags:
    pattern: '^main$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: rudy-website
  namespace: flux-system
spec:
  image: ghcr.io/jvz-devx/rudy-website
  interval: 1m0s
  secretRef:
    name: ghcr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: rudy-website
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: rudy-website
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
  digestReflectionPolicy: Always
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: app-image-digests
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@users.noreply.github.com
      messageTemplate: |
        chore(images): update container image digests

        {{ range .Changed.Changes -}}
        - {{ .OldValue }} -> {{ .NewValue }}
        {{ end -}}
    push:
      branch: main
  update:
    path: ./apps/hetzner
    strategy: Setters
