# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:BwhHx6eL2bPGmyHuA85GDQQl/qCMKhuGn/geE5X40OuwyCbx7D5/HfQBgVhj6hF50k/ZElSxPehi2uF+WUQd/vOPrU2f1aiJs/OM9pIkTVVj/ZLuUJe0+IeOJij8rmoTW8Tu1RHpQ2Kri9eZPasamKIPV56xI2PBiPh2iXGjO1MuGt7sJV1pPeDuBuVLunEU8IJCep7Oi41J6nAvJUXSx/++nocyBlk/IMLe9cQ57w3r9M/itnnn56fB3KQyHLShvRWY5MsZcEOgcv43nhz4XevzGYdybW42ytv620yxMGRhZ2iYTl3XpqUve1c=,iv:Hj701gq4MqmmUgtsxhrv3Ast/zbAXJW7iVB3VUwGpoQ=,tag:olOMltMqPdzBRrnb1RSgHA==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: cv-web
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTHVxbUtuM2pRUHVBN3lD
            UmMxRHFweDNoM1BCZDhYR3g5M2pRTi9aV2tJCjh2aDArSGRuUUVvVlhHWm9Wd2lE
            RjJEVmtBNnQ0Z3pOeThkc0s3ZnE5UGsKLS0tIHdkTlRVYmlUVnZIRnRuVjBJL3hm
            elo5dTQ0cGVvZ01CdnByMllxQ2lpSzQKFH/NdOHQQZ8bEXMllXca3hEVUUvtfPux
            TYpZWd6popSn+pah10m994r0XYyunM9dICqytcvf0QT43ENMy2PfOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:w7Kk0TSiPnN9X08rv5ndaAV+0RWbmk9crovbBBS8w6k1Jv3gufq888kqpuwmt+cFxrDctBuP/VqGD/ELugWQsyOHCSF3ET3xBCrLHkEl9T/xDL1SGvn7KH4+36mHD5Htnhhxnb5CdNgjGPiKtBlFVgfoS3YAYiLmBRFPMVB+8o8=,iv:VeKZOrhoHp/EoAjJ/qfqgkPcnxZGIgCNGt8KcWP/Wa0=,tag:5Md9L0xf1uLO2G4UbH8pvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
