# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:TwQfqWyBfOp67GeEwWXnm2inDRLr15Qgy5HEJx4iGNhtPksEytsg9hW4nBNPUmJq71rBXlM7CPyepkC6HTOYqS+ttroXG950LfpGvwODghBgxSUruLntjXAphfzopYEJuA+Ab+r/wW9nuBZzQQbb+1CW7n6UF3ZFbsRsrmJFBq7GCHZR/oHZaue+1WncVciW0tDyTzUaBiuF0rqRWB8BNAp95eGTDatXi2cPlWazb6DmvMECK+OCUczMQq0I8HJJ+5QY1VPF7As/noAzCzcbiCtNyv5SRZ7eWKsEB4+iCbMBun8QkTm7I05tCoY=,iv:ZhecWET9iFey17fqRkX65v3TrEVTzOeCNZGLC58M4c4=,tag:uKWJKc20Frn/bL7I8ScIig==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: klavier-dev
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRjh2c0dtTWlMTUY1TUp5
            QzVxOGhWUGhUaDNleFd0aFpTejRubWZBUVVJCnhyK3F1NHNUM29VeFY2OWhxVUEx
            d0dwUW13ZlRWYjVEQXN0NEpmNHZmN1EKLS0tIFBpYVJzaDNqbjZkc3BJY2wzT0Zn
            S01wdHY4Z2k2KzE0azJybEQvRVVkeFkKK+wEL4XP0nDFixzZ2agr+wZnU9DhHjua
            A4dhQNEAif/97DPwvD81tDsfKeimw1sVPMCIoZwDuwnMWntARmA8kA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:/q3Vd4GJYa0WvrUTdqPUbu7lu5E3l+WAn3LorEfG1yGTKJVpYk8KW5XwkFEnQE/uWPtRbNo6lg00P4gvopREg1ymRrNF/z8bNgM8z/OdhPaC+nM88jD1XllXgHbGFVJS+/VxoJsgG+mRS/ju78PyHpYvPOTtTS5bmk9QIxCPXNk=,iv:q3CWgPqjNmLl9dHi8T4pCP+pbSe7QLLG2SlH2owhJy8=,tag:93zLvI8m+DEB37azcU27uw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
