# yamllint disable
apiVersion: v1
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:SbY3KdPcwu5Zdi/z4TzEwFqGhkegWk7zALlxCaqaQr7IdxOjwXzjWh5a4vETKByR,iv:o015jppOeVwaNgwqcXbPeWy0ZkjkhrVi32QGZNRpG7s=,tag:ROhMBqiZHWzU772elxCyOg==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:F8GkxuIqPd/R/wBgu0AA3nnpGpgNqoOl6n1Ou7V2ETTw2I4NvTysNnr0lgg=,iv:P1d0YQttI9olFRihdO2LCm19Um/0AkERfcQYn1RdI6U=,tag:lpWFmetX8gBBQhFCDZyUCw==,type:str]
    COOLIFY_BRANCH: ENC[AES256_GCM,data:97pjHD2TRHs=,iv:VLEiSM12IxVlcLnC75AezKY38ifhPjoRIHq4BAVBdCo=,tag:b5LdxF/H+tZUq2/lcblZDQ==,type:str]
    COOLIFY_CONTAINER_NAME: ENC[AES256_GCM,data:SNK8Xp/KQ+1qEsOD6FOl6ZiUgy8Pgl0bu4rGTLY0tSishrLGVNH0415GLawBOh5EEAFHFg==,iv:n57WyM4E4aDKdWUeWLWyyO1Hj5U8tUCjSDkXK79NbYI=,tag:sHYLB/3XAqsDCpNC+yAuCQ==,type:str]
    COOLIFY_FQDN: ENC[AES256_GCM,data:7BJyWcewxKUEoL3lamdUlKeR3pNRrdsYcQwUkezK8tI=,iv:81tlgEuBYaxFPIap6Qj6UGTV8uVgP37YpfszlkOrz28=,tag:4TRHRPWv8NpZ3oYJ3CVRNQ==,type:str]
    COOLIFY_RESOURCE_UUID: ENC[AES256_GCM,data:B6sppmHrTciPZ79ibZyTDLT1T3HCcR4i/PnfJnkjT4A=,iv:XgkonxV3JghUuTffaHlxZwSnn7WGREbNAOHgDifgtnQ=,tag:3WgWHZYke+9EhbN7wmtbCg==,type:str]
    COOLIFY_URL: ENC[AES256_GCM,data:1wYitewZgi7tIVr524lA3DgLu18Mnm4iqEFShVtSLsWQNb1p1oVRh/GYkrA=,iv:rb4rQak9ILY8o2knICcRaRqdKi5jLJ4/j1R6yW0pmkI=,tag:ewDeYsC1iYhfs7SSXF+FzA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:y63wfiJIOUAKjxK5c/LmWn7fWG8OiyLBQU6QNxaG8NQKtOYfMPvhdYL25GRmpDoG9oTfEyXBvcIf9xdTwLP3S6XiNm0M2mv9Gk/GXOu4OmEL+fX4TNT40oHjzKlEdV7ytTMKg3QM5wY7M4B6nOqZAxu2eONxqBoVhyDV15YBJQeUxuZQ1veBbP4BzLkTKTVZ,iv:WkEqYp08ccNxT1PSJIWTjh+YDJYNyumYlxoqfNnnbXs=,tag:6VvE0Zr+iPC/wG3FScxaAg==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:ZetNqfCZvWRfum5ppRR7H45rXpraZsk4Fey+qw==,iv:8/NtGiluPk6F2lBRf1vBDAugdr0loJYXKyjUO6HrNv0=,tag:5T5hjGa2XFCSbPlxow6Qmg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:9/Ql/daQ88MisLC5Ijn1MX8X/W4V4X0JsnS+g85mtxqD4MOR1iGpcnIREl+UNiOSv6Oed5ntmBI=,iv:m9Gneh4RT27cbPgDVUQRoxP3TGjWWjBYLRVBeOhHOD8=,tag:hldi1Y7YnJXEN8uibhXplA==,type:str]
    HOST: ENC[AES256_GCM,data:9Dylzf9DzjgCF7Bl,iv:KJX1Hga4jRf3/EDXlwB7GvuBPRs+B/sBtU9fbrXz150=,tag:AGHvPRk6zc4d2g19Obz/LA==,type:str]
    ORIGIN: ENC[AES256_GCM,data:6DksPChMfsbW//lFv2aaLR6UMEzKZ08XFcX3QVFMAgCb1W5XRk2uT3WmM8s=,iv:jz3a7QqSaBD8XQYa++fos0rRXY5StXfPaSQlAq2K5m4=,tag:XQxCeWhhzXjiOxSgXVVflA==,type:str]
    PORT: ENC[AES256_GCM,data:pkHPLF3B/G4=,iv:ltiEAlaygKbdtq/vKJcg8fp+FRr1Kf0TxDmMQHWJkiQ=,tag:OLP9HKrVAMwVROkNz0V0rQ==,type:str]
    PUBLIC_WS_URL: ENC[AES256_GCM,data:aHraLMoUn16gRRzNlpbYv7Ved2jlVKNQK1zUU4z0FAekP32AGJpSSKBJppor9ebzhPuQM9x6vEk=,iv:ADe1VZW6I8I2kimKIMj2UTMlqg1EiHpuVzADr4gUpCA=,tag:+7Ewp5IB/HmLxXao/zGUaw==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:nnsELAZb8HnqX+6vAiAeE91w8Ecr490r1yolbRtjMB1pM/v2Z3owkaG8Yis=,iv:9zFq4zIx8+B66L1IaJtHJNMR8VFB3xZLzdn1l5GHalg=,tag:Hv/Xr+8ZXpBV76zxEN7eCg==,type:str]
    R2_BUCKET_NAME: ENC[AES256_GCM,data:b4geC5GFw2M8377wK/NI/3JWtj5tuqGk,iv:MDjBKhQC44hoi6wgwiAQ57JQRyf2x4F95AXZaTjSTpQ=,tag:89ExDT3cjcV/FmOr8S0mNw==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:/wBEOe+Uqbpwl+wfR6N1W45aTLLEUnvzqkP+3abnQSHo1+ZdmaqRcfUEgNtNfoeJjrKV2V8wzFthSuXB/3dWkZ8fuqHMeUrXI+zO+03hZaB3fQdlt9Ff4g==,iv:UXC1WX0ug3wmLtP1f19hzO+/fcyZQuVEih7VWoTr6vo=,tag:n8aGwZMQ27ar+LAFoUYY3A==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ezU5BUN0DHEj1avLPjdI55Q+lVycHTXl+ZhUqqZ8sM9QEGXAZktT20RXUpJ9YtLyyFv163ZlD1wkkvRQs4sLqIIIJYjn9MVOkjUhrWN5Z3tg/pIDYzpkhw==,iv:r71R1C+54tnauOe3hUYAg8rkUk8n1JD3BZ8Gi4t/zz4=,tag:ruEJNihX7kLsZB8inJKZag==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:Q83/hlP+2UD3iYK1ejEDbKY2hsP2y2yo0/g/WhEh7okGuhsMh0rBFT9Xhq//rxdMy9DLbFSHfhleG0m32QlI0k8Wgwvr0i+gxhJ5C4idW/6o8gs8yHpSjmJQo4Wk0UWW1JA25zTg9eQ8K+nyhMUSPBAgpTCWAdEe6oy0aA==,iv:Q1zYl3nrQtgUFDgBgILnHrgPYtNYB7dYmUtPT8jgUXY=,tag:2rQlvwTnkVMU74F4LUvEQw==,type:str]
    SOURCE_COMMIT: ENC[AES256_GCM,data:4Hw6PihAVhbiElLThcAXmd75S74O58/pFjsZrJppSMjk9ub8WLPU9kGvxX7mRsGAq/gag50Y7Vo=,iv:BbIMTK063xLW18DvKNOXDN0ph3eZUr7DG3NfOQU7SEI=,tag:moowpHIJSD6hX+1SHX3qGg==,type:str]
kind: Secret
metadata:
    name: klavier-sveltekit-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMGVoRFgyTEVyWk9tWHQ5
            eDl6UW9tQVI1SkdyMHBkUWdIT0Y1a3FTMlM4CnpsVEZQZHdoNng2dGc0Uk9JWjNH
            cFJIdWo3UExCZ3VIQUt6ZlBudm5MODAKLS0tIHRhS0x2MFdsUGlldUVGc0NsdWRw
            dC9uTGx4TnY5TGxZQi9QOHh4UFhqblkKi4RbaBfkDF0Pwd+rqgMdRpV9orEEvCGW
            7i1kXwbWmrC+ZiT7MDLM7vWJoI40hggKG5ah9mBIeUPkx+lXX3CFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:jWv4z76rNvtrjkuf9HacPblAjW5TJ1Lq320/S1lX2L1t62DeRuH2YpNwWEItYGvtElpclNR/xSGAfE9MB2YztX5rgB9b5P3EFV/N11BOjj6umihSfYU7EdRKU343NiTigExVtI6XUJeaPBX5wsZyIZkBLfhkCUer9sLbK/rpX9o=,iv:fh24hOjRAue806MPBiLHH2bFlmyEEQufe0w6l75m4P8=,tag:qDl03I7v6aJy24dXuD6dPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    COOLIFY_BRANCH: ENC[AES256_GCM,data:bbtoJ068gmo=,iv:R4Vkm9klF/wEAArc7OniUvu1tqlP8k6W8q+2jSnYtLs=,tag:dkTEYg9E7T4mx2aJHGbpTA==,type:str]
    COOLIFY_CONTAINER_NAME: ENC[AES256_GCM,data:MeIt0AfVkNUK3zWsJvQfRSfw8n1C5EJ6V2965EtbmlsYslIpTpFe2iMqoY/qDnJwRpleAA==,iv:0GqGZ1OWBV4IOOXW70ioSx4hngs3nuGhQQ98ZDYVJt4=,tag:HCsfFuWq8R60jjohjP2nTQ==,type:str]
    COOLIFY_FQDN: ENC[AES256_GCM,data:ju8SGYV2fjzw3KWtYW1Mqhlv/Csl+p544f1xTWJqqqLA3n9Ygy75UrRo8yleZNVe,iv:/II/sm+hbz6YI8ID4l4GrgHZ6z45tDNgMqoY1FE4RQA=,tag:L8LtxBbT8zofl35c/j9kDw==,type:str]
    COOLIFY_RESOURCE_UUID: ENC[AES256_GCM,data:dIkr0t1LUF4uU9982TCSEfOnq7vvamgC6WznYMcKveU=,iv:PSH1eaX6qcYDVaJS1YtRd5liSCT0VRGiEK0EE+dtbb4=,tag:nPeiI1B/xqrWvRew+xILgQ==,type:str]
    COOLIFY_URL: ENC[AES256_GCM,data:szs5R9yEC9t+JKFky+hgvabASE6zhi3/JXM+o8TiQETwlGMgIrt2HSM2yf7hNSxeVf8R4NPvyx+b0b1U,iv:wthFy62s14d+/Q2FGWQMJH8VsxyN3s6ae2KlCAfOCGM=,tag:/jrh3mu7ZbdTnTyWSUYNzQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:wTW3/0tnkZZYZP1NHa+ZjgWZAXnFGRZqtOAsAxkiT+8O7zg0Y3fSlHZLFMBzXIBWnSFyZw1stcbX+uYq/IztEuqgVF64edYGcnCHwd316wykcoi12gQNWgjagjjglqGkE2kbG8Bg94ZQhFGI/Q/OvPhZeLO+GswZrEhnbO7uKqP/nyHJFkiyjRWzqPRAWXfs,iv:/Nmjwl2y4un95V0WqDZXsxMKEB6OweBzvLafEF3zuJk=,tag:wRco248lHrHuXISTL+acRQ==,type:str]
    DEBUG: ENC[AES256_GCM,data:mmHikOGzt4M=,iv:SqLwX3YrSFKBrhLKzfvwsvFnTrqnDMEHhmbwFKgz2cc=,tag:on92GeWyt+V/fhLSaEymOw==,type:str]
    HOST: ENC[AES256_GCM,data:eCZ10SIhPU7cFGMM,iv:CmTsA17wp7r79/Bd7B8/CPWGm7+KyV6hnRkCYdso4ck=,tag:FaQOdbPso5YASiOiTYmapw==,type:str]
    PORT: ENC[AES256_GCM,data:S3VteOL0Ww0=,iv:0Z66QXROszlTCg30HYtmTEesK1HWDf7413gnAECsMJc=,tag:S8ziqmi9KpStqD86MLYtCA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:OG9DjJuPJVbN4SfL9Wb24Kchn9pnsqCTtfLS1n3nDXV7RsiQnm52nt1G0EAVIKnS6SUsubZdXv2T81PZQGpGe09gv7NiVrG7zelJpXbsdj0tlkRZV9MpjxO10k+pVvP217WBH+jJiA4UYeKQpuJFe4sJ9Qb6DIJE35Sd1A==,iv:3SEu84UOolzx0jYZ13RhwLbbIli8BWC2rmYAcsdy63s=,tag:whWQTdONoFQt2dFJklou1g==,type:str]
    RUST_BACKTRACE: ENC[AES256_GCM,data:iGqPmQ==,iv:kqOvcXo3tSyKqucn3A81uneUQKJS76W7IawJct1PVsQ=,tag:V22fG39eMYvAP3lxTdrwqg==,type:str]
    SOURCE_COMMIT: ENC[AES256_GCM,data:fZJZM9gVzATUrxA9BVIUNdFJeQPcJXhuPAQbaHdvE1zdZtwrnBT5o8r3/Ml6Wi+d2wXBFwFWHZE=,iv:GSyN92xCBaB5OaHUSOv6ATutMCLyNCbMqEAJfp+gtRU=,tag:BdKcsmXaVp0P1mk7/DlnJQ==,type:str]
kind: Secret
metadata:
    name: klavier-websocket-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMGVoRFgyTEVyWk9tWHQ5
            eDl6UW9tQVI1SkdyMHBkUWdIT0Y1a3FTMlM4CnpsVEZQZHdoNng2dGc0Uk9JWjNH
            cFJIdWo3UExCZ3VIQUt6ZlBudm5MODAKLS0tIHRhS0x2MFdsUGlldUVGc0NsdWRw
            dC9uTGx4TnY5TGxZQi9QOHh4UFhqblkKi4RbaBfkDF0Pwd+rqgMdRpV9orEEvCGW
            7i1kXwbWmrC+ZiT7MDLM7vWJoI40hggKG5ah9mBIeUPkx+lXX3CFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:jWv4z76rNvtrjkuf9HacPblAjW5TJ1Lq320/S1lX2L1t62DeRuH2YpNwWEItYGvtElpclNR/xSGAfE9MB2YztX5rgB9b5P3EFV/N11BOjj6umihSfYU7EdRKU343NiTigExVtI6XUJeaPBX5wsZyIZkBLfhkCUer9sLbK/rpX9o=,iv:fh24hOjRAue806MPBiLHH2bFlmyEEQufe0w6l75m4P8=,tag:qDl03I7v6aJy24dXuD6dPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    PGUSER: ENC[AES256_GCM,data:u0zI9K0EHosuFfcW,iv:7wp32H31+Ms6QQtqXoWVYHnL/LvZTHWuhbJEj1CgCJ0=,tag:m5/08KSEegO2gPM0Nx4tXw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:FyR6zdK32ky6WSj0,iv:PJrJlpwDm8fF6T812xaCLNF3tOkhSVkAoqWZXJf1V7o=,tag:CiNJJqGJ1hSnRYR6n3VL+Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:T/Sk7w6heRonDvuwysJNyyN6LOINptmkeCktyxFz2Td1z/RpAfJSkO9++lkfngxO+7t3qHshfvUVr1l3WaDjGHC/xyQ01dDpuamwAQ0kfSYgJSlV8eDmWg==,iv:O6WDAA3ZMIeCySD4FSfzyt5R0WVi/W95xZl09Q82Bqs=,tag:sT15DofFG5FA9PyfxVK7HA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:3zPyNFdhG3+SIPyi,iv:ajvSwUiOha9sPCA36Vl9U/6EWnNOnKnnqSRjMfN6TSQ=,tag:E+PtbJ088KWMGi0EltqkBA==,type:str]
kind: Secret
metadata:
    name: klavier-postgres-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMGVoRFgyTEVyWk9tWHQ5
            eDl6UW9tQVI1SkdyMHBkUWdIT0Y1a3FTMlM4CnpsVEZQZHdoNng2dGc0Uk9JWjNH
            cFJIdWo3UExCZ3VIQUt6ZlBudm5MODAKLS0tIHRhS0x2MFdsUGlldUVGc0NsdWRw
            dC9uTGx4TnY5TGxZQi9QOHh4UFhqblkKi4RbaBfkDF0Pwd+rqgMdRpV9orEEvCGW
            7i1kXwbWmrC+ZiT7MDLM7vWJoI40hggKG5ah9mBIeUPkx+lXX3CFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:jWv4z76rNvtrjkuf9HacPblAjW5TJ1Lq320/S1lX2L1t62DeRuH2YpNwWEItYGvtElpclNR/xSGAfE9MB2YztX5rgB9b5P3EFV/N11BOjj6umihSfYU7EdRKU343NiTigExVtI6XUJeaPBX5wsZyIZkBLfhkCUer9sLbK/rpX9o=,iv:fh24hOjRAue806MPBiLHH2bFlmyEEQufe0w6l75m4P8=,tag:qDl03I7v6aJy24dXuD6dPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:Kdgl7xl2K8rNKXrSLvDDsE03dqBXWFuoLeMrnk+armceuSp8CJ0Tgg5gAaf3PB20gOLDi1Todyjq5HFjntzYPp+MJFKs/IJPYCOny8GDuhEj+VWe0iBrIA==,iv:pVAt3etgUmNe5z7N7ygPgi5O7iTHX7wCxTU8CrhCJRw=,tag:+4DWrzhQ3H4sDwNZuJeN2A==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:w0V6I4sSZblQ0UH2,iv:9gtprTwTl+y5qumjn3jl/57+v8jnwn2k/kYVy7YCY8w=,tag:PGtTahNlsAsuqBBEb57GNw==,type:str]
kind: Secret
metadata:
    name: klavier-redis-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMGVoRFgyTEVyWk9tWHQ5
            eDl6UW9tQVI1SkdyMHBkUWdIT0Y1a3FTMlM4CnpsVEZQZHdoNng2dGc0Uk9JWjNH
            cFJIdWo3UExCZ3VIQUt6ZlBudm5MODAKLS0tIHRhS0x2MFdsUGlldUVGc0NsdWRw
            dC9uTGx4TnY5TGxZQi9QOHh4UFhqblkKi4RbaBfkDF0Pwd+rqgMdRpV9orEEvCGW
            7i1kXwbWmrC+ZiT7MDLM7vWJoI40hggKG5ah9mBIeUPkx+lXX3CFuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:jWv4z76rNvtrjkuf9HacPblAjW5TJ1Lq320/S1lX2L1t62DeRuH2YpNwWEItYGvtElpclNR/xSGAfE9MB2YztX5rgB9b5P3EFV/N11BOjj6umihSfYU7EdRKU343NiTigExVtI6XUJeaPBX5wsZyIZkBLfhkCUer9sLbK/rpX9o=,iv:fh24hOjRAue806MPBiLHH2bFlmyEEQufe0w6l75m4P8=,tag:qDl03I7v6aJy24dXuD6dPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
