# yamllint disable
apiVersion: v1
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:O84irM3eSFmmzBO2TrNBTA8cd38HkFUF4t2GdcmRCm38faHD2V3gyEtffcA70/JF,iv:cYiaEpOvBiJzn2QZKa9VquTfkkwIBNua7Gs1BHzkALY=,tag:WZNnmIKeLEUF9TH4gN/6fg==,type:str]
    CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:NjDxGAtR6Axl/sNxDKOtSuz+NGu5QaRPQcxGotcIbC/oKRsaSHHK6ZulrY4=,iv:iDRbex9yxxrOnYUrljah1s8GFaWLR6uIcUG6yxTfjJ0=,tag:docuY/w9WpNd6zQeRs1WFg==,type:str]
    COOLIFY_BRANCH: ENC[AES256_GCM,data:eucKBnd1cH0=,iv:OoyhUiSR7iBcsvxY+pwzA11ZqGdEkj5IZWyhmuqsBAM=,tag:NtR8/R1i/7AJYi7C6gEttg==,type:str]
    COOLIFY_CONTAINER_NAME: ENC[AES256_GCM,data:kkuYFq/ZC9HWt9kDgVrzrr6xM7i4ISJjwMXnmVuYNr0KncwLsepwBsRLxyYRJtmlgGG6Zg==,iv:rmZ8BdNF/xT0WX7VNkRBkjt3lgNIkKAx0dUrx1BKjJI=,tag:rzSyGs2EWF/DEl/2RVhlVw==,type:str]
    COOLIFY_FQDN: ENC[AES256_GCM,data:Wr1SFS05zpRehfEv6T4gqwq5uIchcXnRCglRLIKPNR8=,iv:bByvkJ09TgOskePOVpvfML1nmqhmlhpX8JjesAptr70=,tag:p0mvhj1wzFwjaztTHdNzVA==,type:str]
    COOLIFY_RESOURCE_UUID: ENC[AES256_GCM,data:h34jNwdqFD30jeI+wu0Y+JvHOT7fuw+tG/i/1S4AKnc=,iv:goTVlNmm3pJKtPlD1ZmIxVWr3keOXGMAASNo5tla0ac=,tag:QlTTEKJYvtnLslLiT+Hm0w==,type:str]
    COOLIFY_URL: ENC[AES256_GCM,data:WshfvhM8XTu9HcBvSe60xvtLwjueAeB21fVLF14o1Y7X7ZO5DUENxg9FYDo=,iv:/Yp6oCJS0JMTCazvIxQhTmTUv8M4qRbmgPRnuq+KNug=,tag:nLRM7KE5Wec5P6zGAy2OjA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:l+qwAXF/+hF3BAIKYE0KqzHO6wqp8MH582kWI5Z8403af0D3tbENx8A1vqa+YYeK9kHAFmBQmfW9ieuqIVnhAjN67fPAqdvIES3hqaaU51t1kwyNzvAc9cbInW1pn5UE6syOj+aG8HwvpkiQ45k3mwY//n9+LGoiLS0BVq/F/6+n4XvIc2b5BNiAGDut1aD/,iv:2vZurVhibQH8yUdBca84x46eKiWKhOgCbT5WoX36L9c=,tag:diPCssvFz4QMJvjRDwc+FA==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:iu5lf+K+/oD1vzkempVvIWg5lVQJ+s/uuYTmSg==,iv:KHaMDmKzhzfR+ZJoK09y4b46JC0b7EsE6Q0NLBqJa8w=,tag:NcD/AdJPP7llhzZRbXn4Ng==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:0RKk3DwwEZGmJJrn4cz6T1/mrR99kD9UxSW0KRktQ5JtZhlBD15IMFF0y3XMe3D+D3tvFVwjWDc=,iv:ZSAUv7AF8FlqhNn760npqQoxnUIRjoEc9abLsPEw2Qg=,tag:64Rz9bz1xDjktDpuhwVOhg==,type:str]
    HOST: ENC[AES256_GCM,data:+o/vOk3GfecqE85Q,iv:ilWDeVgKq5UBoBFfKBs3T2HkAN7a8qcQbJpGXLb4PFc=,tag:xJWKcpx0qmfeAvlHu0Kd8g==,type:str]
    ORIGIN: ENC[AES256_GCM,data:MURlT6gq4DtKVTcM24uDUG3iEoCwi/l6X/dE+PlxGrgDxtrWCJaiskt+bWw=,iv:SEYeSmsd6vlb8vYwQNRjVayaDuKOXocG52/1Icbdb9Q=,tag:MM1BLthBLx8xpQ62rpp/tQ==,type:str]
    PORT: ENC[AES256_GCM,data:ceZS0n1a/5A=,iv:2Gg5XyolilGRNrAd7hUV66SODfBmEPS9hY35vX2+99s=,tag:V/XgkJkEFEPEd3ywP9/J3Q==,type:str]
    PUBLIC_WS_URL: ENC[AES256_GCM,data:AN8kje2xhMSwjyuUJYTQH+ArHUKscHXadj9T318FKXzC0pvxjhsWgxtyj4Sc23wTFSo8uxgbmfM=,iv:JA8uDyg8WPHbjzljWLLS7BMcyVt6g+O+GSrBMW6QIjI=,tag:HceEQvprPk6hYcO1RTBNDw==,type:str]
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:rySzlRGhDcbPaHjt3t4bFRGjZroZP+cm4S9zJuJKnmjZFi0n9mvQP3q+7oQ=,iv:JhrXDzT4TOz9MIvBI4V89wUbGj5rpwCy4Ba8t/8lvKw=,tag:5aUGI9+inZ3UVsHglDCssA==,type:str]
    R2_BUCKET_NAME: ENC[AES256_GCM,data:I3Pp68062zGW3vx0yInQKZn1QA62ZtTO,iv:6oGZjiByM4vJ8TT3oBkpWwgbFtMNovtTKbCE+1OM+8U=,tag:0Tblqc8mBhNUaY8X7GOBYQ==,type:str]
    R2_ENDPOINT: ENC[AES256_GCM,data:C1E49LvOSmSeL+VSwTeYKBy4Q44G5rcg6HAhtVEF15Pvl2/bzd+ciQyO/nlOkQmLqfo7sfoI/NX5aAYP0d92RMOkC5yThlLUrWFLdeggEgNld0Vbfkym7A==,iv:xsBicVCirgR1M0R9VFYdz/WY543NVHFLo+u/9YiVaBA=,tag:a/PTurSdtVnu7LVSi56XXg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:W8JKEXHIKHaRoyg3mPdBNMcG77kkI1unCLXYBgCZ1TjqhWNIi76YBWLLH8dxXXYZIt75Kexliprt7Y4NdNrATUwV/FK34x5BL/sRcd6p9DD/Z/vDZAKpPA==,iv:7Mi6IPw44cQ2TowZJdjufgbO9n+FckqWoWkODtVXr3Y=,tag:y8vnuI8o/+C1gOWF38DI8w==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:kPpiIFKhL+1WbCjYTm4jjo7Q8Nz6hrgrk3FLgubd402k1T1i+HPf2WysRCDo7cQ3sh08P8tLHXIrH73+eyco/QdGHeI1g8BRCmZ4fFF+vAEQr2JEC8eWvTXjqXbhEHcvBy4Ej0/0fR8zYQ/hRKiS4Vyfl+Ai5c/suT427w==,iv:JfYRlIfHcPs6maSYw6jsJhYLi9fr9PugzQWNmpln1+c=,tag:U70V6YljjH+hl7Fidp9eNw==,type:str]
    SOURCE_COMMIT: ENC[AES256_GCM,data:PiFiYyKQ0D63/uNE2lFAAVnP89w+yddWJ+7MeTtasC+FAaav+6AZsNdcUU5W8k/UK0omjh3Czso=,iv:OjmKnAWXoX3/i8syASsSN3I6iSqdxspl0KcxKEd/5oE=,tag:ng/t60OIFd3xDnQlvFsUFg==,type:str]
kind: Secret
metadata:
    name: klavier-sveltekit-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0hQQnR5ZWg0SnRkcVJa
            b0dxTDE2d0ExTVFOekppZldMRDJ2TFYxSHpnCndlUVZ2b0dlS0E5dk0zZCsxSnBo
            T0JIT01hTUFuTnVOdEhqTW9lblVmUm8KLS0tIDdJc0l5UVZRK0lyL0JFVmEwbStL
            VjNRUDNuUTNtZzM2bHdsSWhZd1hIUWsKCibZhKN7Q/xWEDhOlWU9MPR1OWMyHsLW
            NzfTI/uR+iryJKCQUQGABhL9BM+rJJanMKkxCFPbrEYuQsZTogBh/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:28:38Z"
    mac: ENC[AES256_GCM,data:0FBRZauD8PFIhv4LU/uqdAso+YibNxJnfBuTp15C2EfHyCy+hvT5hTFJHnof24n9BWdG2kkykC4bg6n2+iRCEBVCN5X/x63E1rjclPZcnnbuBKXDKc0HIfdsnJ7Wt4P4iCZp2N2NuJsMO0YX6+DaK11qh6NrSQDWT8l5y65C5y0=,iv:wwaDBB2CDG4Vyve2cujWzuXYYdw2so9yF08wkXro5nc=,tag:ucASwGz+/kCqyWtrQT2Qzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    COOLIFY_BRANCH: ENC[AES256_GCM,data:amLk/LFOfB4=,iv:zjTpODcKV2bkQtNdhObjcx/ySiB8b3axwkyZCaHk1ds=,tag:VaitRnGACVEYj/TXVkG3nA==,type:str]
    COOLIFY_CONTAINER_NAME: ENC[AES256_GCM,data:5ct/CmudIDfQvNLCCztiu7ILyHvYdRC+EGQfLn0QoD7wRBvt9aoYsglRVD1vFUXLMFBF7g==,iv:WI15LVqauMvhvWHSxTjqtL7Tr2CorU2UATia7LlRClQ=,tag:A4cKnxQdlQ6MYW3Hpy5+RQ==,type:str]
    COOLIFY_FQDN: ENC[AES256_GCM,data:hD0igtye3nztRU3aqd1wyiPSyOxcIUlnWRERM/2d+dorOEWdb2Rle5uw2xJgglL4,iv:aIGioci3VV7fqRlNkH3hcEQOyj+LJiLqvVw2nj81guc=,tag:XL8Yu+9bexnDlkkMmSEFWA==,type:str]
    COOLIFY_RESOURCE_UUID: ENC[AES256_GCM,data:23Zp65XR9I+S5KxI5Qx+Cl2lyPKYiQoxrqK6rRgukLE=,iv:Ck5nOsZ7vSHrUOyELzIQEPLZ2/1bjdAT7mRO4mBG4No=,tag:enI/Ff2ercgT+aO51B9Mkg==,type:str]
    COOLIFY_URL: ENC[AES256_GCM,data:HVCNqdxHCUagtB90Hu/fI61SlQnG/mUXBCxYMLKqGoPnDlsDbxwQXSNKaHIDcerfm9aE2qu+q0VZrYVH,iv:P02zG/cCnhG1q7TzrVFSz6HrPErpFD4zqqSCUKJ1E08=,tag:3/ngUkWFBpxsPuwPR16C8A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:7pzdcYisiU1gmyLQ0FbQV30Q9aW5bF1iBnvw/qsH7Xcfn+u4A7NOA3oUztifYXpJMkKzgr2tIjmCQCNbMsklsDUHjZnhjO+baXoayU0/wIUWoc6KhTgnpUwyEVvbR1Vc3lUbenpCRuzWzXeoJFhXtEEQnYRiyjZfhFPsoYs2SLI1NmgWcj83lDaae34rQObZ,iv:32LbhD9jc3uHiTDNzE9qVF9KAHtqL4k4iNmmxyGXKrA=,tag:ytiwJqwPaFX75wC7n6ErWg==,type:str]
    DEBUG: ENC[AES256_GCM,data:WqyBc4xwOto=,iv:ieQlDv+e73TN9E5oaDl+9Ae5doyJB215Zdix8gCd+r0=,tag:hUdIKfTRK94//wokhsog7g==,type:str]
    HOST: ENC[AES256_GCM,data:/rZfU2WExvx3d2QO,iv:R0QAMBc2cGCcHPgig6ZJnFbnCJNTWu0bllC6Rl/pDlA=,tag:C6nfwZGlBI/gTcn0KzLF6g==,type:str]
    PORT: ENC[AES256_GCM,data:sF0Zv7fGpLM=,iv:0pc2eOQOvYBHbpa1/SocaXxHA92EI80b4egI9d4RvaQ=,tag:phlfcU+AXAiBDXB1qywCxg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:IAoF8SDYosrtqcCwvEKpbnijkmsMO2alaJlua0jy0Iy+t3SX193VCdAar8aEwAEhmMmbgxCFtm6yuFas0dcsHTSqkblRPZmWUAG1q6aLK53tFxU2Y9j0tEN+zHpcALBWGMyfmfN+LXM2dqLB7xQj4MAYkl63Hz/qzoaAIQ==,iv:djgUMFkKaHtEDjcaH/vHU1Avh6frehKatGardQj0pQI=,tag:bxS194fM62CmEdcZnzs/Yg==,type:str]
    RUST_BACKTRACE: ENC[AES256_GCM,data:fGYubw==,iv:LmxgLcmyH3CHCo5t/ry6LKIYPSDFNB7uSQ3jVR9qjd4=,tag:GBU2zimB8lGABYIClcOjow==,type:str]
    SOURCE_COMMIT: ENC[AES256_GCM,data:+fii7GOUwNAYwJ4a5vIrQ4T4iYlAtwiAOQg5bmiQvIrg1YoXDBVD3nVS+UEHGCvOSMk4Pfs7v6c=,iv:kEcpL7tLaETQQW+P+OOUDuyRzvZShZ/ad5Ip3v/eTZ4=,tag:gXvy4awAN15LJnL0mMFvnQ==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:JxQiLb2fNbkD9Qf8MaZz7Alty9aF5MjARi69xogQ2G67mk+RvRPMnmjUmDEmIv+6,iv:hRZRzk5tUGkjlvWAX6mCQqwGoyP52aNnYu932xOaw8Y=,tag:BV2oC2wtSR5GpMDOeHiNlA==,type:str]
kind: Secret
metadata:
    name: klavier-websocket-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0hQQnR5ZWg0SnRkcVJa
            b0dxTDE2d0ExTVFOekppZldMRDJ2TFYxSHpnCndlUVZ2b0dlS0E5dk0zZCsxSnBo
            T0JIT01hTUFuTnVOdEhqTW9lblVmUm8KLS0tIDdJc0l5UVZRK0lyL0JFVmEwbStL
            VjNRUDNuUTNtZzM2bHdsSWhZd1hIUWsKCibZhKN7Q/xWEDhOlWU9MPR1OWMyHsLW
            NzfTI/uR+iryJKCQUQGABhL9BM+rJJanMKkxCFPbrEYuQsZTogBh/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:28:38Z"
    mac: ENC[AES256_GCM,data:0FBRZauD8PFIhv4LU/uqdAso+YibNxJnfBuTp15C2EfHyCy+hvT5hTFJHnof24n9BWdG2kkykC4bg6n2+iRCEBVCN5X/x63E1rjclPZcnnbuBKXDKc0HIfdsnJ7Wt4P4iCZp2N2NuJsMO0YX6+DaK11qh6NrSQDWT8l5y65C5y0=,iv:wwaDBB2CDG4Vyve2cujWzuXYYdw2so9yF08wkXro5nc=,tag:ucASwGz+/kCqyWtrQT2Qzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    PGUSER: ENC[AES256_GCM,data:MqJefOdZ0dUn+3O1,iv:bMPBXM/2yCvXvzsJ18SdQymRQ9k3Nj2NL+2d2qzU+YE=,tag:S52Me/EJnfbnWU+QJ0SIpg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:p5ljtv1tBEZniqQn,iv:O1Dkxfc3P72/BnCIbM68Bl/tjbE/GQ+GJt3OyTC+m+w=,tag:wWho0TNo3xWkl7DqwiYPMQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:H1V9YMQxH+QhMSe2d+TNortH7FnWwuNrbNni400WyzQKVkydFKbfrJtoKZi21f41kvhOR8cT+4RgCE93rG4oYsLofvH/T8gK5BeRxOZql8NJ6uzwCdACzQ==,iv:nsiwCScxlnsSKyXZ7UwNwd4xRFLB507wBYko2CK3lq4=,tag:6O6yGSgMUUoyHhKBRTey7w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:GtiDgLI3KpTKRVCH,iv:omzN/hpLaVSnYcugAmb3Ba54oYo94bmDux/19up0i78=,tag:s4laA78eIqaZWVMaNAIv9w==,type:str]
kind: Secret
metadata:
    name: klavier-postgres-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0hQQnR5ZWg0SnRkcVJa
            b0dxTDE2d0ExTVFOekppZldMRDJ2TFYxSHpnCndlUVZ2b0dlS0E5dk0zZCsxSnBo
            T0JIT01hTUFuTnVOdEhqTW9lblVmUm8KLS0tIDdJc0l5UVZRK0lyL0JFVmEwbStL
            VjNRUDNuUTNtZzM2bHdsSWhZd1hIUWsKCibZhKN7Q/xWEDhOlWU9MPR1OWMyHsLW
            NzfTI/uR+iryJKCQUQGABhL9BM+rJJanMKkxCFPbrEYuQsZTogBh/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:28:38Z"
    mac: ENC[AES256_GCM,data:0FBRZauD8PFIhv4LU/uqdAso+YibNxJnfBuTp15C2EfHyCy+hvT5hTFJHnof24n9BWdG2kkykC4bg6n2+iRCEBVCN5X/x63E1rjclPZcnnbuBKXDKc0HIfdsnJ7Wt4P4iCZp2N2NuJsMO0YX6+DaK11qh6NrSQDWT8l5y65C5y0=,iv:wwaDBB2CDG4Vyve2cujWzuXYYdw2so9yF08wkXro5nc=,tag:ucASwGz+/kCqyWtrQT2Qzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:GPivlLRWjetYMvsoAkFF4apVZZnpVVLs1piM7p0V5lEV06XuMfJqCD15i8Pfz+3fgT0i1V5EJu5S16xpxoIGSlsxpwbgbMpqdUk2Gpaf220GMzrb8qiIaw==,iv:dgkxK/vH0EmMFkhzxbLkYeGyXbHmMd7bi6Im0eTAFt8=,tag:JBY3Tv1TnPHxVrMOfQjdVg==,type:str]
    REDIS_USERNAME: ENC[AES256_GCM,data:EQY87pL2KekoE6ey,iv:hynMEsgT+S4cjpLKcgl86Eq+K1d7SGIBF3dRAtOfnv0=,tag:osPVVHyQbp6DBtg//4b+uA==,type:str]
kind: Secret
metadata:
    name: klavier-redis-env
    namespace: klavier-dev
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM0hQQnR5ZWg0SnRkcVJa
            b0dxTDE2d0ExTVFOekppZldMRDJ2TFYxSHpnCndlUVZ2b0dlS0E5dk0zZCsxSnBo
            T0JIT01hTUFuTnVOdEhqTW9lblVmUm8KLS0tIDdJc0l5UVZRK0lyL0JFVmEwbStL
            VjNRUDNuUTNtZzM2bHdsSWhZd1hIUWsKCibZhKN7Q/xWEDhOlWU9MPR1OWMyHsLW
            NzfTI/uR+iryJKCQUQGABhL9BM+rJJanMKkxCFPbrEYuQsZTogBh/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:28:38Z"
    mac: ENC[AES256_GCM,data:0FBRZauD8PFIhv4LU/uqdAso+YibNxJnfBuTp15C2EfHyCy+hvT5hTFJHnof24n9BWdG2kkykC4bg6n2+iRCEBVCN5X/x63E1rjclPZcnnbuBKXDKc0HIfdsnJ7Wt4P4iCZp2N2NuJsMO0YX6+DaK11qh6NrSQDWT8l5y65C5y0=,iv:wwaDBB2CDG4Vyve2cujWzuXYYdw2so9yF08wkXro5nc=,tag:ucASwGz+/kCqyWtrQT2Qzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
