# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: docs-site-basic-auth
    namespace: docs-site
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:a6DoH7S1ExzBubK9QqvotEbHoIU9wJ6+7UwWbFm14ykbj5nyXNzuBk+L,iv:ypOmIqN+d069g6X5Hl4E9rfi8SzYNYmO9aXz49BniCI=,tag:Md8I0KV28HuPYRb8p2s9cA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TkswYXIvdnpjenVSc3c0
            NnZTOGJiTmZqLzNHY0c2SFIyQ0pUelRpN0I4ClN1b2RTaTdXa0EzNXJxcXBkb1BS
            S2MwUGE3ZnpSMi9RWG91M1IrUEttY28KLS0tIHRLRDd4ZmFOZ2FUZDl3MEpkcW9q
            NmNlV1ZFZ0JLSzA2aXVlaGpGQzZaaDQKK6VctN3/GQgOx64uR+Tdl8hER4YF/DvK
            qwTl+fW04JoDF57pDEsHy5R/d7WL8c8PMf+msPwpkibQuJTjgfVf6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T17:18:28Z"
    mac: ENC[AES256_GCM,data:Rlx29BFXW3iF7WFpwiM+Kth64CoD+HqKw2o/IcGHe2jw6JRKM3JHn144JLAHboG21PVK5BoENZY4lJPUOhsYzsgVzmObITwcp2dr/FJno71yq1WVo/hdzBBs2bdt6jYOGJjqFTIv5pKR+yDHO8aiKAyBS2nt3mkH/ymThvK+1Tk=,iv:yL+egTFjWtH20HMiybDVxYhqkxfHjGNlxgfWlxGmUQg=,tag:Zn4FlqeGX/WbVx98CoT8LQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
