# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: docs-site
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2982KGzzN9mZD/w8ZKP4fcI3S8XRbmMmaCNFN7L/Xdzo8Dvz2RVJVKBsseBR7X3yX94AN41hpnYFHhiKGNJber6pAWXnMhvDuB43432gcm604xCQA0/RHRf7fVC6lavOI1eMTagZJi9iK/dOZ2c/c6/BYzJHWBrZiO/GeZ5YmiFg1ThwOtW1XJkXDLaZ8ndP+XOeCcg5ito5zwJoYcD+e/gPq11NjenmDK7UczITrNePn4ZZGXIidQ==,iv:UyWZKJ+HmyNpJcKzDSRFpHdeznP2KhoVRN5k6IHvJEA=,tag:PBucRiIEWJeXFFEY/EP2sA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZkVDOUlxbXBsOTRNb1U4
            elR3Y1FqUDJvR0hNMnZHWldQc1dQTVVJMEJNClJhbTAvS3I5eEg3dHBKdHNUeWo0
            MWtPdXZ4K2NwK3J4WmwyVU5OTFlQa0EKLS0tIE0zME4vVTFKa0lCcFh5amFOejEy
            Zmo5K1BMNmJTWXBJNnFwcml0dHRuWGMKnunf97wbCiwqIwCej3MbJWhrJQIRCmMw
            xSgSBCorajS21f2HatnxmY2nuDa1vjseV8i6aMsAqTpeTet20fNWJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T00:32:02Z"
    mac: ENC[AES256_GCM,data:y668BnOLzhLLOMtupiSvL4n+N2UXvGQ3QrhEFTeeizhiT4hiRsdU/u2xS5BO6KCdJHVXm1Jt7tEaInesPAMtpkvRhSz578mPTuw6j4R1XJHJwaKWe31ql4kDNIvbj7sylBPDUw1Y6nO8tRlqGquDani7Dwhduunw+CysjYdXwiM=,iv:fVm4vvg0tzgauYbyKKzxUi2rqO71w3WWASVIMFSQ0Cg=,tag:GtvnwqjUc156nRWfC7nLkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
