# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:/OmbdEHYhY2C/r8C/rFGd/cBzyVO3ddp7ZEHLS9AeZcOzyna2MMyUBiPihDr1EDU5/JyLZXv6QKFnEafh4ZuPGbX7UMVFGF8SwHJOvVg0SfbG/nHq1ek7Iv9eIcU60xSjAii87ecZGsQt1e8ms2WdC39hcAS7hnhwsVro7miV5gD781ZeiMKlPOyO23dYb2A8c4JhqUUoPIClxEw9WOPA07s7RSb6GEHlmUrQ3bCU1Jv2DxrScN+3ciGN9u//t/6IPGXBVywgVXkSdt1hJBJsDgjFxewBYlWUAzXWtvuAO0A5inEMvgmEhIi7N0=,iv:6jHe3lzxarnbe1n1IdIspIGyhzJkGSVfuuTF9DYgIAc=,tag:qYIL+SBq2/F2sdH+rltYBA==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: docs-site
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcHJQZjY2bVd5SWZFVFls
            OUZxR29IcHBCc3d6WXV5MUR2U1UzN1hmUGdBClRwLzJidm5TaE10emRvandMNHZF
            d0lveHBvbzFBYmRsK09ZaXYxSnYwdW8KLS0tIHovUGp0YlVUMklkQ0xkQVc4Zkwv
            RzBtQm9vTEVEclhxczBFWlc2YWtaTG8K4ODVwp83nIPRkCn1Ypye34+XYCMA1xJ7
            CjOhxNcIhjfBS6w/38NCWunIk64mjTpNKZLQyp6tqboVG6/Sg3AE8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T20:57:06Z"
    mac: ENC[AES256_GCM,data:KgDyzICA1olHOAO1ZduBPVbtVkXLfJxMm9sQzhTP0Miw40VlY2wlq/02XOtXH7gRBTYDDktS6ANqt0MoUDyksnT9iQZW+Y8Cm9kyorB3m8ckoqTZwsyUji8xzjn+Fz+8g4tIqfvOObEfUnk6wr+dsLajjB5FkJZzI+a/kNbcEn4=,iv:a5xOzT9PmMJo1tQdCoOt/vFhVdIC7Tvj8j+aSUHLbVg=,tag:7DU9p09B9l6NOEo/PA7xvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
