# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: docs-site-secrets
    namespace: docs-site
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:DKu2t+xv7om2WmbB3xcwaFm7lirbyo4yFpLEsPZeYxtX5ArNuEQM+dt5jFHwyGgLxDWDUl8Z0GssLVdG0Mc8Vw==,iv:jAScQjdLO6kPcHB5Mz417ZMBJuL+LLsYlwR7tZ4hVXY=,tag:gTAZRTcOn5hkaLucE3M+Gg==,type:str]
    DOCS_ADMIN_EMAIL: ENC[AES256_GCM,data:2udOkShk8eh7bsOxB6M2,iv:MYdrAOL7/z1tXWwFMJ5537H/cw6gHHGPjBf4hAdDQZs=,tag:Nn+a0Jy9Wwb+94AqARf2Lg==,type:str]
    DOCS_ADMIN_PASSWORD: ENC[AES256_GCM,data:Tlym/Xjt07w44H0=,iv:1qmUnHoAKFoXaHksjv7Mxq025TTDuIDBjYyUb0jsbpQ=,tag:1U6EYyv8rxnppLAYQf4alA==,type:str]
    DOCS_ADMIN_NAME: ENC[AES256_GCM,data:ibY7lw==,iv:B6o/u1eighq2yC+OPqo/wiKvw/cYQ7CHWWCcc8gZLbo=,tag:RI/0WVpHiKmdU5yzW6Vo2A==,type:str]
    HERMES_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:nZqMYI7THjKf6DvC5eobqtn07ZOidslCnEb0nl5r+3nU+SVZfgkGnCaQrOvdO1/DBR2lXvK1LKtrbRcOv1Ygoah9DgXc7qnZ7KitE2pQl10UeDko7D7el2cWupqq64xfB4fzbiGVC/jIkf91DzqY9UvrVq17zFj2cCVlLoavOhefXEYjg7oO5VOTQrZsGG/2cx0y2zURjLA3Ni+OH0WveeOirCRP5YUqduVFfLsBS8AynbVujQw3IjR4em7/3kf3IXpRAD+17+8ZupIXASHmCL6X1ObcNDq0zgyCf2ff6SU49FINIrRxu3xdo98tQdBX+YuwJ8gmGNI2ll58vg9U4E1kzA6gX8sYyrJ14mIiC3KhSnjBfZDeUmqW0weiEewLvrVj8gwdDoupDPm+mxEd87e1XLB7680m8KAKqNOcTWOhegvBJEnwGsqlt79aixUJvSfdrcsCbsSDET7/YT3z6Gnp554Fo88oc1hngAFB5oj9/8BNrDRJhatfGSUm3ryvYqJq,iv:KFp3L76+6H61ooFv/UzSwLwEghNB2zW8s9WR30f4gP0=,tag:V/jd3gcNJHHo+3/EeDNhvA==,type:str]
    HERMES_SSH_PASSWORD: ""
    HERMES_SSH_HOST_FINGERPRINT: ""
    VAULT_GIT_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:ZzB7/SgNbVadzTCp5Fxch1Y1qASRJbHSJl6aYfjdO1sqFzhqdyAg6ZdxK9i6fCeD4wj+myn//Hrr1tbFXH/+05bdf+d+vJSPZ2Riysm/4p5w3WZr1gikiA659lDJEG62eBEyB5zW6Yb2mneQXBCCbNEXZVTMF4CjsHlBCtmzfMhDM2Az146lWfY+fIQt9ncw9nPjQekt6kHhS4M+k9+HeWN63lj2JAR1fjGb3k9YB/LMktYd9uMMjPfeNhCdR2G53NcWrnM4pdYgSFYrYFBs0cEzRANexysk7/FmgHdYRNYS+tq84ERT1hUgOLxTf+RgvPtDEiQyPFm1m6s0UdkGHQMIx4DeKRSC4J4pQm2QqU1AAw3HGS22VjrMxeOIOtXH2F2TmvIPfQlBwt6weQ4c+LlCiSxJ3aR+kt5+X9u4BFRCHZawqmaLqRuTH1AXpqRs+xqQA7fEppkFfZrDup5B8qk45NxWgm8/DfYy6ye3mmqyCJ6ttnS2LpT9ObvTtINz3m3XjKrN267+hmbdtOvwHM6A7YSztkFvAspEjdhjlcdvwNk=,iv:gS92V0Mv4F1bcwj1tOZiMx4pnkoQXEqR0zBWsew0H8o=,tag:IZKOiijkzTCqcyIcArAqjA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TGhIcFJzTGtkbTE2SmJV
            ZS8vSDlueXZ3SHVPTDhVSitWSEd2M1hIa1c4Cit6SEU4T2x5bzFxUWx5dWNLUTQv
            eWs3b0NHb0dwbzNCUDZtaWthbGhraFUKLS0tIEZYUEFWbmVBeERmYjhiM2hMNkNo
            MmhWTFNPbjhFR3c2d0Z5K1JNTTJ0eGsKHV8DDQ8Rv49WrWPvoMwudTzh5hYPoS9h
            VWoTtj5B+7vG1SB1fB7H3u32T90dJSJUCfGZxLipYORiYbbFr6b+UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T08:52:19Z"
    mac: ENC[AES256_GCM,data:lXQfeU5exFooS28zCGooqrf06QMI+6cuIe++7U18Fo8a5TpxceOhl6ZQwKwzgQ5o3lKujZY046UQQtRLR/nK+Fph2hCoDn2T4tezx0T9DGiIOv4quSc5TI4XF0PgeOZlRevm0Z+rB5taxBmNCAarBSSp0HUQyv33nVaQKux88z0=,iv:8LevsZVIqWw2w+1BFNBqf6KSthCUTm6LrpcxX4R07Ng=,tag:abKjG/ZTgvRILDLKesLNyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
