# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: docs-site-secrets
    namespace: docs-site
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:+FzVZYGMQOs7cPK0YlPD9ZVNj9pmKsyGtqU81lWyW4UlayXmRFfERgPyxJZICqdCGRQZlrV+azCula++uLeQIA==,iv:m2zucy4T2Kcm/dt1OLZKgx73m3GZvlVesIvpS3cK8/Y=,tag:ESoVSFIcpxmw2sNkp+YLtA==,type:str]
    DOCS_ADMIN_EMAIL: ENC[AES256_GCM,data:OTcDUKt5lPJ6FhQNMebFuWaLSzs0lWgpSg==,iv:65Wol9hBwyw0SFT22M43k51URkwxdJWtoxC5yLOOg0I=,tag:Ux86+sp/pRu1rdLzRTLtxA==,type:str]
    DOCS_ADMIN_PASSWORD: ENC[AES256_GCM,data:u4lOaM7/dLmLPwcjZN2fXghbffomiqamymfC3+AyIOg=,iv:uYu/klQ92IAKR6odO7DCmsvqGDkSlp7TPRkiMLt9IjA=,tag:JJIppLLmq52SHnGGVlglGQ==,type:str]
    DOCS_ADMIN_NAME: ENC[AES256_GCM,data:Bh2V3Q==,iv:26Fvtp2N/lIaHiUCOpxkjV2xokbwEgWK71cXBiJ2kag=,tag:cj8QuGCKN3CZAcAOwjGHug==,type:str]
    HERMES_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:ZiDmwMos2txfHFkU00N6YQkgXOmtTu7Hd/CZT3QlA0tm8b6PbBFwIPyjn6ZWyfqfn1RI6NygRsWUTkOgP9Jp9vPODHR721sQPBgvAonOsGMFLC/f7l15h86RFqUrtpa4bun1Gfwl8kngviGqXUDjviXPJkw5ql5sCcm4tIBRfShtcaSugBlf5YbB4EYdKm064yWZJS069/en4VO/cR7/yeur/rpIoYLjdykCUxLBOvQT+LK7aL5qxYjVuKc7agWdGC06aa5YyYwu83wX3X3/Xq7MCU5fuhUdirRd8r1AE33xtrNwH0NoxuA6azrGuLmfVR42BEmZ4BvxAhk8Jb39rJvVYEIU+EiPWeffM8nyITy9yTGqCRmGdW3pxHyPpnpwhWANR/1QCfb6OgS2kzBeICQXxyeCgyS8PmZzeWDsYbkyF3uC74RqECx9ndADChPV4vQ+ArFYE0avfolbE9r3gaf8ZMI/AJhLiFheP5A/Y6RRWg91JYsuH6OZHi2ku0QpNYCI,iv:2v1h68celMhkhFSwbKB3sPt9tdRX15qM7upIjJQI0Vg=,tag:rtHEtx+YqDrWV2l3BKYJEA==,type:str]
    HERMES_SSH_PASSWORD: ""
    HERMES_SSH_HOST_FINGERPRINT: ""
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cHJGOGp4dU51dWhkb2FK
            NnB3ZVQrSC9nWFNUL0N1c2l6OE14eWJDcG1rCkIremtwamhRR0RRNjdNcUxhQm1E
            V3Y5aVFRSW9MQk1aRTlQTFVMY0xRcTQKLS0tIFZ2RnhuSHFwSk1pVjhoeEhWVkdU
            aW1ZeXdhZDJuVzR3L2Z4SWgzZU1tVlkKcnF3WXRKugwuSHQ3rl5sp61AhOqidjH5
            rfe5CNPYlJU8TKmhsBJAH0eeWgYIdhf6hhDK2niOk1Z9QbBOfYKTHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T20:07:55Z"
    mac: ENC[AES256_GCM,data:2W3rGXv90nR8WKBtdvNdb9bZhUOsmdbkpfwo0RL0RBs0w/buAAoL/ZvLvYNZwWvMzg/UURickTJ/NumY5eJOOm9xo7s8mF5PZ0HjxxYRwg2t68B7Wh1Z86tH2kJzLkzfNopYUzKQYUe/GGXn0CbROcIo/WvIxexRljwSvp2n26k=,iv:iSPmNZ7ZjkO7+2QcfvaU3foADSS1eZo6Qf/UIu3fAZA=,tag:9MO/AwU1sOjTLuckhc0snA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
