# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: docs-site-secrets
    namespace: docs-site
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:h2y8pJjLOfZlBtlCUiDRXsPTzYiHeJP+dyGBKsZzK8sbA7GVsJ01SVibJOnY5i9p7wPV2gtsVNHdkKHV5BwqdA==,iv:XrXzqCTDhHUWvA7d1pdLS7czzBfNUU02reEVjdAbKkk=,tag:ebHj+fN9CLuIFzyGIwefmg==,type:str]
    DOCS_ADMIN_EMAIL: ENC[AES256_GCM,data:LT837PoScl8EkQ+DTeyd,iv:Wn/ipfmlIdYmKf0CvLGuRVvAzmbKk2I14ma0g93Tqvc=,tag:6nK3VwTE8izaNW2JvTDYyg==,type:str]
    DOCS_ADMIN_PASSWORD: ENC[AES256_GCM,data:nPVsuaHIbSVFIB4=,iv:L+hNFlz9mYp0M0pDGVX7vSuhKFOdsLjYd8sdkgKzjIc=,tag:j6oVB9h8HbFlYn1Gn5f8kQ==,type:str]
    DOCS_ADMIN_NAME: ENC[AES256_GCM,data:AjjIKw==,iv:qXThX6+vGMEoUcluU+06BUcVop2qFW7dpweDqiZBMoI=,tag:PY8mA/2ahqiOG1RRqNViPQ==,type:str]
    HERMES_SSH_PRIVATE_KEY: ENC[AES256_GCM,data:sDZfiBsiTjMx50L2pLkpODZnBwN5i43V024RMtERNS2mgsi42pJgW5knb1vQ5gIgA4Vme7POYOVOpcIgiEDR8S9RT7fkYB8m2f96VCVqK53G3fWP74YSmKbxGJZHXvpjZPL0RpPSgpH9YCtLmm0tvUH5aMvTb8ydni5gPZaT4q4vL27/VOoYQbx3YyKPBn6YkiKzfXongDH1zTawZAtv48bb3ZJxpdmC7M7jEZFug//f37ygCZgo3Kf8pUqZpriZxxlxkaJMpLySzqPilJFur2qMDdlq0cAyJ4xG3AO3g+e8H/3DAtrK8V1RyGSnr6PRfyt2FqgPrEBJwtOnj0hPbohL8yxe7yIKSlDNZGkyNRofTXq6Eve6ucyUd3Tr7Df9yzQ+HvLSkv4O0MA5uLUTCVnhvhEPotlMUTh4cra15keCDkiEw/XeQd/49DLhr4CFtmaa9x/CXiFuSJ7kkHXyCGrzuTxS4N1gzzabgOwACzZehQIDwITDnRpROwt4SpAHpgqo,iv:w3yr+KaIs3uuP1UIaRO817e5e4oIol2OnlrJpJaK1RE=,tag:lCYBae7UYP/gvTS9OyfMSA==,type:str]
    HERMES_SSH_PASSWORD: ""
    HERMES_SSH_HOST_FINGERPRINT: ""
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bnc5ZjVTdVZaQnljVWRu
            bXJla0VnbG4vdnFWUk5HZFBvcFMva29OTnlRClh3d2c5L3BDaEk3TVZQOXZJK20z
            SEFMd1ZvUmpQYk1mODcrUkJVRFJPRzgKLS0tIDZrTHYyWWpNeW9VWktFemZwZUtP
            MlNla3Zud25BRXRZenlFMnJnZDcwYzAKiskN+I1NxwkSEDyE05Utdi4Ag5Y00Nme
            jNY2OKBnH8V01vsQzU/zmDUnwn52rciegICvBrxMnkiZfJ5WBZqTwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-22T05:31:35Z"
    mac: ENC[AES256_GCM,data:ie3duu8GmyPltfdHtw/Nyrn36xIlzCVPHUhAZLinHFFz2HC87FHi/5M6YMdq4l5VEog+VHa41Hqu9BPjiI/cTqjuOod38qNLt8RdyKRNCtJ2eDQCSJY0zWr+ELba5XEeMu+95HFC0OSiQn/C9z0OsYkngHejDOH0Gi+g8/tAPSc=,iv:Z7Xy6G9EAvI4YcE6kKxAI8QvGH16JAixx4Fjmu416cQ=,tag:YGZuoPw7NoXCJX4MDM/d+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
