---
apiVersion: v1
kind: Service
metadata:
  name: docs-site
  namespace: docs-site
spec:
  type: ClusterIP
  selector:
    app: docs-site
  ports:
    - name: http
      port: 80
      targetPort: http
