# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WucTFcNc9GB01eq4+ZupbCYqK3niaeK7HVqRae9Vv6VH92biSJsXLQVrAwLpAsFrew8rxnVOb9MpY2a7BN1Rg6/XSirDhdDfmHVkjyhn5ZOuAI1HyzVhZPjQISBzOqzVFKLs,iv:PMEQAXDUMBshULRm2peKxBZUxXg1fs6f3E5hAAao3Gg=,tag:FCE0pBerlr4axe1C1rfdAQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOVlpMkRaUzd6MkNGcUNa
            Sm43UitCTHNJU3RFYW9USXAzcysvQ2xvdkhFCktIR3BnRG9UenhlVDhoTE9sL0gy
            Q2pPeTBaSmhmZ2JCR0F5OXZDT1VmbGcKLS0tIEhPV2F6UjI3UUtsM1VveGovdDZh
            T0FXZ0hlNFFtK1diRElneXRGakluZ0EKUMj4VFPAHn+0hULy7ITq8YMY6UUfpA/G
            iZSCK0gosBJQ7KQ24JHF0yl5BoR3eKLx4vFStufmDdk6bSHM0On7wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T19:47:05Z"
    mac: ENC[AES256_GCM,data:bA7GiKj4sO249HPJf12FtNZ+z6mKTFjl3EB1hU/st7ZhLtUuwHzFXRASrvm8Bp5U+dnbrg1eJODM68JweEkcYrgzmOhLJ2opWivRTG4EVEP226lJdSsUMsR1WUQD9KDHe2GyB0w/r2DF8W1jExLP9Bm7V8W2najcCbDzsNsXjiw=,iv:p7fcWg3yO0wL8i62m/ZAQFj609GreIlvgiR2beWv2nY=,tag:jbvd4Kpp1HC8PkYPmrHdBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
