apiVersion: v1
kind: Secret
metadata:
    name: nas-ftp-credentials
    namespace: storage
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lsEiCzY=,iv:6k0dkf8nkHuk3o9esoN3DZn5HeM3VgCQV6vFVhpIQms=,tag:vFXPTjD++MxF/UO2l0zFLA==,type:str]
    password: ENC[AES256_GCM,data:rfIvQqedOe4AwYbAJbPqWErTDUqZLnqTEKlnVy0E0QnR9t45,iv:0ld3Dx58/eevSXllDEoiVaMIElnscCtnkhb/hLJiJ14=,tag:ZegR+XAVzkOO/H9iNis1WA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWkhIV0Y1MW5sRXRxQ09w
            ZmN3SFhGZm5EMzN3YmJKR1BxejNwKzVJQlRBCnNXWDQrV2pDL21YYUdXcytxMjU0
            TDFIUC9yaW5KVk1tVkVudlZYanpWYTQKLS0tIEFzMXkva0tRZmx4TzBmSXZUOE8x
            K09jajNxeEl1Y3RJZ0toSjZLaEhmaG8KcV3fViMQ3xcnHONaoWyo0GaCBJXWRagE
            LaHkD3aQPSNZM/kNjeGjSdTYk6nRLNxeYyXzPmBiBj6FVG6n8g+JTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T08:26:08Z"
    mac: ENC[AES256_GCM,data:gH5aXAwPgITS6sH+irfZbQzFg6gy8XKgyTfNlZ8olr3xku4JF2/agVC7JjCCQKtJViVgND508GKKzYXXvSGah0swAdKL9mZ9sosMSgX1gi0NA2R3lGcKXGgp04jsGW/mUKh6PatEnj0BJNyyWfu/a8yY85x8SU9P6ivCWNXA3eE=,iv:FP6iUcMEX4dGTqNsoxZqyrFcf2cXM+wJef+IYAUxR9U=,tag:D+l0tNYX8DVA0YnitSXVcQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
