apiVersion: v1
kind: Secret
metadata:
    name: nas-ftp-credentials
    namespace: storage
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lsEiCzY=,iv:6k0dkf8nkHuk3o9esoN3DZn5HeM3VgCQV6vFVhpIQms=,tag:vFXPTjD++MxF/UO2l0zFLA==,type:str]
    password: ENC[AES256_GCM,data:vUpcpaBa+80R5g==,iv:Zeu9CC2zkQuhJmkl6Wi8gWdxQ9oq8VIE00LcBfwPh4c=,tag:r8uwHtH6aYfEl27fGoP1gg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWkhIV0Y1MW5sRXRxQ09w
            ZmN3SFhGZm5EMzN3YmJKR1BxejNwKzVJQlRBCnNXWDQrV2pDL21YYUdXcytxMjU0
            TDFIUC9yaW5KVk1tVkVudlZYanpWYTQKLS0tIEFzMXkva0tRZmx4TzBmSXZUOE8x
            K09jajNxeEl1Y3RJZ0toSjZLaEhmaG8KcV3fViMQ3xcnHONaoWyo0GaCBJXWRagE
            LaHkD3aQPSNZM/kNjeGjSdTYk6nRLNxeYyXzPmBiBj6FVG6n8g+JTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T08:23:55Z"
    mac: ENC[AES256_GCM,data:SznR0B2Zkg5k2Tdd2BpHo0gcw4NdI+SEMdCuWT6Zbxy5h3HkKO9m/hqrMFL80JORqo0eLQlp/LrAYqCiO+fQIWYAzgSl8mPcAdUlsl+uITqdPdFUaiMPKiBfnfBoEVK0HaeQCPQa0zwccnkDy/T9pdBWiiUzx+38AmsVeMAu1HU=,iv:3TkRYCNQz0GeFYIeGk0Bh33chAr/0J/BPnK2kEfOu9I=,tag:JQDC+hUVsa8OLBun+HT2rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
