apiVersion: v1
kind: Secret
metadata:
    name: nas-ftp-credentials
    namespace: storage
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:lsEiCzY=,iv:6k0dkf8nkHuk3o9esoN3DZn5HeM3VgCQV6vFVhpIQms=,tag:vFXPTjD++MxF/UO2l0zFLA==,type:str]
    password: ENC[AES256_GCM,data:G98uW/l27IEy3mwLldoCa9adDe7Padc8Le/fzWhem7CwLSY=,iv:HqjpFWpP1nivOt9nOXC+m94Jp/HQ2DJOHtkM4MQw4mA=,tag:dwa6oxtMwRC146hVwxpcfQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWkhIV0Y1MW5sRXRxQ09w
            ZmN3SFhGZm5EMzN3YmJKR1BxejNwKzVJQlRBCnNXWDQrV2pDL21YYUdXcytxMjU0
            TDFIUC9yaW5KVk1tVkVudlZYanpWYTQKLS0tIEFzMXkva0tRZmx4TzBmSXZUOE8x
            K09jajNxeEl1Y3RJZ0toSjZLaEhmaG8KcV3fViMQ3xcnHONaoWyo0GaCBJXWRagE
            LaHkD3aQPSNZM/kNjeGjSdTYk6nRLNxeYyXzPmBiBj6FVG6n8g+JTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T08:38:12Z"
    mac: ENC[AES256_GCM,data:VNV2qIQ+a0OsWfg4fx5PgvbZeSdXrWnN9U57q0QckPpmZGBCyzixkOkwKDRgeQ45YqVffAP1xyd8FGrUbG/Cv3O9AhaUSfDZdKIAUcqGHAi9JNsz77St8FcuxLv7wdeRln0q1+UqUXHCoYGwsWzy8wBIF+b2p3Q+7MjqRr+FTIc=,iv:8QWv+/4qLwofQO4tz5yVAGe/jynKZX+ek32Nbu83uVU=,tag:IHV75oTLjxxDeZpT5pRapg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
