# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: comet-secrets
    namespace: comet
type: Opaque
stringData:
    ADMIN_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Wx3JIw+2uMdlsHEvTro/P4FIOo3kmMNlHauDdI+3Ddubdchd6Xr7B68ZwWm29VccDgXNPmGCugfw02ECIls2gA==,iv:8UlFEO28TcFrAO34TLmhSp64iHH5l1yZ4gmeHMFc45E=,tag:FO8S4+u9LK4ewEEEjUhjJg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:SIPZ39VfXnmWK8CrMwGxFE5uZW2CqYoWlpD75g5CwlYf9iAcXeW3e5Jsv9blo2B+/QLo1KmZ7H08z9JluNqJuMAwGqlPYGVMi5OKH0XkLW38MCONdDxdmYc+bOurw3WaXqQuHM32xd99KOBujn5PzjXCIuSklz632UoiGnF+M64=,iv:RtOgwhG//GlvQ3yy3Jv5h9gCHwFyhLftMbEZoPJ3WZc=,tag:Lt+h43jTdLl2sLgM7Kyv7A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:8gfsrO0jBBUpu9jgOY74zTm8Y1KH8CeSwuqkW+G8ssAHloQdHzCjsStxFVfrja3ggoivAjtTezrlPJxg5dv8x/ak4jJnOwUeTCIrsMvEmiV3gcIiT+TFNPUALifX2GvatA8eZitQuvN3tWscazFnih70cSLyeYzh9AJCPm7Hb2VqOcXUK/1OyBzE/zNKfIhHOtHtoyAJZXHpsda7AIVAOqnDSRWC6SciWv8z5lfdAk6lDOQXDgeO0tI7ewH+L0s=,iv:G8atNbJ803g/Wcw+Bzd1rWGubKm8Qmm3cW3MsqKH6fI=,tag:nmN+eFaYCu76NlSML9YEwQ==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:VZLHIwdV85dn2tSTrU9ZvAlZa+ro68repJG1CuI7cqE=,iv:+hYY9AX1z9tJ/aNWL6Kmr4OjvdRqpxzKyyetLFYEjXk=,tag:TCSi4IWtzj+y1nlt7JAa5w==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbkIzaDEyM2Q2UytRdkh5
            d3haTkl6T29YLzliR0thZG1oUVB0UkJnWEVFClN5Rkx2aENld2lLdll6TS9SS3kr
            SXE0RE9TS0Q5WXdYZGE5WWEwbHcvSHcKLS0tIFRLZ09ndis4VDllQjNTWk5sV3BB
            aDU1eXhSWmk3K0Z6UkVZRFBJSVRCM2sKfpJRPSImb2K2m3Q5fQhsWWbUYUo+FE1j
            G4SunSvxS4myFRt0diw3AhIDuB1g3GjIEPJkDD5fn2e77g2CPyW3FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T19:05:35Z"
    mac: ENC[AES256_GCM,data:o/XwjTruGCmD5WDJVLf78rje2uNfUtJWHtmEr4X/wuji2XllF6S0hBm2vvSTxs5kiYH5F3yIdqY5AXeMppNYqbInKyycR+D3TNFONlYxQ8PKDlgAk1JOoFzUCHwuaGNctfCVoM/TawTotVjakDV7jjfLhvA8sN6ciRQENOOtLJk=,iv:mOzTsYls4fXkSPA6fQAcYyJgkOxxPWRy5Vy4VnMwr4s=,tag:A5ZN174E0injKHxqMLT21A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
