# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: comet-secrets
    namespace: comet
type: Opaque
stringData:
    ADMIN_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:Wx3JIw+2uMdlsHEvTro/P4FIOo3kmMNlHauDdI+3Ddubdchd6Xr7B68ZwWm29VccDgXNPmGCugfw02ECIls2gA==,iv:8UlFEO28TcFrAO34TLmhSp64iHH5l1yZ4gmeHMFc45E=,tag:FO8S4+u9LK4ewEEEjUhjJg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:eGX+u+fgVd4tJWimNnrScjJ5R2tRXeWeR6JPUvxEI6MWn1FzXk36ZpFF7kFi0BJvNnFBJEVnDmmGbiAorPkCuQ==,iv:jgsdTZT6ujsszumYUx9ofnb7LvYbZQieJ15ji1F2K/k=,tag:NXpWMGWiHn8302QQpllX0w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:4bH4MJffHaZV6YqLyp2yBAG5Z7IlVMerWuDhqAAmqi9NLEMCH0E2vPZcubB3J7Z87UVjJcZXuK983pv4HJiUscq403rvoSPSOZ+Qo3WwG9GJZ+d0HwVLxTAeDCoU0qi3lyqWTMOVFpUPmL5ycS7zvCAs,iv:G3WJIZdedG8kBvF/Dtget5mNaBb6L7mrfdlc78fR3Tw=,tag:0TDC0YnHWN3nE4xOjkw+ZQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbkIzaDEyM2Q2UytRdkh5
            d3haTkl6T29YLzliR0thZG1oUVB0UkJnWEVFClN5Rkx2aENld2lLdll6TS9SS3kr
            SXE0RE9TS0Q5WXdYZGE5WWEwbHcvSHcKLS0tIFRLZ09ndis4VDllQjNTWk5sV3BB
            aDU1eXhSWmk3K0Z6UkVZRFBJSVRCM2sKfpJRPSImb2K2m3Q5fQhsWWbUYUo+FE1j
            G4SunSvxS4myFRt0diw3AhIDuB1g3GjIEPJkDD5fn2e77g2CPyW3FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T18:01:44Z"
    mac: ENC[AES256_GCM,data:MBrdqpXCNMwfg2E5a9QGTYLd/O70QiNlM5X8058rkbPqS6kYqJpa9Q5HOlLIaNUjT+mVN4PM1C0AiMaJqdwEkS+gyglFZm/fN8+ZfK9MJmvIJdddwoylLzs1Ejbblrs2Qnzn+H5qfs3xiIUJ8mZ6Zty1oJex73hpO01IKbC4u18=,iv:g8/Y18oIZs3ZjriRoZBdeYeVIKW6u1dnce+u+FCk5zw=,tag:96CC/DH3madx4GuG7uxVZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
