---
apiVersion: v1
kind: Service
metadata:
  name: comet
  namespace: comet
spec:
  selector:
    app.kubernetes.io/name: comet
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
