---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resonance-bot
  namespace: resonance
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: resonance-bot
  template:
    metadata:
      labels:
        app: resonance-bot
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z redis 6379; do sleep 2; done
        - name: wait-for-pot-server
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z pot-server 4416; do sleep 2; done
      containers:
        - name: bot
          image: ghcr.io/jvz-devx/resonance@sha256:f3f21b2a3bccd26810923390ca0af95f2252187373bfde6a58eac8899e6559b4
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: resonance-env
          env:
            - name: YTDLP_WPC_BROWSER_PATH
              value: /usr/local/bin/chromium-wpc
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 600m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 1536Mi
