# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: librechat-credentials-env
    namespace: librechat
type: Opaque
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:/D2oS9d53QPPiWfy8GeDOXDgwgX3Rl/jjqQpMFyDO83fAHUPGAr0H6JUbUZ6EzLwPxfXaISDx0SxmAtaFNwLww==,iv:YEJbixG2/KK/pjuBFUPJeMHJ0uYWm4wrsaFc5yEYsfE=,tag:8v2aubhgJy5piNd2dkFrAQ==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:lJZJbHbU2OturvkCNLstgnTwUXheEq5DeLTXgNzj/Qo=,iv:picCGD36qLXnA86BRD36pOCWV2ksjpSPui4mxzGWZHE=,tag:PK2EYCK6/nx+SdcvqsAL4Q==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:P3X8DrvhV00t1iC87SX3SIOxhTZjQm+3hcYr/RyOeHztQCND2ibxmTtzyg3Ex33CDwcw8SULDI0+utpq0SgGUg==,iv:yXx3Y5XAlVeR6v416cLYqC7jgkfnTunws2nOg6b/zYA=,tag:POitIRv5/Vxx6tMJYQ6xkA==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:JdxNoqKsmla3S4oLNrZhLVFqeCUQz+k6eRlKNv4QrrlipDerWbeAF6xNtLZ8oaOOfVOZCUgQIY3cnaPISXQGug==,iv:yiVAcdrH4ctrODAujO+grhmHvvFwl/GLpML1i+488rk=,tag:gIpyatQBFf1195lSZ0ot9Q==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:/EPQ4JbJgOddMC1gLbINNMr5KAtDfSulMrWokjAkIyATAW/3vseGWNBO/cswEJfWPmBtbXydWEvvCN6dxyGZfA==,iv:tinEZZTG9yljzq2sKkHAuzUqXlVLs3lRtiLGo8GC/OE=,tag:GhQOsa1BC7lX79HSjOUlAA==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:yABHAk20jMJfUkPU/LKFs9Gal3fdSFgCwL/kibF/VSb2pJVR8ivsfxvthztvv6zyEvShLCWs0mrtilxD3fGo1grWaUnfE3O4,iv:PX4FJ9oxSwYWVQhkuV4R2/luJIym44b1/ZDDAjdNsNU=,tag:BVso6KaHod7Y6kbEyMLntQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:fi94r8hNdgVAwuaE9ednI8zvVUnudSgW+D6TE+Xw4//WICY=,iv:BO8H/682iBKElRRh7r64sbByT3U4vsUKPH8LhXQr0VM=,tag:5HN0axCn32r+AI4OLdL0lQ==,type:str]
    CLIPROXYAPI_API_KEY: ENC[AES256_GCM,data:ibBV+20ZpbOlCnk3sdtBlGvM04ZffRGi3pmgGFQ4T43JE8ReheF0gRX2F/JwArvAvltrQw==,iv:9wxtBiXCfAtFEV+rvD83H2WQVTbxruUHuXPlmR6CUiQ=,tag:uOvBKM6K/p9bPzbn+CG5lw==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:HfvSP+cYRUiHh6cjCCvsaLPZ76hK86X01xFSXi9GnYpRqbO6imsleY4PzF4kms15Vn9X4tvKSg1hV1cYcY7DTSD8iloO/nzAxQ==,iv:ZmSXmoTDwQ7XhsMhNVeNxCGeidaGLTL+6sDGYJncfeM=,tag:Rz1iSlP5wuiq+C6oS7jh7Q==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSUkydi9OQnNVQWRPN2V5
            M211WVBlbUJYeVM0UHlwQkZSQWlTWXpRNjBBCldXMGQvNjlIK0NIbnYwRWZROHNS
            L3A3dERNVEh6Qlg3MzVwR2RObW9TTVEKLS0tIFJqYis1M2RtVm1uQ3B2bm9tUlhR
            aXpDaXRONU9LbDJQSmNyYU5rcjE0d2MK7TDZdXPiWIWjlhBPXj/kpXsaCfKV74KL
            AHyKsgX2Ak8yKE/JDrHJYhUvqM+I68FASIkkoLA6D9nCJljdww8mOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:40:07Z"
    mac: ENC[AES256_GCM,data:6eureBjzlaFGONem2ndtIB67eMkP6+mxi7wxv3Ak4Tzgg3Cpr/qF2ubHa4/ZHOkkclG9wQvAn6F9NonpxwKk5chglgXULf2Py9Vh2jkI5EqRU0NydiYeR/KwHmcosDcu+pFKtY93RKiiaJjn8UdWTCmWb/Xz6wofL5Kb7ToEfRc=,iv:wpnj3INDnQxym9kZru6k5/j5ish/xo+yC6w6M7CUciE=,tag:JmTqzJykOcP63bSh0OQ/Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: librechat-vectordb
    namespace: librechat
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:2ZqFmVpjhFPzliVh1tewtmncpXNFG3EepL8AOUR5Be2iZs0cfZKBErjl07O9e3JfL7jpnOJeDmjUzlTCh2XuHQ==,iv:FqydIKi0QXap0k/UgeTQtnAWME7Uckc83ZcZ/ruerYI=,tag:EBmPMIGf7YF//B7SMGspMA==,type:str]
    password: ENC[AES256_GCM,data:cY5dgNnyBSEEEJG0xt1ErCToremWXHOhlOUT0KpifYNjoRmmKkEDrchgXV09oY0BdkZliDuztN+8gqZq3SqwVQ==,iv:kbNidNISnTT1gcz9wCUPfCaIWtuMkqRshwtcaLVBPPU=,tag:8JEW7DZddbujqBuOxNJmsg==,type:str]
    replication-password: ENC[AES256_GCM,data:wW5xY5P7Xb3oBrNmKQ5CZQf7s6dQFC+cXzNhulyah8UR0FUPrTl4qC4+NSn/qpBzgJ/sMV3k0toBtGATE0xquw==,iv:xCdS6klJY/AuzyCCHr4FpVb+BIbg5bf4jkcgv7MGb4g=,tag:k66cEc3p3G051EyGkam1gA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSUkydi9OQnNVQWRPN2V5
            M211WVBlbUJYeVM0UHlwQkZSQWlTWXpRNjBBCldXMGQvNjlIK0NIbnYwRWZROHNS
            L3A3dERNVEh6Qlg3MzVwR2RObW9TTVEKLS0tIFJqYis1M2RtVm1uQ3B2bm9tUlhR
            aXpDaXRONU9LbDJQSmNyYU5rcjE0d2MK7TDZdXPiWIWjlhBPXj/kpXsaCfKV74KL
            AHyKsgX2Ak8yKE/JDrHJYhUvqM+I68FASIkkoLA6D9nCJljdww8mOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T18:40:07Z"
    mac: ENC[AES256_GCM,data:6eureBjzlaFGONem2ndtIB67eMkP6+mxi7wxv3Ak4Tzgg3Cpr/qF2ubHa4/ZHOkkclG9wQvAn6F9NonpxwKk5chglgXULf2Py9Vh2jkI5EqRU0NydiYeR/KwHmcosDcu+pFKtY93RKiiaJjn8UdWTCmWb/Xz6wofL5Kb7ToEfRc=,iv:wpnj3INDnQxym9kZru6k5/j5ish/xo+yC6w6M7CUciE=,tag:JmTqzJykOcP63bSh0OQ/Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
