apiVersion: apps/v1
kind: Deployment
metadata:
  name: rudy-website
  namespace: rudy-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rudy-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rudy-website
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: rudy-website
          image: ghcr.io/jvz-devx/rudy-website:latest@sha256:d8d180a172e44b89d697594b2964d0f6858b2e1c2bc6c9a70772a11128c2aad9 # {"$imagepolicy": "flux-system:rudy-website"}
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: 0.0.0.0
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 512Mi
