---
apiVersion: v1
kind: Service
metadata:
  name: rudy-website
  namespace: rudy-website
spec:
  selector:
    app.kubernetes.io/name: rudy-website
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
