# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:xh7YB3bqR6QlnWciydq/tiWGPjQDYebBrObORIJBTLXxxzKnetcvmgKGdRQUWY0x6YHfgpY9742v6137/B/nQNphcnPxMdeZhmdjHx4fOt5NKov16P3yib08wcbvqd/HTkAjGgoQYj+zNtsLD13yy7ZqRB8OSqjiGnDmvmjSdmk+WkdlLP2egaSLqMuh6PYuenbeLi/XUoa2xx/4ERABK8L7PlYPl2c3Myyi+fHtSEAfFdFl0q5M82huX63tDNUcSJkEpmdGn5tdx/BYuCiDKO0WHR7gwrTjDNYRzcCXQXzGlMbwSUl95m3lfDQ=,iv:8UpcfJ0CSgpdAVTR6rWn4bJYOy3lvALBSWwSmYR37HM=,tag:nSqA22unFMwuyl2Lxm4e4Q==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: prowlarr
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU3B6bFpaaTIzN3FHbnRy
            bVFORTk0MHMxbkFRVmY0ZVExWncvWmRYYTFrCm1sSWZNQ2xYakphbS9OaXI0UzJ2
            SGRMU2laRnVPUXVFRFI2NUptUTBXYWsKLS0tIElIeG8raFFDZU83dFpwcWlZOFNn
            UzcrUHU1czhOemlwNEtqRTNkclVaUTgKaNBjTRoNzRpeahLZtV9QCBYeGcySNm7Q
            pyExnPdoDtvwaHppfgZ2VqsPk3h/HLryQAfQNCatrL3HF9OInJ1P1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:32:56Z"
    mac: ENC[AES256_GCM,data:GDzGw5YpeIdxMsB9rS+1EIfOyY/9nEe9iTjt+ghe0OBHDK+jWQtJU+9r/uVORUl0MNBFC/0p7hpWOfQB+pN3o3JlGhoQo/Tt3vLnLgps0ba35LJpLH2Nv4s+50HzQN1uk3pNTUJW4xgxB3AuJ1/VN1TI57xDB9skibid4A8voG4=,iv:dZ01/j/i/Xy7Sz3HvM8xyCouotvKRwWXYWUdGS96ETY=,tag:smoxxb9lUCxFF2BhbFAZeg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
