# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:GXVFHfdU50UTMzliEckEZzLsOgtLelx7ufOhZAvWcNIRlDOC0qfza9eEz708aGSn5K/F9pWrhyziNTOgHmqJn0N8UV6mB2B1iRIqMNS83qs87EwTPXhhz9dSbE8Hhmg2Mh2B8jXEBk1FHJneFcX6xfM+1KdytFvn+oPi6s/rGokiEjidotEBU2e7ApkVwyjgLh1cEbohfWEDzdzJvzfmczKH7C5Ku2SmWi4A6zVyeZ+a2NkHzSSxHTHURT6nLpVDm3WOXgBcIkGDdGCV9Mv+I58Da9P2E9noygUs3xh7LkIDIQt0nsMUdSZa40e3fN+T,iv:E50hcd8St8N+kOLqJVrjbgkLvjgVp2A3RZn72OheT2w=,tag:HEtUa2PODbeq1SLX0D+UoQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dko5eGQrV1FxRW5xVFc3
            Rkh1YmhGSWlONitlczdLcitiRG8xZkZkOVFRCkYvcGVxVExNd3lPQWVwVGsxNzIw
            VDBtazFteFhCZ3FOTUdUWlBBRGhFQ28KLS0tIFA2ZVpsL0xkTGxaL25LOWlqVWhD
            Y3VPQVNndWcrUUNSaXY4YVlYYXF2VGcKkmDdicN4LgacAedmwHhAvDAF/lMg7cnE
            ZHHlpFpn2ky9jv7RnC5qHgwNNu5oJmoMgW0XYglHkpDE52pFin+EuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:34:33Z"
    mac: ENC[AES256_GCM,data:vSLPWeFcdWu/yz5RUk3DiJ30SG+ZhR4O2T7Gl7/JfzqTJ1+bTh86tBRvzFKM9+phzuMlMePr1dZ2X6bvNKxmiUWwRwX1s6S7Eqk3e1gO9E9GiS1412Kse1ab+VKR41Jf+rOaf+66GUfpNeMR8ZdkS57+onCEZ7ZpT8eL8g0NNKg=,iv:DnBmCUfCEwnJkx3Uc29LVwyJhZgq8kbAeuw5XAfJ/BM=,tag:ED9IusX3XZdS19BCcS67Ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
