# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secrets
    namespace: aiostreams
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:WrRGxm6HgTZstBZLoXyWdduZ/Hc8jaOc4pf0h/ZeVkTBMB9xcdT+Ir0JomQYW31KL10fre7EdS9Ifw+OJs9Itg==,iv:g4FCegeusdMN5whenYekiUd+4cMviN2II2qBGG96izU=,tag:ybsKiX5QDs043atSiVomBw==,type:str]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:p5DApccb6eaJLlKCDqkKtYUqkMoY4TE3x1VdHRIi8Bf/nCbh5A==,iv:BOkdtn9y62j/jjRDc858uicgLExuFnxiAF+N7uGk94I=,tag:w1LjS2YJWt6e/mE1oUIUXA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweFJENlJrQ1ljVVpObWNC
            aitFUkNRMXpPanBwQUcxQ3N1S3B5NHhTMVN3Ck9USjB1S1creE5pUWNlTUZ6eTQy
            ZXhxSjViVzhzZlZjWGwyazF5Ykh6ZDAKLS0tIGJ0M0NONEpSelhDUGZ6eXFxdERJ
            c1VsWlV1aklsZU44cWcycCtuNXhSWG8KJSHR4EqSZyYKmena3tkNQHc0pzwnnLME
            6xs/U41BfB0LXpIj+DeM+H/mHqN/gkJBgY38S2rYH3DyphtERkjPUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:23:57Z"
    mac: ENC[AES256_GCM,data:OwL2ayeR34YPk9c+ZNl2WGRdo49LrZ6M0rhDwKDmhMt2h9RQZX1dBOGDOz6PmnfySqtpC3Tzojfod2tbJu0X7bn/hCCRJ8Ad4wCCIGri8R4rd4xTh96cMQIwLMSkejPAm668/TOz4yfXwlkvvlAW3O4wdTCeNiSTOSSRQwZ7CVQ=,iv:rZrI5uP41YFo/MHcYIo5hQE3CVYSceMhizwzAdwY7fc=,tag:/3M7jgVT6zaWKGk+7kbfEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
