# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secrets
    namespace: aiostreams
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:WrRGxm6HgTZstBZLoXyWdduZ/Hc8jaOc4pf0h/ZeVkTBMB9xcdT+Ir0JomQYW31KL10fre7EdS9Ifw+OJs9Itg==,iv:g4FCegeusdMN5whenYekiUd+4cMviN2II2qBGG96izU=,tag:ybsKiX5QDs043atSiVomBw==,type:str]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:p5DApccb6eaJLlKCDqkKtYUqkMoY4TE3x1VdHRIi8Bf/nCbh5A==,iv:BOkdtn9y62j/jjRDc858uicgLExuFnxiAF+N7uGk94I=,tag:w1LjS2YJWt6e/mE1oUIUXA==,type:str]
    USENET_PROVIDERS: ENC[AES256_GCM,data:o17ex5Lnw9XgdBUctFp9Na+20SAL3E1T7Rd/6tS81c/nT2LgAM1UZykD4MPRgSmUOAVDDv5vkxvZTSp2l1oZfPq9Msx1q9DeblaR5xZXedzn5wUsrwHNCAAtnyM0r0YrVAc7FFskUVTJTUD2ESus9iymJh5bIlgxrxtkGD35PnN0QjlOnlLL/d4UmHycswlTsEfCmbhP3JBfemi4qCEc8uEXPkH0VvkRQP5SfPBU55oNw7hSZL9rjofEZWLX8+KYtETpR/GCAKr+zKZTtStKTmMvutIz8gWv7wLe1hLP4xmQsTP3QrQowG+5dza2Tjrxn7Cgse5+76p6bunRlu4cRyrA8OIhhM+ZpHiKhCe2KneOAEemw0Pj2DV3GqsXKiACxccl5gHGFWWNq8sS2t1AylGx2l/SyQKbYsaYu8uImw/9udOeqQ+WohPrVz1spaXZ3wGHb8uBA4lFWXyqQA2LkJMJf8E9HdGIhlx1ZfULHrgMdG7xLUek9AnC1WgaFH/YzuvhEmxQgNNfR+CExPulWLUO0BIU1Y+0L6HjzG3VcQy6vNlEYRh6MrSkKYceuebUUqUKKt9x0C9jw5wAn2ACNsJNsEmlXt4JGHQBgwgBH6nlWe6rIngulcY32XZaTZ1TZNkd0dMOjZmgPDOuMT0GOoqogZvY/KqCCpTasaDjC/I3y1//unPzSFtJAWxXebJ9utL8X6m+579l+CZpAzIsgdF4KdKjzlpyvvsp6z1UgTYF5U4hB7hBX+Sr5bLNM3tDcKFaLkJ7CUvy30vSSQAWf96AOmIQ2akRPDl9eEWoU5mG/Pcaw0nUJPfXIY0PhXQseI/1V+KcPlfenj44PxM=,iv:Znj+dQVD22N3OfkalYXXjTlfTfwdiCzhlqQqB7h665Q=,tag:lENQzRuHR34cbBkah9wy7Q==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweFJENlJrQ1ljVVpObWNC
            aitFUkNRMXpPanBwQUcxQ3N1S3B5NHhTMVN3Ck9USjB1S1creE5pUWNlTUZ6eTQy
            ZXhxSjViVzhzZlZjWGwyazF5Ykh6ZDAKLS0tIGJ0M0NONEpSelhDUGZ6eXFxdERJ
            c1VsWlV1aklsZU44cWcycCtuNXhSWG8KJSHR4EqSZyYKmena3tkNQHc0pzwnnLME
            6xs/U41BfB0LXpIj+DeM+H/mHqN/gkJBgY38S2rYH3DyphtERkjPUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-29T18:11:02Z"
    mac: ENC[AES256_GCM,data:bsFsi+3wJmhhVO7okTTLgdDuV39JqrmZ3cispYjN1tLwbFcLZSi07n0JlGgArg15hLRI+PIx1FVChEivrcFkXEv83G1+zwPzdcRx/oEs/VOT09EDdj812mPDeoQf7hnlPLejaqGmUC9NWa+0Ah9v4xFZTr10tM+/eIX9Vd+zHaA=,iv:q5+lhQhmEEVKIyRaeZ7jFbqGmVctSMDLPyaKMy+lx3w=,tag:2mmWycTcYqUxys3WzPtb0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
