---
apiVersion: v1
kind: Service
metadata:
  name: aiostreams
  namespace: aiostreams
spec:
  selector:
    app.kubernetes.io/name: aiostreams
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
