apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:JI93qqE9uljizWyydfxsymad1E5d1WzMXXotdrVTEsuprLnjD1PbFN7cQct7vNRia/OTIhI=,iv:SR0dyuoAoFJMOF54Pga48hXyzheVYGBV98ryqpaDQbQ=,tag:CWkkKwQ5H90SwdWIknL/VQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bjYwaWhKMjVXTEpGNExQ
            dTZXU0JySVNZd096SWZYdzY5VlE2TkcxeGh3CkpZYnZaZUlkT214TXkxdTUyWFMz
            dithT2FyMHI0RTlYUjloNUhNdTBsakUKLS0tIHYxWk1PTlJ3cytzWnlEanVVaWVF
            eXZ0dVRVNWptVmxVaVQzNFd2ZkppeUUKUbhvEbhLEV8/dK0vkIRWFYdEdqiJ/VFs
            bcRhGYk+ggtA1hSmjqyZXx1WsIfEQ56h/O9eShVwkfE8zAL4eyQbuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T07:31:53Z"
    mac: ENC[AES256_GCM,data:mbchK3qC4DzSV3wU5gdw4xK84NZGYuNAKPafH4oZLveQfUPcwvlQHbf0husP5Yo9zZ+uZBZ8/qLNoKUbfgrtLyAmAM6p+yekAIXu/7MhPcyLXmOpnQj+S7OIKi6VyBOpQZMC5+z9erSxrE1IHzCR2bko6PvLCUpU+f3cAYPMnpU=,iv:4HlO5n6s04znL2955y/30+709ArrS8RxmWaDei/82Bo=,tag:/EY0071XGbLAjCUMmCfNRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
