---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbdav-config
  namespace: nzbdav
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
