# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nzbdav-secrets
    namespace: nzbdav
type: Opaque
stringData:
    FRONTEND_BACKEND_API_KEY: ENC[AES256_GCM,data:19Wayutk8vQuooOOEnSfZCiPtT79fIL7axX3TgSR7hWAqtPGrOZrPIt7/iVud2Gt8HSLN3s2jNA+ckz7N0kkSw==,iv:cxW6nbhy3iuxnPl2frIAw5W97w68wxI1NFhT+caMAI4=,tag:K4BKoeJnqhL81jubYyQuLA==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:fJFL0+sx89IQBsUZ/Rc37+83VyZ5Y6UBUEpePcXaSmqyfx2k+YhhJwBK2b7y3lf+jNsauGxb3yugAnfZlThF56Pgo//mRxPF2YRfAWh+F/gPtHDwrvs2+Q4Qla5Kwr3GcvV01kSpgZ49UMn5SbSnnKU+5qcd/M+MqfnxLa7oyto=,iv:RL7q/Jz6Gy5CeTpOFRNRRv253D3yjCG9tbcu7Ti7Grw=,tag:fsUL9YI8JXjM5U2AqUAl1g==,type:str]
    WEBDAV_USER: ENC[AES256_GCM,data:G782HJgW72AELQ==,iv:U37e8jSN8eYSTyraWwDskDfNPk+4EhWXY5UnCcdVscA=,tag:CJWuocMkzW2hIQlUkGmxww==,type:str]
    WEBDAV_PASSWORD: ENC[AES256_GCM,data:dotRyae0FiBxWn5ORyxdwMtGH+WyBJSYWSRqOe6C18dOqbu9DPLJxAWmFCwbhrVI,iv:EXgdNL5Oqe2BgVGzOooBzAuEm/svjnLd26InhKYDzjo=,tag:YXrioo1Nhz3w9IQP9MBFrg==,type:str]
    NZBDAV_ADMIN_USER: ENC[AES256_GCM,data:wckKtWU=,iv:lh+LPWCRAcfG1T21724lTYzR5Y5TUYeV26IaK6+uDdE=,tag:eflSuUgeNuk7cksOUdBPTg==,type:str]
    NZBDAV_ADMIN_PASSWORD: ENC[AES256_GCM,data:DdxSevijpd41kWFxAG1AgnIwEpMw5bOm/YVLSWpS5rIWee0vHn+Jw5Z83tPzvljo,iv:Sy1y0EwjXenY2Hhg4v1cY08upE0AO/kDg64QkGPxxSM=,tag:PUwgF+m6oNuxeVx7TIHfxg==,type:str]
    NNTP_HOST: ENC[AES256_GCM,data:qd7XKvy3U0XzIxovKg==,iv:rWN1DqPxX6YBTZjJnB6b5aj2ac8NkWSmOQkvdpyDjO4=,tag:YE930vDQZIERw4m5VBGA1A==,type:str]
    NNTP_PORT: ENC[AES256_GCM,data:1s8c,iv:DBO2DTGl6yXAU2BTLy8IvJRNFe25t2v4e9Bq/hd0oXk=,tag:ynmdpTsc2umGlKvP94g3rQ==,type:str]
    NNTP_USE_SSL: ENC[AES256_GCM,data:vm9Gvg==,iv:kQAK5LURz+C27FhT5+4AxKME8bo0AaiGIVBZDdK6fXU=,tag:jbh3CgV09RDnXbDWnstn2Q==,type:str]
    NNTP_USER: ENC[AES256_GCM,data:0JdIS3v6w6XGMe+nSM5CwA==,iv:qXsVTgq5HiMgZv1zL6FEMtI17WrqMvBodawLGhBl3As=,tag:nnOudamsZKtjVL0Yr1kPng==,type:str]
    NNTP_PASS: ENC[AES256_GCM,data:JAZ6j0Hn+9vuJ64=,iv:xt+E/HfpBQEvYdGxzOW8OAVAcBEYJz1XOK0VVL4094M=,tag:2x6ClUh1TcmIs6xN0+Q/Rg==,type:str]
    NNTP_CONNECTIONS: ENC[AES256_GCM,data:8hU=,iv:RrO9hrbIChOojvzRE0d/Y2WUp9VAR9xE+yjTXOrI7aU=,tag:FAvf6CQS4cNd29XEkI7zJQ==,type:str]
    TORBOX_HOST: ENC[AES256_GCM,data:Byyf/RVNOIMllItFOD2i,iv:pounFPShDNVGs7kEPVF31YeKOeDEuF1kc0PuuIQKGO0=,tag:BS5ap1n2wQdZfzMCsxfnOg==,type:str]
    TORBOX_PORT: ENC[AES256_GCM,data:Z6Ap,iv:HhzsK74Ol6arYbP3pbyiutjE9HclluTc5n7oN4fJHm4=,tag:s5mba/blXjnFZtbshNnyiw==,type:str]
    TORBOX_USE_SSL: ENC[AES256_GCM,data:OpP5fQ==,iv:YaX5wKmor2fSguf3+9lsAYC8WqIdzeIG7T0VmE55Pwc=,tag:YNpgVJvHFSmfvMx/vLv6aw==,type:str]
    TORBOX_USER: ENC[AES256_GCM,data:tL4FR74yaidyPwP/tfBdQCgGi8ZMb6J5UZWK61YD41iXnySJ,iv:8KL2beo22Sy8fZEubN0JYJVGpE1IObuuoFxNnitaMRc=,tag:XNKs/qp8fmbbQOiPI5wvYA==,type:str]
    TORBOX_PASS: ENC[AES256_GCM,data:FQJxI36FnV1qB6FIlorjhzcOIohrAw==,iv:YlSNsLCIaPljb7Ss3iNsLuYb2sbJNDWxA1LoCPkOsBw=,tag:HtmnojW0nBb4IApb1ET6kQ==,type:str]
    TORBOX_CONNECTIONS: ENC[AES256_GCM,data:6g==,iv:UO1750cZ1VEL/Xw/ZKI1OHkPAjBV9otb9pWrus+OuSg=,tag:jt2CjnjjckT7i2EcUzN0TA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUUtla2ZNcStnblZGWFdQ
            aEtNYXdseXd6R1htdFBYaVJNNG1iaWRMUXlBCkVQaVd5Y2tsTzhJV3E3VXFxbWNu
            L041Qjk1eXJEbTNZc21vRFFLTmwwZU0KLS0tIE4xM3FIVXVhdWE5ekNZa1Ezelhi
            Y1Vjd0VzcExheFBGNGtmdWJXRjZqcVkK7vqukVWehBS8zbpNnuqN0AQTAwLF9Szf
            /Tokn7bVGUl2085ERp8g/f1Zj/yQB98ORVtzrl0BarwIubXgQ/yNFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T07:14:59Z"
    mac: ENC[AES256_GCM,data:F4rtiHnovTkrMMqB+Y138JeclPxDXSGrnPCUMUX7Kkgtc72ghJ0r6fqclLainS6YkKQ/dOM/Pn7FnP0hSAJWiM49x3sHc5lUO3wHjHYXDxwrxiJMVMTRygZ66yL4DibNsqpFVLETqufTbXw+BqK0R8/1mkGIzKNQwBVPtk6xar4=,iv:ObSsIBrURuM+ODiAryxdcRvVz5cFA22zOMzQaP6c+V4=,tag:WhWCkyU1pRJOzP8yppDAJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
