# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nzbdav-secrets
    namespace: nzbdav
type: Opaque
stringData:
    FRONTEND_BACKEND_API_KEY: ENC[AES256_GCM,data:yuwcwBsMytrwe5VSxuUMzJNWGAhkpphvgdgALcw0TkOo9WXrz6Ulrn5SifZ3nlstKg5MyQGbPgCHZXmjaJqJkQ==,iv:E+dFZx43hn7P41jPBVgpbfe+gXSKMSEq1HyXyYzZBQg=,tag:6eZq/MxbiUB69MGHstc4nQ==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:zUNyxl8xKTWksODIo0I46eLIeORV7EUqyta23YZL/f/HHgnmY/gtl0pPmjPbJbfsbc/OKLwzuvmpEtCGclkIdx+zI/AXA4EzYVlUGF578CqmN1udMDbbWTwFzbjrG7zYanqRoClQ0mZbRReAXiD9p77xGRH59DL6Fwrk7Z4UcVw=,iv:8SrdD9eTAEuFE1/pE0zQfSCOB/1VOvzvw32MRtLl+BU=,tag:nd3ry1n5I86A6Bk40QMFzQ==,type:str]
    WEBDAV_USER: ENC[AES256_GCM,data:Tjj+qsFl45TkFQ==,iv:bRmy+DiuEzCuu30u/J59CSi1u+0jQESJvVWZBUCUogE=,tag:aAJQvcFtnCwb5JHwViiNKA==,type:str]
    WEBDAV_PASSWORD: ENC[AES256_GCM,data:KIfOKJsPbjSqoiOT3ANEb+YHRaTPv0utXoF8cdDzl87ySXGQxBZSHRfAx556pxKX,iv:c8+i8YS0Vt61CkFnYqiDoDPC3s/Yf5QkGNSLMUMt8WU=,tag:6qlIMeSVov2ULnJD7t/43Q==,type:str]
    NZBDAV_ADMIN_USER: ENC[AES256_GCM,data:0bA0E08=,iv:Me/5rdaIL2mWPDjWVf0Znb/0NZhLtErzAjgJVSk2hGc=,tag:VhGU/+0s51w7GVLnVfK6Ag==,type:str]
    NZBDAV_ADMIN_PASSWORD: ENC[AES256_GCM,data:XMJat8wZjZIh2rKSRoM6nZgmX1n1j8M9hIO5mvPbvnPosmwqKw7orSyuFMjxxlDr,iv:ITpHHNb87KlRWo3Coz9F1TL9WCSr3CWeHprdpEWZKnw=,tag:fLAmnVYe4FdZMVPfjZWPsw==,type:str]
    NNTP_HOST: ENC[AES256_GCM,data:UXx9JcAcD9kizkGayJyPHWKw,iv:MQKKFQjLOuCvZishoh0YAsuv00oWvK709WTm8crLJBM=,tag:RDttL/T9UMrp1G0EuNpgZQ==,type:str]
    NNTP_PORT: ENC[AES256_GCM,data:SJoV,iv:oHjx37LWvXPgvbSaLW2he6lfts6KTpi5B2ADdzlGOq0=,tag:Bd0PkeoNidZ+GY9BtJ8BYQ==,type:str]
    NNTP_USE_SSL: ENC[AES256_GCM,data:bJAeSw==,iv:xvwTIfNxNRVFFL0R3BopHcJedgwhNIcgA1oqx/69Ftw=,tag:iWzAjbF9MJl3+ceikZLmhQ==,type:str]
    NNTP_USER: ENC[AES256_GCM,data:N9xRc1cyk45X4PciHOBPstytoyX6UIvg,iv:M3gI/XMTn0TZ2bRMLZlVuNag40Qaka6mdocZqBzAFdo=,tag:DM4Qp3i5dhM7OgZFKtz2DA==,type:str]
    NNTP_PASS: ENC[AES256_GCM,data:5nIYALjEH8I2,iv:y+JVZM2L7h/bwdVEHSC9gAEWrixQqgbZJMGTyQ1TA0M=,tag:e+Wv/cuq9wh5FEJVRItUsA==,type:str]
    NNTP_CONNECTIONS: ENC[AES256_GCM,data:3go=,iv:JFYQ5jSp1Q5J6yrA9neI5KH6DR6PiYL/D6JI4ZJEh4g=,tag:nR9V9e78umUhlEOEohDR7A==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOHdta1hKeENkR1ppRmh6
            djJxZnRHM09vYXVlaUczakJyVGVJTjVUV0VBCkJUNWUxRmRvVG1sMXU0VkVKU3I1
            RGxoZXpURWR4WkpDUGlxT0kyYlpIekUKLS0tIFlWZVJqWGJRVEpuSnRIYXdacUY0
            Sm5IT0w2d2l6eEF6SWo3bS9vbTZlT1UKbairvm8b8zow4Cm7jXFEJF4l1xS5a2mY
            LneQY4OHf+6E0pKZ96jskBmmPOcsF4UkH2RVw3jXerQy9Hfo+lMGCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T13:35:28Z"
    mac: ENC[AES256_GCM,data:WtptiKeNKDFfR2xiHNiPYl5bn80DG2TL96fygm8yjFuDikPuJywQHqKCRrUXIrR57PGIG1g2E1UovFb8TWDNgqOO3z8geKKgl1lVe/R1tkW40MqA4Cf4hX2kaIZFWI/b0VMCZ7BV5ZhEd1lgHqvO6O6aU7H6iegFQAm2sEDsEwk=,iv:yX118BZBbaQEOGRbHc2FwoOhrlNG29bvGyIqd3sC6NQ=,tag:clbnKfzb/8rt094EMS8h/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
