# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nzbdav-secrets
    namespace: nzbdav
type: Opaque
stringData:
    FRONTEND_BACKEND_API_KEY: ENC[AES256_GCM,data:luYx+cks6CVDCBE9eH+hi2FmX3yQFcWy+jDRR/0ii60SjNfLkinhwEx2eZwZ6ezvKTeagcBXj0K1VWVS53PBXg==,iv:lJSg2PERFW4pzN/BGJemzs1zENZY21FmLp8JxIIifFg=,tag:z/V+VuXPbA/TdhXOcSruhA==,type:str]
    SESSION_KEY: ENC[AES256_GCM,data:/EQc+pRsHz1h7+8Z/Yml7MsLHX+7b//d5Zr4Wn0K/43fMtqCMVh9c2b9Ikbs9HkMQtN3Ekuf6Lom18eVFvDXglbTfZP3rfWQ2qpdWtqEot+dkHeUSCiUujZdQTxwGe13TO6oRj/yCVrIM9JtjNQPhiJQ2Ap4Nis0kAtipBQ6esU=,iv:LVXe30d8eA17vX9jr4qD5O1ipF8YR5JcEQ7+uVZuC2c=,tag:X2jTmXdW1lLn9rTEzvOGAg==,type:str]
    WEBDAV_USER: ENC[AES256_GCM,data:ysDm0Xm/BCA66w==,iv:YRLl6p50mXP1tOB9RQETc98LijkzRTu4FbF10TSrfxs=,tag:YdMXNoOG7frE2c67X4IW8Q==,type:str]
    WEBDAV_PASSWORD: ENC[AES256_GCM,data:sYH4VzfNVNvD8uHiYJUYDgoH3/9lRNMYo7+xky+kAziFbRuaUMOcbAJe+vw38cWN,iv:f7zc3Y+k8WfDJ3dnvDSoFoYpnTOlUs7hdt7SxHoxaEU=,tag:cpOl8+H8u5Z196bN6chn9Q==,type:str]
    NZBDAV_ADMIN_USER: ENC[AES256_GCM,data:12D5NPw=,iv:dSIbKPpb/l/mB4dMKBtWO23m0H0luk2F7ffSxAU3sgQ=,tag:sOiGs4iGAt9IghJXFDZOug==,type:str]
    NZBDAV_ADMIN_PASSWORD: ENC[AES256_GCM,data:usVqzi2DbDSckpyE9dHnSkp3MeQSSjNT9jN6i46FrD7wBIOGIfWyDOzWo9kWrxTU,iv:3ZABaggJAVTRAyxuBiXSDiba1cNPfqjhOwPNEwgypec=,tag:UsRAAC6AwgBoDXphJinaLg==,type:str]
    NNTP_HOST: ENC[AES256_GCM,data:UfcXglAICkJYYpIHUurLgNtC,iv:aYlFO0oPZwV+fBzgJpRJvpd5PTGliPRQTlMSjVTkbWU=,tag:RaMpYub1Gh9RQ4wDm4FBXA==,type:str]
    NNTP_PORT: ENC[AES256_GCM,data:CRNx,iv:1KMeKTbTSKdnGN8CVTg0sl0c6riV2H44Cok7YVtTF2w=,tag:5UOOv4Gt5LW0CYYKBDbkDQ==,type:str]
    NNTP_USE_SSL: ENC[AES256_GCM,data:JDIsrQ==,iv:sCC3zNokC7YGFKO0wRejvcrRUAW5euVJ4ICZdsgpkT8=,tag:ujdKY9146sQZV+C4yd0Kxw==,type:str]
    NNTP_USER: ENC[AES256_GCM,data:GSivCtW2KbybjfTSFLbYYuEZEkDOiTuM,iv:njzPoK2+N5qASvXT0H4r/FN7uPSDkhhuYtOL+22rtm4=,tag:X+PMiMYCgbl8ZnINPfoxmw==,type:str]
    NNTP_PASS: ENC[AES256_GCM,data:uhi7pI2q16X5,iv:by/sXaLXUOpHMgfefLVOx/8oEedUfCJDqMvlTA+qiq4=,tag:MWkBY0UOBqNnaS7BGwpd/Q==,type:str]
    NNTP_CONNECTIONS: ENC[AES256_GCM,data:ILY=,iv:iMcoPum88iYU/sEThk+5j+MqVE556/tIkJpHTTUhWDU=,tag:SmhOnrtBDQ73XFR2LeTQRg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRkUxYzRJaFowYlh2azF6
            YTk2ZEYyRzRpMDFyeXhuQURXaEp6SEtjdlh3CnhLWklOaEh5dlRicDBWT3JKVVZt
            ekVHMUxpeDdxMFRORmIwb3U4ZFVTNmMKLS0tIDE5YTRkSXFHZC9jN0JLRXo3Y1pJ
            Z0lJdWpvNml5dW9QRE1BYlhrSmJiQzgK5mLWX5ZIus2v/R7WccPJGZxvBr7GnQAV
            9upnCK1MTBBs0imAC2dn2TtF+kAds52fmE7ScdIJfDSbAgXaDEtpJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T14:23:47Z"
    mac: ENC[AES256_GCM,data:vjxm5/zGixKqlHAwuea6fVt3euyK7J7Nz4lSkkOEIGMWQZHgnZMCB7WZWkyXx9+FZsE227gr1JJ8PI53PiftlxBvWqytpR3tWlaRK85pIDOypqWHLX1JcoolU7bP3ICKTEs0I7Ubh4V2vGYpwJn96umn1dQNGX0AyOe40Rwmkuk=,iv:6N7J92WR4AxP+Qi/XtDmwmDX0odhGl4nsfMHA0LW4ro=,tag:uOvGoZIvKil7kT0+JKEVqw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
