---
apiVersion: v1
kind: Service
metadata:
  name: nzbdav
  namespace: nzbdav
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: nzbdav-hetzner
spec:
  selector:
    app.kubernetes.io/name: nzbdav
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
