---
apiVersion: v1
kind: Service
metadata:
  name: nzbdav
  namespace: nzbdav
spec:
  selector:
    app.kubernetes.io/name: nzbdav
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
