apiVersion: v1
kind: Secret
metadata:
    name: hermes-friend-secrets
    namespace: hermes-friend
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:e9lM3j66Aw6rHJ7GtjTW/ryN74dir+iLEn/iNA4jb72i0yX9NPUqK4RpREzpnO/gwOsiR4gS5x64cwDSSnKbfnsmdYzgFc3y,iv:1erwTQWczfk2QjL4osfSC4JbUZHtAQSR9ldxpxq94uk=,tag:loL674ownLfcFzb5U9eduQ==,type:str]
    DISCORD_ALLOWED_USERS: ENC[AES256_GCM,data:ASuJgpMWhWXpOHHs4xhUzXUn,iv:kdA+mnhEezd9N0WObIapITOI4tPc5uRxX2CcPMfJAn0=,tag:pQW2DWO35IpMmZV5hdp7ZA==,type:str]
    HERMES_GATEWAY_TOKEN: ENC[AES256_GCM,data:LPTGq6wRiv9WRBxeUtU16T06DY+0siFmxtBxcM6D6tgoTWi/4wAHnck/p/JDSMe0IAJ79lE7Pvy+AeUsFS7rIg==,iv:H+1VAKlKxnKo09fvagNsR3Px5iTI8okOiOCpmhQZheY=,tag:KkBg9i3ht/tH4XjRsIsbxw==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RnhGUjl5TDExSVB0cVB4
            QTFvVE5vb21QYVBKVjJSOFFnUlh0VjdKVlZFClVHN1FBODc0ZHBBNURXYStXT0E0
            RHlnaEJJVUtpMU13R3ZDSTlQTW8ycGcKLS0tIE5Fb0FxWU1udmNteVRpeVFMcnAy
            dGxLaUgrYVpZKy8veHdDY3ZwVHpISVEKdd+43qZ7L8P1T8q5gLWsO3nI7cJsNEe7
            8NdiFInU+O7Q6gEUQqBEwdP6MotQzBcyQNCUDtZuNvecUC7zf1R83g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T18:50:27Z"
    mac: ENC[AES256_GCM,data:HLf8LLA5V8Gx58JMD8t6pigxtu8x8drd1V3QSLQUr8coKtd/yY16QZOA/H73bHVLmSdCp7lm4riIWZHCfyqFESh2JkiXWpc5y4d/kLSjvjhYEOqjsO2xz8I2lLv1vsl1rw7zGVgmz9k05epjXe/+ggKiGihUvrbRnSOeg6x3TsA=,iv:WI/5efgGJTibjeJISCHSeenonAe54YWIN75Hd7i3gpQ=,tag:QsNJStRgSDQKx2ig8xnAKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
