# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: termix
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:elN7vEU0o6wBNse0VVZFhsK29EAl5TCuHuKU/7O0X0pSVXNRn28lBhY5qX9HZkamv0IMl8FmXlq2zKiDeQPtidGpXhTcIBqnzQgHIUnnfvtNLjXYnt+7MpoRAgtDUc6H8X5s,iv:rAx+/Xqw3M9tW+EM+HhNPND7uFuJSqp67Qgc7uWH9PE=,tag:k+rd3rAXoDyRkb9HCTxxdg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckViYlFVa2UydGEwMzJi
            ODJpbGF0T0NNNi9qOXFVYnFvT0ZueVJrY3lzCmtidENhQzgrWkNYdTNvbjkwWE9D
            blk5ek5vcWVkZVRrampISDdaeUsxalUKLS0tIDJJNWVTdVk4cTFwd0tOUjBmZ2Qw
            SjR0aWl2M1ZwQjc2V2UzZjJHUm1BM3cKMVkSAn1370VN3ImEXuSNGWeYXF9SbFNm
            1IB8MBysL1vcoz0AWdEXYnjCommjm/C+pJVfOT80m4RKPMdDRu9G9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T18:02:12Z"
    mac: ENC[AES256_GCM,data:wyLV60GM7u7OGesmfbAuWwTptXMr0rXr2gFy0QjxuSXw0iQ18fdKBs7p1xMWmiD09U/fHvxI5EgKTsCC9353BWODZRRn4r4qm1V2A4IA3hiOL1CNxn0Hr+OcfCkPThFKYc16KNdnNe/Jitfh3X0fmIkx4hkt7vLi2RWz1L8Lh1k=,iv:eBlcEZWudKNKl3Lktp4rjqOx5upJx/se4NHXq+AsjRw=,tag:aMpd6hzb1TpPWMFXAan0Hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
