# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: termixkit-secrets
    namespace: termix
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:NFDkAPfpq0LH,iv:fo7nU5tTJyUxb3Ws/UEGDNUGK6NwjbjYupnRjyXj5XA=,tag:YoFThgl8lBu3o42rmaz01g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:HDBVboYyqQ/10Lqz2a2Rff1FEfWJSaNGL/HnXGgq5hPlT/QoEUe2t422QvJfTa35,iv:d16uShFWosXWunLOflVO7fW/NBeT2ABmzuGiLM6I88A=,tag:bLKGoRIPJ+KPZjW9+Cqm3A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:sMK2xk6dggo0,iv:Zp5LhnEO+7XiaVGeABnI7HSpaPUQAw2iOhZbDzNGuaI=,tag:MgfD1dh2X/sBezKuDE+52g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:B2mXcMMZk5FujAKSK1D/PScZpBMYo9y9PsxxzWcXoDvk8XMNnfIEceRAv0AF7Wh+oIxRtYX1SGTj/aDDc1eetDKwKnAhtqUTtgSk/CgR2dHdGJ9wNdvMpnCrZ4WvgOEUMl81UA==,iv:xL7TkSiAO0p4kb/W380yEKvCQ99sctNwSrPKycMDSWw=,tag:AOrNk1Tl1Oj5xMOFpN2eIQ==,type:str]
    APP_SECRET: ENC[AES256_GCM,data:rpYp0jVAgkc1wmqAfkjzFobIXcwhdtIPaNTg/hF07RgW8ymDYZP/hvSYjeMSiELHdw5yue57quaaWfX9LziBfA==,iv:Gb2tvg8ml/WGmoFEQ83smSOSZJwNTBdNyXvPBNfWaSU=,tag:fMiTO9vZ9GvvO46QBrOaKw==,type:str]
    CREDENTIAL_MASTER_KEY: ENC[AES256_GCM,data:0eTc7eW5zYxjAx9ePIUW/xt3ErNvGgKu/ozWgIyP7dhC516QaKUflEp+vvLG93VU7oOg5mDdhTkTSfeNoUYoWw==,iv:6YBCsLh7l4G3dSfkqVSk2gJa1PJBSxT+BNwz2x7DKrA=,tag:n/TDLOgWNcw37PFshggCNQ==,type:str]
    GATEWAY_PROVISIONER_KEY: ENC[AES256_GCM,data:4oTBXiaxthX+mEGF5VgIajfZqDvD18JASirm0roRwA6S7oY+aeCYaDRAmzmjmN7a,iv:HRUXFfdBX8lk61GBWCL8IhHl0Hd6nDsn9nKv6DegZgM=,tag:DLIafpHMgrx+apQ9E3h38g==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFRtR0tzb200emc3V0VP
            bUNORVZRbnJOMFI4OXFvK3NaR2VqSDRhNFVBCjQrRlovV3NUNG1hWm9COWxTTWQ4
            ZjFrKytvVDVvdjlsQy84WEQ4Q3A4VG8KLS0tIEVkbHBnbmwxUXkxSUlNWjloOUNh
            S2JYNm9TV2ZLdDlINUJaN3dHb2YxNGsKf/TVtzaxoVekBMzGrSmiuyfFyX+YLs9d
            K3Dz8TK0JrreYfp9UAmmWnB6pby89QfjsrF9qH+/PFhL2Rxmiwuihw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T18:01:58Z"
    mac: ENC[AES256_GCM,data:mg/TyyNvCBPVJfY8EU8JkoCvtSntJiWyS+QjeFnd3GZT2rEDs8jl5Dd+czGZKqGKRTT3jBP2bLKUhGQbjJURZHwZ+JwS0j4I6WkHMfHMpO5rc31WkiEys4D92WAHCGNjnjJ77iPsa2KwlOltqGPM4Cbq3H/OFltKb1JuL+EfeJQ=,iv:mtfc34QiQYjlgQ9K7BrUivuEULlRfsXkhRQ7MfeOm98=,tag:KEs5NxDlU/MmqGQsg5gM0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
