# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:YIYXrZgKh9iuAnvhS6yTndvWB3qNkLcmDWYJIVNhHf8PrYY0dZvoEWwfuofUz1yFq6WzHw==,iv:73DCNqRdPh3/GXBNPT3T8F3WQaERyyEVdrrKrAQLBwY=,tag:mFHFj7obeM6o1vynKHfIyg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:7wT1oGy+s6mRZ3XXHanppKBNPm4MmD+/K4QVDqoa5seZ0IzuDkOJkI9pOx51i5/rFf+vD/+c2R8HXmKbO8xBJw==,iv:Zm2dPe8HL3fil6M2EukpO0dCzytygJnk/cI4QXk7H9U=,tag:DX1yPGvecsKgHdxk/ekjdA==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:XNzW70Nwol1FlQ+bO7XNsJo314hAfbpVn1NFc2g0+/XXXZ+krb2I0GgCgLZxTAB3YK5DRmDmjiJOHllnaC3rFy0Wkr8G9wzB,iv:IqY2mze75cF3qTPvJ4p2ZG1RFcd9Pn7BL1jpCtEzgJY=,tag:D+W1EcHpnO4q/3iMkV/dUA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:VoapNxy3IyIicoeTjjvugzypttfS81hEHJheh4emC1nXYxE=,iv:xQeIwbPz5Tk+Ri0pZ/kpQdJekg2VclOx6KnT1o2wuMM=,tag:UdpYhMT2HnW+Iace+gHNqw==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndlNHMTN1NXA2TmwwNkRr
            cHQybXFVdmVIZ0hIYThoYmM1NVE2alBqU0NvCm5YNDBGT2dMM3dGM1dYZEhUdVdZ
            aGg5dEJFNUp6NFg2NVllVnFQd0dxMUkKLS0tIGZvMVRkemk0VmVXd0ZKYWtNbExT
            RWMzcmpjYXBCQTZ3OWt2ZjVkc0M2S0EKaK6ImIOv+VnqMy8j9qB4yVtOjvH5+DJZ
            Oe3rlrY9i7JTnyb9DsfyRKX/5ZNhVf0MVM4+6uWUrI8N8rIl62okWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:39:58Z"
    mac: ENC[AES256_GCM,data:KTGOaNcvWC9kqcCXgScAwFZYtXR5UiCf0IBeMMmy0FbAmqp1SSrIfsEdG8939W97PnJla7MuYWDEsajI8Vk/ltHmSjB02bjDTkI34XDKp9PIMjVu1dXK8bEOVEhnKMp2tjB1YWQeuBKtTc/K4m2MwOu9ehJaUmVMMTf2B4d0WM4=,iv:mMgfkA61EwOGjsaiCfOuWT6KtnFE4wELJFiPftbWseo=,tag:Y85kZWS2DzCGTRYBX0LeZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
