apiVersion: v1
kind: Secret
metadata:
    name: copyparty-credentials
    namespace: copyparty
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:hnm/4EHTMm0CCQ==,iv:mlHkhOUTWLMQ8ABmzW0R/KR0hOtzBptk/FaAZ3edaks=,tag:iK2+H+mYwalEvE9+LJ0OvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbVZ5RnQyaCsxWVJ3SkNt
            L2xMTUx6WWdmb3p6OFpHcUlKaVF3ditjNFhrCnBRS2lXcW5UZFo1NXhKbFVrUWdn
            T2RyMHM1UEtlSldGOG1NbzhCOFF1WVkKLS0tIHdDbktKeEFDck1OVlEySGlDSHoz
            UXl5T3YvVlhLaE5PZm5oVCtINUVMcEkKX3siUbvsMbc/32LmQxJHVSgnbp6NLv6a
            wKFq44KR5H79LCeCcjhmdEq7NX4MnnnCTJxIf77dN4wqD1TgGqslSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T09:50:06Z"
    mac: ENC[AES256_GCM,data:XO2Jc1G8nIea8cqBGPKHsV12Jxyo9fOB0DnXyDeVR9aS8ffNr7edhOU/uyv/OPYie4IgW3+Xa99O926vvFsR9rBHexiHojcSnm04EAAVNykrIYax4w7FU2JbOWRbtFn2QUlqvHivx8Nuk9VCObEFmoW27RbRZ0Bx6ZnUVFxZdZE=,iv:qaf1wtCAPo6V5prqg6OccrOtfjhHzRbleI1YtldL5NQ=,tag:1W9fGcXarUd6A942iL7AUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
