# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:x8dEkB2hGgNzq1ZCrkHMAy+KcyoHpyZaTaoeIGEIM/NOjHatf2dZGEBWRua/jtMHyDCekAgl66mADxJzhytQ/YbZutZWPPNMlX3IAL7na6iwbqBP4GgeofdaktflGWqOM77XiXGDmFsf424u6I9G1iUMD529/qt2k3VWzSTn5Aiq2bVVXOQLP11QX1lAk40aN3mov9oKYp2KeIyoMVUS3HIuFIEOYH8XyTQqpvjplm/HKVvWg0qtt4xPi93/utgX2kn4wt6w56FyeZx7+OWj/bEf30+G1GlfKDC4UKbSmJMe7d53Qx05NxEc3MI=,iv:/UfMwaa98vJZIlRxDwdlvSOxTj4aOCrOuAHE04xc1Qo=,tag:wneiR8YKpd8CqoOuq6w8vg==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: tunetap-app
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV1ZsN0tOOXYxOWRXemN3
            K0hLMXF0SHM5b3lyN1p0L01CZUdONWFzcW5rCmR2UEVPZkdNSHYvaHpDa2pPalk4
            d0hxdXhUYVV2NHBDL2NWTlpXcWhKMncKLS0tIHUvZ1JRYnpBRlJWK2NGY3RUczVj
            d3hkQjl0R2drdUdGUy83bVF4SEExNE0Kl/nWdScT80JESiIUC01Kz3rqAOEIqoR+
            f0oZI7Zu7KchHxa1nDz6k8SaCl3dOLAw4OzRJX+0lSRz093odreVcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:21:42Z"
    mac: ENC[AES256_GCM,data:PoUkmvVUIjg8tFdf6SN4IM1oRcGTvGUXlXHKn4Onk/M7qR3bgSnnmMRk50JJSkyAd9XNDDuXx2VfV3snyFLzMsQSJ9CGuUAbilzS4ba7DLhSwaANMqTJVMs2RX+JISFoqGx0PdOOFAP+LHQFxGpgesVaSyaXb1+mfhvKk7foVOA=,iv:SSeoxsL51DdlUPPB6YTevHxPr0Bb6Fpw2mlP2Tdk3gQ=,tag:i94ZUguPO/QmM8uqQb0wAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
