---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tunetap-data
  namespace: tunetap-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
