---
apiVersion: v1
kind: Service
metadata:
  name: tunetap-app
  namespace: tunetap-app
spec:
  selector:
    app.kubernetes.io/name: tunetap-app
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
