apiVersion: v1
kind: Secret
metadata:
    name: aviary-env
    namespace: aviary
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:QLi0B4Kyme7gbdVDxGvOBrkiiqUZ2a1vuJkyrcI62g==,iv:mWInHb8vIOFiniEW26dZeiSmNv1witeHjEo2Kd71AmM=,tag:Hz+pRQAeNmp0sqqQiE07QA==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:LCslzAHTGLLLRrAZXC6SHrvVU0Q895XMgROyGpJuLViEmmE2E1icus6it3baO9/Q1qe5BFM99gEnb308vyNBmZPRFvrASTSu07Tf0ccKEqD05w3lYfhIIkCHzzw/Vqfs/XUmGE6Ku+RmYVIVFOp4R0vZxnjJxr/6SfGQUgiTgNll54bRcmins3nWcIlvwa+2nDYGMFLNOB251eZp+Nct3WsAb454T0SbdHGkmdoithS70CfpWeCH,iv:IzbVbCV0v9+c+GsIebnNUKjrjf+0fzlFTNRue+zyfFk=,tag:HhsRGyUVUsugsOQ3yMM0pQ==,type:str]
    HA_CAMERA_ENTITY: ENC[AES256_GCM,data:j+B4euwDwLAB4p8vq1Wdq3G2SSZcl3R3kMRt,iv:o/T/4kRtdnFTXJT0QN8tDYspI6pGATATDiWhiD4dOd8=,tag:mHCdFyuUP/M8s7kbTdhf8A==,type:str]
    HA_MOTION_ENTITY: ENC[AES256_GCM,data:SfzSq8+6g3odB3GFLddosGgAYzZsyv5toXXX9W45HikQU5KYYgh2,iv:g/Nx6e42V1TZXu0ggqtYB/HQGQxOEx687MYA3k2VPZU=,tag:QEIXJho4PH7YjF1Hv7NReg==,type:str]
    HA_PLUG_ENTITY: ENC[AES256_GCM,data:XypYGkyCkYU=,iv:xmT4NiPFF4pRHjid1kxOQMn08HoiFHsS3Qy563v2Wi8=,tag:DToAftr4Q2cNAvAfy1+09g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:/vjI3F3oMTgJ+saZ6yX4YMhLIWC9bBv6nzIfcVEu+vTG0LSXeBtSDyFYcioO9XAWir3i2FzZv1ntGsFLsLDExeg6aT5EKfG34g==,iv:Ygwkf5YW8mtdnJrojXu7NppI5PWKUpTuRMT7B4p4CKk=,tag:hF+kYSwsy/VNTnHwc1J+6w==,type:str]
    HERMES_WEBHOOK_URL: ENC[AES256_GCM,data:XY6t6ZhNDbyfVinpVWEo6YtXzf4HFgTU//F6YGKbzywKi2Pl4uROhN1OuA==,iv:NBbt+J35nDscy69PnsoBBFHZ8E1v+37uftgdgIXZTbk=,tag:oenZLTb3+YPOFf8AWCj0Og==,type:str]
    HERMES_WEBHOOK_SECRET: ENC[AES256_GCM,data:tIL9GF6gdAA+HAFZ7+XMddQV8bFi9F8dhnXb/u5g9RHZQHmmCm3uJZjPkg==,iv:OXw9EfACpaGoYH0uRrQTYbQEmGY3yPT6Adffx57710I=,tag:hzMiqVDzM9RNLEBjokZInw==,type:str]
    RFDETR_URL: ENC[AES256_GCM,data:GV/AntLwFr0xe0hXKdEmspPt2xxUJm2b,iv:Ckt/QFUXlVx5GTBnHGmVDhHbyHQfyplR2+CmvBm4mUk=,tag:9cxqPhCpXlwggrI1ANvcrQ==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:ltZ+0rTp9KJj9fS0,iv:kstTvWOJS17ykUEnWeIK2pcnMJta4AfMmlnLFBP4Ivs=,tag:9dS47ahJzAUOgfEjZw4nXA==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:o6KTmw==,iv:iBPmTpeax/xMTlx3ZGQDTpSd0ki8aRcORm2uXfi7p/w=,tag:RxRJPvxwQtAHbtlngpvVwg==,type:str]
    N8N_API_KEY: ENC[AES256_GCM,data:AUoQPVE4UriQ+3z0hBaqCRTeLx9PCTjCsXMXAXiPw7M/qWD87ckjZAFbLtJgQRaPYbfHjrKk5/Cl4wto1lTSOZ+zcTX1zflUYuu+sE++pg8sq2yXvUXUDzdco6No9OitF3GIJMefSgvDPtbRibVTAnDK0TJSMcDxX+UMvsD2407wwfhwlRonuu/JRfgKjNp6Bw+MHO3MTpMqKdrFKUnKFNAby5ZkxrHl1h3L8XQ849RmiWsf1u+q5uT7Esc4qDHZpUYxVBuS6Wg6dLeejHnhV1mS6suADRiGPlLUKlAZOynnuxSUDTWRPBqp8VtmLAoXObs1dac38TOKYnUwAIVV4dP0zIzMgVQZqYaBlHXV0lIkbPrZCrKx8mwgolT3E4SzSw==,iv:KKQhqtXlDERKAikx1/PNYDe6BigGCQeu9EjrMH04Cwg=,tag:/8vuAiM++AyE0Nqkm4limg==,type:str]
    WEEK_LINK_SECRET: ENC[AES256_GCM,data:jjMIpIYi/I/my9L7aEpqToz3OWzWsPk/YSCiaX96AgeeB6wDBQ1qHeZMgsHepS4qaQTUCGCB0eF4g4WPC0becA==,iv:HjtY5p8oXRmFkw0SPOEq4lfym0YpWUU2EepvrniSM7A=,tag:Bx962o1OdeS+gFCHJIj99g==,type:str]
    GALLERY_PUBLIC_URL: ENC[AES256_GCM,data:Y3BvR0OREQ5D7ZVyrp2LhJzHZZX/3mE83U9avQkcXU6p,iv:25g4K6+YNGTzRh/LuT7RlNfGKszU32hA9jj47WUMPbM=,tag:Ul+qrKxK53ofbT5BpdndNg==,type:str]
    CLIPROXY_API_KEY: ENC[AES256_GCM,data:ebewyWU1WL3l3ZESM3MsZrc8rewmb4yDR4pkiNttqiV+hMc0E6mamFpuaUEajTg=,iv:MZO48bMs81eXyXU3JHCCHMYMYtw8Plhrct5QXZfl6fY=,tag:84xCt2Ku9/qgAYApEplASg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:10JpMaov/rRfYQ==,iv:Z/LJ7oJ84mPhoDlsjWQ1P4ov9DCOhMooPs9EqbrlGhM=,tag:TxaUy8r+g7fGz+lFr712Ug==,type:str]
    HOST: ENC[AES256_GCM,data:JzNigSSwFw==,iv:Y6kK2lmQwlkaLoAH1vtUOKVeUtksbS0Df3RPp0vk2eE=,tag:jhzBWhRs0Y45aIyfmI8leQ==,type:str]
    PORT: ENC[AES256_GCM,data:dYvybg==,iv:c+1G2tWtKM1ejUimnRn4fHZa2yc6tngHaliOAd6ll6s=,tag:hnEPKKKN8x6IWqQzu0VNKg==,type:str]
    PUBLIC_HOSTS: ENC[AES256_GCM,data:E+YtqAXyu8tsEy1LQMplqVCMaOEX5twH7A==,iv:qxUNyij/qydjf5AqrdWPrMiwU/A2QsbqoK23M52jb10=,tag:573h93HAQj17gM9VnRREMg==,type:str]
    YOLO_API: ENC[AES256_GCM,data:xZnxghGEqjPKRqBnIKxklHC1qqqkD+0w,iv:yMRNlvo4LvS/MQL00yie4bto4NrerIsKDA+GocxqtQo=,tag:YbHzN9sFGXOyqxzvVMRfXA==,type:str]
    RCLONE_URL: ENC[AES256_GCM,data:EdzeQWDzskdhDMnBjb+sb6aWi8DYCHgR,iv:rtKz87nIcMM3WNiMYOlFOcyiq7cubuCzpqGl2qAw314=,tag:4Q2d8kAFOvPpFpZn3+iLDg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TjM4SUhudnpMOWl5UGJn
            U0pRdVZQVGthbkVBWUoveDRGc08wQnFrSlhvCm9OSGVEWFBqMUdnMjVCN0R5M3hP
            SmtyOE9DellTWkoyemZjUnVKOXoxMUEKLS0tIEtnNXdxRXFQMzlNU2VmRnJCQXJ4
            b1NNS2s3NURVeUowcUVFWW1jdnpHVU0KQYWLIAWsPxJVSo3Tsda7YndbjMeE2p5L
            qnQqEsKh1KVyvyJhoVMEoMBeFTXOUdsJj/I+umr+XRj6YLOrPPkZ6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T13:33:38Z"
    mac: ENC[AES256_GCM,data:GfTFokeqALUy7DZXrvtDz9TZfz9qH7y0s7BKsX+1vh3E1SitYjICceTsAiZ4e6ZeoBtfjXzrWSRuOds78OAwpQaipNAqw0+EA7WfLJ5I1mELj1Wd1Dz3nfd84Ft/i+hLAR165aHnMswXjTsvALZy/dkP3TZLewFcUX7MljUYnB0=,iv:NVhSwcKSMHfTSdaRUWHNAYbslL6fSbZr7MwHbELf/Gk=,tag:WkzbC9InodwF/cyHy4Hfgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
