apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:PX0ebt7TwmsdnQOC+eV8ZvncL2Tre1OKGNRmyuBnCQrKCA5sCEHTQA==,iv:uovC2g01gxrksaJ+oE8qO07DeuTr3dC62GwTTvCNYx8=,tag:ds9Rhi3rNu8+ZfnzwWaabg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFam1GbVZUcXp1aWhUeitT
            alJ1Ly9EaU1lTnZ0Z0Q3Tk05cTZyV1hKRG1VCkdMS0xld2NVMEFuTC9tMCtuZXU2
            YlFDWkwyMXowOHJZc05raG9tenpnczAKLS0tIHhCbS9QMGMrR0hsQlFpYm1KUWVN
            UStwZ2NXa1hsNkxlcFBVS2loc2E5eXMK3mMR1dWlsqUesCwN4wGEyzqYzE0g/+zW
            RjCtcOTUvShmdRm4tdov1kdnrAONw0fKJy3C6zcurFNu/K9ZtZydMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T08:23:51Z"
    mac: ENC[AES256_GCM,data:6ZbYTVVXCVzQPBnnRzx5QclqR7pAdFkBxZbDY7EBZoirvUPZqSxNV5Y6uvTj7zD+D62fJwosHnNHQGwx2RVvXMLo8jW8BCvzBYJ1UBsE6arBdH57O5Lu2t8aNLpeM+KFPvTlcMbehwJYupLH2JW1e///FbxcwuUacYy+1U9Z7y0=,iv:iccSbv+HWhHHW4NfKHg1oJakZVgPqj8ozm34Xk446Rk=,tag:/VQZulaRA/rQUdPJnxqmHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
