apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:mXblCdWN7QPUvLdWv/ATvIBddzTVWE+dmG42NNfOA1+mcMO/GY1Zc0XbjZsohWGGFibST6dWZ0IifyTE47lK3YUy6hdBJ027/uWmMCfKT7eHVeuOMf8EDzOG3QRj5RDsaQA7UxaaP/l8oYGEv78YkG23uZs4nhcjomx23lWSxjIgqguX6bQI4uf3SAxtC+cg/tOW/PffVekhfW7BdwMqWS8bEwcAFbFDYtlCs8aSfBPn2qFZ5RUGqA==,iv:mRSPA8EySmYttct5XCgCOxU2FiLVNNkJWfNkSzg+MV4=,tag:0Y8qFJP6+MCG9pErEpMudA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFam1GbVZUcXp1aWhUeitT
            alJ1Ly9EaU1lTnZ0Z0Q3Tk05cTZyV1hKRG1VCkdMS0xld2NVMEFuTC9tMCtuZXU2
            YlFDWkwyMXowOHJZc05raG9tenpnczAKLS0tIHhCbS9QMGMrR0hsQlFpYm1KUWVN
            UStwZ2NXa1hsNkxlcFBVS2loc2E5eXMK3mMR1dWlsqUesCwN4wGEyzqYzE0g/+zW
            RjCtcOTUvShmdRm4tdov1kdnrAONw0fKJy3C6zcurFNu/K9ZtZydMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T08:34:57Z"
    mac: ENC[AES256_GCM,data:TO+37OMPfSkRNVkSwoUtAID3A/zmorSbTugCzB5wY5MatapiVWxJQpLkl6TunF/Q620epUxfEwWMvm+bG16WVdRqZjAtCFDqqgCAcC1IC2moSlQfwpEkEyrPNctl3Eqts92Kc3vHstnTVaYkdNgPcZWyYB2yJvkNuZ8FQ6ni224=,iv:O3mlHaiwkEqRius9oiTf8S+CrcXJNEw8CMBPfNRz7ns=,tag:6ULICR5hxLCnet9Bh0UQVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
