apiVersion: ENC[AES256_GCM,data:uDQ=,iv:f/IRheuJGfZRbNaoDbXQIuOn96nHJgU6I/EUt5/VeVQ=,tag:PFNdqnxGr//Rsv6QV/4Yxg==,type:str]
kind: ENC[AES256_GCM,data:xi5xXAmb,iv:Jaa2/UDoDxkl0HK8bzHw7dyIYhTt27Mf8LTvn734aic=,tag:KZu6lZZK+L/K2rpOr2cCBQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tAZNFILuG7iVaN686X/gtf+iqNHrmWo=,iv:51RqC8YfyFS/od+a9dKbyDAlzFmuWx9rnvqTEoLfGvs=,tag:/NK7jX7/wlXj6rdXKy23jQ==,type:str]
    namespace: ENC[AES256_GCM,data:Vnoymhd7gMVe0dc=,iv:LxcnN2x6tBbZQ9YXGGVlNPEorgMKE7zK+psU+B6waA0=,tag:jJzuXWH11aeUfai2xrlGug==,type:str]
type: ENC[AES256_GCM,data:HP92mfCl,iv:02fCmBNt3DDCrGpthL9aWpUjxgH5rQSHvuIiYQ/UEUc=,tag:STbFaSNCLbI5jgdWFxsJTQ==,type:str]
stringData:
    token: ENC[AES256_GCM,data:TYeqvBe6olOK1fipGdlHormUfaRusrCJGzJtXA==,iv:yeqiAPW9qaTQgXU4PPlNg+VWgUdQSSbUooUIz6a7IUY=,tag:95hJKuD58V/7kbJ7FxLmeQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUlpTc1BBWmdPOGZwMTFP
            aWxpUWJwd3hHcDNLNWlOWDlJTjdCTlZIa2djClVnMG9Zb2J5aEV4Wjc2dEFrR05N
            eFIxaDRIbXlJYXI4aU5KOFYveU9ReXMKLS0tIFUrdi9QMm1id1BvRCt3S3Y0VFc3
            QmE3aWxudU95bkZWNGpQbEZid0VpSW8KDW9cBO9tPqayfXruciuy8/MNfHhk90rp
            zrzpaXyop2pk7ixzrHn3eEzfYmMQvteH2auzGlXMvU8hCHSK3nIOfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T22:12:25Z"
    mac: ENC[AES256_GCM,data:3+fukXoIAZQumOYpr5V1QKzFAxFTEpsls80PutIi3hmQEfU1lMq1JjGUIf+CWIesqPb+LdRmYW9B4BxUB3abRwDZmPSrPhpIexxDC+9bDAh28fvviqR2lcSwaBtZqyGFDcycNpUYrxdqV56fdOw6g/SyaxVjUkPG52U3Lbo7u5A=,iv:RQCZ8hPie9yY1zBecHqOLzXWn32y0BD8readSwNil/c=,tag:CvyB9IYfEdlgDL0IuLvvwg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
