# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: toepen
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:elN7vEU0o6wBNse0VVZFhsK29EAl5TCuHuKU/7O0X0pSVXNRn28lBhY5qX9HZkamv0IMl8FmXlq2zKiDeQPtidGpXhTcIBqnzQgHIUnnfvtNLjXYnt+7MpoRAgtDUc6H8X5s,iv:rAx+/Xqw3M9tW+EM+HhNPND7uFuJSqp67Qgc7uWH9PE=,tag:k+rd3rAXoDyRkb9HCTxxdg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ckViYlFVa2UydGEwMzJi
            ODJpbGF0T0NNNi9qOXFVYnFvT0ZueVJrY3lzCmtidENhQzgrWkNYdTNvbjkwWE9D
            blk5ek5vcWVkZVRrampISDdaeUsxalUKLS0tIDJJNWVTdVk4cTFwd0tOUjBmZ2Qw
            SjR0aWl2M1ZwQjc2V2UzZjJHUm1BM3cKMVkSAn1370VN3ImEXuSNGWeYXF9SbFNm
            1IB8MBysL1vcoz0AWdEXYnjCommjm/C+pJVfOT80m4RKPMdDRu9G9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T10:25:03Z"
    mac: ENC[AES256_GCM,data:1wRujXLu92lndQX4TOmkXv/+yMyqwJ3FFY0uPB4LazmtjTO7zxf8e0JpeKVtoVY8IXYTff1nCGiLQadflLF94Uzcgnj/uS0/Ww93lZ5Coz1fayhr7D46L76EDePLvvlbBF3886HaAtb+B8nKBEkzBbZ/XS8g2AyBQg/438fwG04=,iv:8M2eq9OIEiWp/oBA6WImxcL6Y/ZTOynOaDFAZQgCZQk=,tag:TBfm44tGBU8A+jttAdX4ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
