# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: toepen-env
    namespace: toepen
type: Opaque
stringData:
    SEAT_TOKEN_SECRET: ENC[AES256_GCM,data:BFDxBRWPy7pvP+BwxQwrbKfyrdJ3iNkBSyGjoxzPRJg+ZskDuxIsFGKg1OiYLMHtPwbr2JOVYeVmsDeliYAY2g==,iv:R+sqgSRrXqAPp1TgzI5glubfoQOKBNUCyYCqCD6OCVs=,tag:RYYWSXLMAHiXPgeK0Fbgmw==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS0RFdGxGNVJINmFadVBR
            aDFtZHVTQXBENXkraDNwYXF0T1Zlc0lDSzJFClZXMVM1RTBuV1NCdlhoWUdkS1Fm
            bndBd1Jtb2svRFN4NzBISml0T2FNZDgKLS0tIGdVaFc4aWwvSGtsa0FodTV3YnVm
            MWh1b21wWHhYakcxK2tXWFowRVN2bmsKZqa4gtPLtocEmelk0zPmkvIdN675vayT
            lb9Y3SnEgIkwcvM4+r/b/VoQOiwTllxx7URbfXKWNmb4e7RmtoRSOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T10:26:34Z"
    mac: ENC[AES256_GCM,data:8BaPc28j4zruyFTLMDDL8lqvs4Ab+wWsl0vrxQ6RiwjdFYCb2BvrbxuQ4Uhc1dDZGvBoVOSaANGABDG5OsLhlpWacQxr+Wpvub9a/eF+uka1snAA1tN+ve9p34GU7R3K53yo4oB4J8qGHeAZ0apX332sCIwhvDhdwlJ/IEWqLRg=,iv:uAY8esc+9fQNDkM3YgAWAVRsH9TJVAy/flmOY1j2t8I=,tag:JunLkOOIpq5Ct5n3KimZKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
