# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: toepen-env
    namespace: toepen
type: Opaque
stringData:
    SEAT_TOKEN_SECRET: ENC[AES256_GCM,data:BFDxBRWPy7pvP+BwxQwrbKfyrdJ3iNkBSyGjoxzPRJg+ZskDuxIsFGKg1OiYLMHtPwbr2JOVYeVmsDeliYAY2g==,iv:R+sqgSRrXqAPp1TgzI5glubfoQOKBNUCyYCqCD6OCVs=,tag:RYYWSXLMAHiXPgeK0Fbgmw==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:mCeNhxnLuj9ANEtQ8RZPIfFp9tmflLRM//A9pL94EOA=,iv:KzGV7dJZVzEEJbuFt7whAaMFiSLZ8v72dyBNqOZXq0Q=,tag:LR+u02YY629mcDciHG6YfQ==,type:str]
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:bYRWqsJHK/lAWRJEi1kGGmhYIicEfXEM+OtXN0GSp1LydMUdWANg9W/G05bnUwzg1mHYqDLMb+FJmRtypNTgBnR21OL2og==,iv:kEts/imtCxA8ABRuhtI4KXWGFqKyv4eIWFlVR4iJcc0=,tag:mnO4yE8TDiNnNWp8jtSbPw==,type:str]
    DISCORD_SESSION_SECRET: ENC[AES256_GCM,data:t04MrNeO6McrMB6QKXs6ESMpq46zeDf7Hqo0tK46h/frsG/qhRKbEQY6mqP2Xx2XEwqglpIOmlbMETg+5hEPVQ==,iv:bbMPSgIP9hWO+aPI2QTgGI6AljlEAdljhPShWDma+No=,tag:qzC93YaKiIg8kKEGlVLm6Q==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUS0RFdGxGNVJINmFadVBR
            aDFtZHVTQXBENXkraDNwYXF0T1Zlc0lDSzJFClZXMVM1RTBuV1NCdlhoWUdkS1Fm
            bndBd1Jtb2svRFN4NzBISml0T2FNZDgKLS0tIGdVaFc4aWwvSGtsa0FodTV3YnVm
            MWh1b21wWHhYakcxK2tXWFowRVN2bmsKZqa4gtPLtocEmelk0zPmkvIdN675vayT
            lb9Y3SnEgIkwcvM4+r/b/VoQOiwTllxx7URbfXKWNmb4e7RmtoRSOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T14:16:27Z"
    mac: ENC[AES256_GCM,data:ZPy+noegRkTSBDP29EIwH1C5q12Zi0oYKuYcvY5cAsgGLENCPHSpdFC0ZQp+by798S1P1ZSslM9QJcaAKyoEVSl+Nl7u5llxQK/6uwnpDQAEFJ5L7YlZhXJEUu3XwiCYxJ2hLUWFvgWg46b3v6vhwUBpXerw30aQ8S6TZrTM/WI=,iv:BwGTJdau1ZMcU2CElOA9VM8l7iN4uL87fFflJoGZkKA=,tag:u0SHlP8oUHufVkxcPY5xbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
