# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lobechat-secrets
    namespace: lobechat
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:KK8szaiS4FxZsR6pYim0LHBpwxJnr+qLe+1M/lpeYTkYfqbyM80hqeB5eGY2zC3DkowbRw==,iv:Hamm3vDMwFk1G0rJ3FFPwdEcZin9KP2UW/1ZqRuowjw=,tag:oUzYWZq7eTrRnt73Wqk0/g==,type:str]
    KEY_VAULTS_SECRET: ENC[AES256_GCM,data:pFWGZS/vRu3ugITRvsD13Udryb/n/Ivr5oPWsmnCN4UiHD9Y7wv5ADIVNXY=,iv:WSNCxM5zej38mCRFoq54S7vswaycirVlDdwbB1K8bYY=,tag:rVcnhoau8jKeFIwqIuoGXQ==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:thIkWcxSm+8zCt3hS1buEq2UIxwJ4U872i2iRppwUJh3AGlkuQ8AA9HbGkM=,iv:IGuuJlxpSYljbSqUKezaX/EDEsh1tl1OKVIp5DBwnJI=,tag:T7gEQM+2u+LWbdsLIg3uPg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:sADFv6+WVfxwFbzCIP2i5pBKt19/4d7ftrUlX9kPxQk/ud485Il5rSP+Y4c=,iv:adQavox4OdgSWYa9DoVmYCfnIr9by54Q672Vr0SPYlg=,tag:kkmvs4h6XoHXiQfpBqwciw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:zELfLy/haXJxlym3Ur+7lWvvCKppj/FoxA1NHkRL3IURAsq00SHROY15tutjTCsn8j2vJ/44SR460V8zwu6AQ0zFwPkkSUd46MolxTN+HkAlvFDnz5Kr,iv:NyN7OBt345RCNZaCBFkPnGsmITnbESsEz3Bb1ZBXIa4=,tag:qhkLWuogS5DKKvsptVWAJg==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:NXJUm7guS+dZds9h5wqg8vE0e1wTr+LLrw==,iv:jHXE41GL4/yErRUSEIIMkOamnhF6oWJJkKY5hz4jjk4=,tag:SCRtCY+zyxNZ1hBj19ijCw==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:03YvDvVtBijg8hJvGw/W7AZsbBXTFXjHKm+jxF1VbHqFlbzfJ12XbvfUlQwgXFjs,iv:iYsUJQw8qX2wUHib0x7gObgNrI9VEQ7ZmHMyyLrkk4E=,tag:z4gwl/SJwsHmkZHHdQmmIg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQei8vVnFWUER1Vk0raFRa
            OEp0L0NnQy9VdGFKSDJwZ3UyNldMNGFDMm53CmpyZHBWdmdkRUpCaStwN2FNaWQ0
            UkVCSmM3SUFHeFAwV2NBV3Y2MGlyTkUKLS0tIDJSbUsyM0JNT3ZkaCtjZVB5aExN
            STllVWhwbkt1cW9ZaldYL1NER1F2czAKGegn15tl/YsF2B7/VTHLpLmuP0lAHMSB
            /NGuoyaggkSHzz1G/qOTrhXPbrs4VP6uH/T95yATc/S53C0z6Tvvug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T12:52:28Z"
    mac: ENC[AES256_GCM,data:ZiHRDrtLXOQRVm2gQ4IaLKcjqqUueM89gAt5UXLdE9ZgspT1WvBjg+FbugK4FqV0OsK2DLGv02LBf9WfNA0zA5ItyjVLR/N5t79EzyiByHsuIfYrko87j1OnisRUqy3YX8nADEtampcxwCiOTqsbgyqGsrrifAeSRiNOmpfiIrQ=,iv:MeN+ZVcSwTCXo08ZGGHl5G6WiO61ILxHS54qnzgBHaI=,tag:Lms52llSQ52R0nXiXslb7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
