# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lobechat-secrets
    namespace: lobechat
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:sYnb8la5fy7+h8iqOI31S7isRxCF4nSpU355+r9mEwf5dwjeg4JtroXcNrAVxZOubVzGTw==,iv:kwPpe0VkOjqthLqNtpO+zOJ+wyEqE538Q1Rk3QIqE1U=,tag:CRtEoZep2CEMY3Wp9RS2Iw==,type:str]
    KEY_VAULTS_SECRET: ENC[AES256_GCM,data:bVuPEXfrKQVMlJKER2FEijy76N5np1h671bQ6glBmTGsVenckJweeYb+5MU=,iv:JlM2iVoGWeH0s6CH/GPBxzEuMYb8qU8mdVo/ntQn71M=,tag:qTqwYP71PyYpVpFx0Q1dZA==,type:str]
    AUTH_SECRET: ENC[AES256_GCM,data:SGhFk3ZpnTZ8yEAXN6TuQ9Uv4o/BU+D2L5xRG6jOHPqJ0kc3YOTG/BkCMoo=,iv:NSjfh+7Rs+9QY2T49AyI8G5XzAypl1OlML+S6j1PGFU=,tag:KJIbPLT9+3iS8Ql34vonAg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:3FS8hvedICGSiLS2K0Zp8HnjILQDNpUQDfvMCBW3SMWAXTq2tcoFtIIWCH8=,iv:lo8gpNGocMhougphgYof8dtzzvsIYhTdSPbZW6kwZhY=,tag:kvs0MdHibkAnQaPmmJauEw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:+JDdkrFpGTOtCLFA1jzR5Z+RyneZrjZ9XnKrji35eqK5Ve3ZK9jK5BMIiGIEPgV6ZaPtfSGdofKQKMjLLHOHsgSQ92V7+KjVO8eHahKR44rQWfAxoLrH,iv:pjWxxKf8ckjz/aPaI2l9gxgmUBdTVQGJr1fwChFHAqo=,tag:huh3kzSV9gif3MHnm8elIw==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlOUhPQmx5eG1COE1sVHNN
            YmY5dmtjU0JQYjZjUzExWW9WVU9JMDB0RzJBCjgyclY5Sk5DLzRRcXpmMk5wRXlE
            YjE3a1l3MlVZRGVENyt1Mms0REZWclEKLS0tIEJDelVBNURRa0lWZ1htQnFRSnV0
            TnkyVWtYTDhHWXRtQmFTL1NYRVJIY00K0s0VqcWFF9QxzHvPZLJzxZGVOhnCjSIL
            0G3SPZ2EI5Wm5MYtstNeDBnHYmADqNvwsEZfLye0sgloLG19LWbStw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T12:08:57Z"
    mac: ENC[AES256_GCM,data:1yQDISV42pKx36427ztTHTWZ8JYBWPNGB34bnG6sYPf+eBavgxaRO1e4eOmNcPHHyWGhHwO4sAGiK5qglKVSl4L8oKOE15K62x38NTO03jqcjuHh87xK0Rpsxlze75KSEFa3+YSFoLWRxNXtSJPAOmhIHhajVx0LCrbqFM3iMKA=,iv:Q8mMFbb/qTmjXNytDSR0RodExCKp9cwU6rSaa7rRi/4=,tag:KFX1Tk1hHpsrFMtYoxusxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
