# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: boodschappen-env
    namespace: boodschappen
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Uz9ZPHMPxwzwC3SvkXrUJgXXzGxKITuG0NTkaEj7Q2BQtQ+aws59FZByjbzjhCUlwwtBn4+IuJKYE1+aX68vuw==,iv:nePJNrtRIv2Oxz+8YOEsx/HvxeAXTwzOgbTrSyb/M5E=,tag:g+cKICtJwSBnpkXUZ4Bncg==,type:str]
    CRON_SECRET: ENC[AES256_GCM,data:9/ljqMkBLGCJSdh9fAA987Jrs5DASw+SqZnEPJX4nLppRdbVHcQUWl5nrmi23205IGq8t7teCQjo33gAWlowIg==,iv:vGuTB5kAiC+edCouCxhg/SFGDE3FoyBI+PrBZH+a+HY=,tag:qTD1DvRf063QyTYA3jN+hg==,type:str]
    PUBLIC_VAPID_KEY: ENC[AES256_GCM,data:7TWdS5z4pENr/lRndEXBlZ3sfuf4M06vJDXo9fMKzfyqJOFneIblzs3TDPZ8wT0oMO+rbiYFJNN8dDXbC4QIJZnCMpDNCEQeOTx/gLB5S5D3Mlw2pCuf,iv:2Om4ZjNKdlm0SZyh6YHMG0JFLc6ovg7lejAxMV9ZelY=,tag:W9LxjbKoa+ffHUe5ttnnrw==,type:str]
    PRIVATE_VAPID_KEY: ENC[AES256_GCM,data:8LRY7DEIM+slfx5JOVyY/RF3POpvJkVwfaF9Yc1UY3F09Bm0KIHd6YC37g==,iv:BDqDf+0VMFdb0kTwOW0xo2thgEJK3czx3x0GzUpXjyc=,tag:/KhzwW6vewfAZ2ffvmJoUw==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:ZbN0w7j9CVox+QcV7wrttnoFsJlAG/sMC/k4obCQjitPw2gyvymm,iv:KfJAxXfltU4w62l+RU1QPxm3Gl5Ns01gRviHuM0GniQ=,tag:vBTwcmKG/N1Bci0Mvoqn+A==,type:str]
    BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:RYRTEd1wr3RvZN6NImZEmo9thflvkf3y3TdVpGhqJpWD1PNtIPXPaQpnSbNGinWu19hMuMum31KqcGSj7m6iWA==,iv:Y27nsiXzjevgJDs1ihFAQyVS5FKyz2P0SX5ZP/8ECQk=,tag:62j/jSl2QoZv8pWi8awHWg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQisyRythWVNGZ3hKSWNw
            U3ZycXN3ODJuVERmc0dtNFl6QjU5L2RtaUVjCldPdTM5RGxmN3oxYjJ5ZGM1c0N3
            bkFUdTNsMSt4SFpIbUJFWUg1cUo1NEUKLS0tIER1Mzl1SlQyWkRtSzVRbnNrS1NU
            WHdWcWtTWWRUVzdhdHBVMkVVS0pER1EKQ5dZ2QkGljJj2yf8G7wl2nhUMuZh1rv4
            VUZ4Pn/eijgpoPXCzg8+jOAZDESWQlzTIE6AutSDykQ7W8fThvNpuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T09:28:14Z"
    mac: ENC[AES256_GCM,data:vI0pFjU2uhAjAv+hbLdqB/lZbsazRW5nDQGZv2/q7RJ78h/O+nbySFVWWMPU0OixgYOeNdd/zziFOHNlw6JpuIRd2FVSHgewP2S0WRXIsoQmCm/1BlzZobPk7bEFOYD15JORIhteX01wP2wKNL+TxD5hlB8XDp67k4GN0iDA+R8=,iv:Td6npUBuBkt1bMv3dQASIQzjia4ZECMFusADY23rAoY=,tag:5c7wym+BjnhQxnZHGHgvPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
