# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: boodschappen-env
    namespace: boodschappen
type: Opaque
stringData:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:Uz9ZPHMPxwzwC3SvkXrUJgXXzGxKITuG0NTkaEj7Q2BQtQ+aws59FZByjbzjhCUlwwtBn4+IuJKYE1+aX68vuw==,iv:nePJNrtRIv2Oxz+8YOEsx/HvxeAXTwzOgbTrSyb/M5E=,tag:g+cKICtJwSBnpkXUZ4Bncg==,type:str]
    CRON_SECRET: ENC[AES256_GCM,data:9/ljqMkBLGCJSdh9fAA987Jrs5DASw+SqZnEPJX4nLppRdbVHcQUWl5nrmi23205IGq8t7teCQjo33gAWlowIg==,iv:vGuTB5kAiC+edCouCxhg/SFGDE3FoyBI+PrBZH+a+HY=,tag:qTD1DvRf063QyTYA3jN+hg==,type:str]
    PUBLIC_VAPID_KEY: ENC[AES256_GCM,data:7TWdS5z4pENr/lRndEXBlZ3sfuf4M06vJDXo9fMKzfyqJOFneIblzs3TDPZ8wT0oMO+rbiYFJNN8dDXbC4QIJZnCMpDNCEQeOTx/gLB5S5D3Mlw2pCuf,iv:2Om4ZjNKdlm0SZyh6YHMG0JFLc6ovg7lejAxMV9ZelY=,tag:W9LxjbKoa+ffHUe5ttnnrw==,type:str]
    PRIVATE_VAPID_KEY: ENC[AES256_GCM,data:8LRY7DEIM+slfx5JOVyY/RF3POpvJkVwfaF9Yc1UY3F09Bm0KIHd6YC37g==,iv:BDqDf+0VMFdb0kTwOW0xo2thgEJK3czx3x0GzUpXjyc=,tag:/KhzwW6vewfAZ2ffvmJoUw==,type:str]
    VAPID_SUBJECT: ENC[AES256_GCM,data:ZbN0w7j9CVox+QcV7wrttnoFsJlAG/sMC/k4obCQjitPw2gyvymm,iv:KfJAxXfltU4w62l+RU1QPxm3Gl5Ns01gRviHuM0GniQ=,tag:vBTwcmKG/N1Bci0Mvoqn+A==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQisyRythWVNGZ3hKSWNw
            U3ZycXN3ODJuVERmc0dtNFl6QjU5L2RtaUVjCldPdTM5RGxmN3oxYjJ5ZGM1c0N3
            bkFUdTNsMSt4SFpIbUJFWUg1cUo1NEUKLS0tIER1Mzl1SlQyWkRtSzVRbnNrS1NU
            WHdWcWtTWWRUVzdhdHBVMkVVS0pER1EKQ5dZ2QkGljJj2yf8G7wl2nhUMuZh1rv4
            VUZ4Pn/eijgpoPXCzg8+jOAZDESWQlzTIE6AutSDykQ7W8fThvNpuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T19:46:03Z"
    mac: ENC[AES256_GCM,data:grk8tVsSqBCdoBsdvaAXm8YHQgQ+IvJTJxx/lM6Al5QCfKnu1s0Cb5fESDBpS1ia1hwCR3B0k2E25AVnZTmMb7U264t2zz9bzsLeW68FX+RMmvDbP/qS17hEjWYdXd1U22njOHSOS5Htqz1yOOoruKeMKGb81PHAKtNCf5TrjK0=,iv:GfsbSEp8ZkZh8+9ya1DWbHfWsQoCpAM5ugQa2Vd6VQ4=,tag:XGtBYabxNcXFesJljZ5hGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
