---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cod-zombies-pap-checklist
  - cv-web
  - dartbingo
  - openwebui
  - prowlarr
  - tunetap-app
  - klavier-dev
  # Rudy is now hosted on Cloudflare Workers.
  # - rudy-website
  - resonance
  - docs-site
