# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: hetzner-firewall-home-ip
    namespace: hetzner-firewall-home-ip
type: Opaque
stringData:
    HCLOUD_TOKEN: ENC[AES256_GCM,data:Wihfmjbb/7mPA1ruOdmmf+ROY9E7gRNVOv7BNkS8hxvqDM4SnvXYdxkKCF+qK4dkkp6gYenTPi5mFmJsoPEdXA==,iv:TT85L2zZgcZWozxhcOk530r+0M0VNZZJpFRVdVXAjKc=,tag:w8HqGt+L9D7XUok3mMvVIg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTck9JNHNpU2FWWXFRZEZp
            c3ZXSFZNaG52cnN3U244Nkt0amdzalUvOVJRCllEZEVvUll0MHpCeXlqRGdMdmQz
            V2M0YmEzVDNkK3ZPT3RtN1A1WG5EdUEKLS0tIEZQV2hSa2ZXeXhFcDQ3d3AvRnZQ
            QW5YQllNamxja2ZDa29FVFNJSXBrMHMKJhuOPQ7IdVlVs/54LGlcaNg2rXPHXOwO
            KhzO1BQYDt9N2zypHK8pD1f67YyU/dOP44nTNP8vEZh4Ox7lCHgzEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T16:15:57Z"
    mac: ENC[AES256_GCM,data:cApy1UgpGGssKBlcht388IV1r62dQegUUI12OrvePl5Xuipe7l7beJRONhY8T61eYRs3SM5mnOBSDjav0Z1rMV9gVEl8Et1r/HJFttq3KIlIRTdyYKE8/26bE3Zr7MqTMfXcDsAZWVBmUhidM2cu/eFqRxmkxZuZLgiTupApwWU=,iv:7ycj5tcR52ka79mXfR/Vh1tLjIVXzKzXY74iqmewfuM=,tag:p+BnCCxcww5+oZkMgaXNdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
