---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: "0.14.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: metallb-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: admissionregistration.k8s.io
              version: v1
              kind: ValidatingWebhookConfiguration
              name: metallb-webhook-configuration
            patch: |
              - op: replace
                path: /webhooks/0/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/0/timeoutSeconds
                value: 30
              - op: replace
                path: /webhooks/1/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/1/timeoutSeconds
                value: 30
              - op: replace
                path: /webhooks/2/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/2/timeoutSeconds
                value: 30
              - op: replace
                path: /webhooks/3/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/3/timeoutSeconds
                value: 30
              - op: replace
                path: /webhooks/4/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/4/timeoutSeconds
                value: 30
              - op: replace
                path: /webhooks/5/failurePolicy
                value: Ignore
              - op: replace
                path: /webhooks/5/timeoutSeconds
                value: 30
