# yamllint disable rule:line-length
apiVersion: v1
kind: Secret
metadata:
  name: resonance-env
  namespace: resonance
type: Opaque
data:
  POT_SERVER_URL: ENC[AES256_GCM,data:/2y2NL7ls25ysSktibBmRmSNeo7BjgWMH/KJ5ud7I08=,iv:dRHj8qIhJomCMc/ZZJIsLyKxlTaTIpUDy1YgHx28cRE=,tag:XFsSuyP7YUtZMd2Lx3ietA==,type:str]
  DISCORD_TOKEN: ENC[AES256_GCM,data:x7yJYLUHqLDZbr1MaXZdge9wvQ3AIn+8glSv/uUvMwYKEPS4tftQ3OywWSdpjUgxGfMvhCOHfMjMwDsZ14LUK0lTc3o+IiLgQ+cTB8siaW1wkECx6U6G7qlNJgvmHBhQ,iv:ugjFkJhmxMygVyngITFBsH8X7uze1t4YyxZSeKgbSO8=,tag:icXPvRyxAhIEs6tP8ecCjA==,type:str]
  RUST_LOG: ENC[AES256_GCM,data:+ZBawk+T7uZWycRERaBhwT9ShSjRdoTu6IHCvQ==,iv:PaKXT+ORSKV5yQ7QV4IMhiYp1ja/KK8DDFZPUTPGW1I=,tag:wp/GHuA6ouel4Jv1LSJDUQ==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:RnJ+h1jEQTLVk4bRwFoPmNOTp2y2Fc4p,iv:UBlaBuskxdBpLtB5rdkqVL759eA3z62FH/TE5aoqobk=,tag:7VZsmm3PFk8fxsUougX67Q==,type:str]
sops:
  age:
    - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQTBybEVBaXdxRGo2WDFR
        QnJrTlZDcVE1N0FwUU5iOTBHOFU3Z0djMlVNCmg3aXBQTENNdVI1WjNoVG16dmph
        NnQwUW5paHo5WngvWDhOc2hoakt5WDAKLS0tIEU3T1FnVzNvWGU2eHdZS1lYLzRD
        ZUhYTW1yODJzOGNuMUh5MUJac1ZTdTAKnD7SQE77EYmJMiDJ+a7ZUWUvGmb5m4fs
        ghTRlxKRv/q7CFUjGhKiHuS7oWmzcJttc81aupWrL+Cwj7sor1qQlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T14:44:23Z"
  mac: ENC[AES256_GCM,data:+yRM0hdSCNcgA/VnRHZoui9MoUL6nQgcmkVglA3zBij1ZQZUxqnNT8PRO0lWW7nZLarHqf+IfnbnNHNu8vr4j/YcvvzectVcNBiH0pV6KqIOiztp3FIJyxKOqzvH6iFgk5ySqiEACjwc5ko+t9vB1L13jZNU2guZOr36MwFu3bg=,iv:Ww1EnqSvXrSBtc6p26lx339Hpkc2sunoYqPV6ZHgoLg=,tag:0bQtiruwneTx+BkaQfVBxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
