# yamllint disable-file
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:tquavyYEhpm4veuHwHggk/E=,iv:0vNQ2V39nqm7fMXaky7tQYuO3VsNDCP33u8PNpbRbIg=,tag:M0U96F0YzfYL7LgP61mRNw==,type:str]
    client_secret: ENC[AES256_GCM,data:JFyf7ByHSY374t4xvFMgnLZ9Io01lMGht9IHijKR1R7zDW4iBPz6GjjgWy0fmQ/G4zzSwGe6xO9vcmDb3isSqA==,iv:OfWyCAjYWkpTEmFsm056nF1J4eINg2dv5WZqw9F+nWs=,tag:CEhYO3y5kuSoNFoP8ohkRg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbUlwd09WRmozNTlGbm1N
            UUFPUERyQlIzVWk2bTQralVwaUc1Z29zQVdzCmIzZHovM1ZMV0NKa0xZWTlLS3RI
            OWFlRGNsdVRSYlpaYUNVaCtYME9QeDQKLS0tIFN2a3crbUNaSGk2K3NIQlZ2eVQ0
            UXdvTFpPd214bXVub044T0ROdG81MzAKPSIyIQfLoBBwP5kGwgQpG8wlU3L61iYh
            LAL05svRFScYirCh8j1u9ad1Qj5jgMmFuUJ0oUNp2cdQNsOXCzU3Sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T21:06:41Z"
    mac: ENC[AES256_GCM,data:017Wr3UQ53EGxEuY0wwyxPSZJ8SmlLzzpXv3YyUIjsye3gyI3r1LRgVttTmO6rlCn693TsArclTESWVYTlYYHTjdni6Vyq+h9ZE4zatqff+OHMfjma8qgjvFfZGkHYMCjvFXzA0U9QGUr9p2oZXJX09f9PLD2CIsItLOkUBJRzU=,iv:IKQnri/gQRt6Y2IPyWLvueZDBJMU7K7mCujdbGThsjA=,tag:9dK5/Wuuf5a+efcqpKE4Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
