---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netmon-data
  namespace: netmon
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
