# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: netmon-tokens
    namespace: netmon
type: Opaque
stringData:
    site.vandersteen: ENC[AES256_GCM,data:nOvmYTVtGGpuayu3HuwqB5lsEfIgnhn/jkjLk2GEPKLm7Bmx4fKL1saxPQ==,iv:giH+Hcb0kQIqsYhfRRnvNHgIK1YS/AyEBhE+wkUUbg4=,tag:6/7vh2cs76KER3LrlIWyqg==,type:str]
    admin: ENC[AES256_GCM,data:koA0w2ocb2+nZAzk4STs0v3xH1zN1bB5QGP3Lc6XKO3Y+H/BwVfRq3F5WA==,iv:2Ua4d0ONEo1wVteEVZkdSXlqBAeYMDGQz1f1I7OY63k=,tag:Qq78vYt8/Vm0xzXB2jrOZQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidmNldHJPMXlRL3hPdC9z
            ZWRzYzZzUFRKUDV0ZmowOVVlVEQxMFRFWXdvCkVOVkVoRXhLL3Y2SnBWaDg5THFo
            d1BrOEU1ZnpkKzloQ1E3MytjQ1gzUVEKLS0tIFVtUERPM3E3ZmlpQ0xpemhwaUlZ
            YThRcHFIS2QySUVsRnZhTmo1Z1duaDAKy17ipNMcflsqXhyciFezK+EHExjBJ9ze
            iOh7XDRDD2L+U14fGMbtfvZAi7oaAHxhCEVQQKaz8KAzQ0mK6xgxpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T15:42:15Z"
    mac: ENC[AES256_GCM,data:A92UHd4Y1n48/5Px/YJdLRrJRLNSdXY0VIAVlAg6nmVlNfl2EmiAjBal1I1DJ3PPDmXN/9ItreLVwWlHsBbe770r4qDqHl1Ph8Y/I/s/c6Ivgus5q7X+oilnFOYpwB5JFVUPM+jfu4y8DaUFE1qGLvIivbqS402FwDYv6IJ46Y8=,iv:KnRWqXt3zBFU7L7CkUSrjydqBmp7Em/r+fGD77FE4N8=,tag:/949D6IxhnrvD8ZjZjHo9g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
