# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-config
    namespace: cliproxyapi
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:BCzSnULslep/KAjnyLOVPKLChEM8zvQ+z1cx59Ny6ZmMbqVvqC0ig9HzQsHWXPtnSenVlj4lycUnMVHtsChcQb4zaJzFbsvsRxeRhiuwtvz3J6gGT0IIN5Kx5hqjQ9NfFZpqxCUxn+gKZ8si+VjBnRgPu6kccKPSYEbfTAcZPmNewuIgaKBFHMr13Dv7Z/8NOYt8IS8KgXaTdT4kDxk/jzDVDFefwpjNOypKsVVKcADip0XZdPEkqtsgunfqaxk0UbHJiUDByhvzYpqFfrx7KpinTkgXe775SzhKyiCJxKRO2TYZoUawD/GXeK5vu2wWYIn4GkqutWczjsu8fsuuEdygwSk4lnZx/dFVL87MfIDw54gCkCXJeBOCVA982IY3ZXOKM65lZTI0OwBSsFV7RAXanK8OsCYbhhBBy5j48PJxv4kGGFoSVH0YrMy5rZt3loIKbLgGTrsVTodFql1aP2T06JgGYDHyZZCiufuunBJFF0TSrXHm3a8lIrSQ8tbxfVCzwKNXExR/zzr9Zd2JKvX3paTkU0+R9JFaa3dL/h08BJR7AZK+X3NZa3BUHb//9UEQyT5PZSKySURkHZwV1Y4/8PBdWv2UQDkRwNCgsyYhwb5R09cW/2a8EYfhY3T97YunQmKaVFtf114QLmGy6QPI3mby0jsQBlzly1LgKW6xvmG2LkIH4pUfvFxHljxQeDktggTyyQp910E1wdSQUZsaHR3Wryy/i30p2N6zZ+N7IRprEJkM5deUWw8yBMV15JeFgiLCv35WGSdQSiNUqxeIJfTwEtyzY3CQxgEO9To0feCxRgYmzlfF0vl7dCnqq6KChwuQ6Dll3QJHb3u9Hgg0iEGPuicrlcDVAC5/h25b6KbIl0mL82rrZyYJXGnCUG6XRbxWWA/b6SajdFRhB/SRdYGnqqQl9MuL6VfUs2/r3e4FKlwKX5YKrNHm1bl4Ksd0XZEGucEsCGBO9SgcYqYVvi1Lx4xkPtoS4OH//Mf7ZB0lZHDqPYF9rAAypY7P3nXJiGAUt8LUWVdieOfqjpCZ35JV88da58XrDFnyQcUsRGQpf7om7EbrE3IYRuVAELY=,iv:derSpP+oYY2ZavirgG00GqDLZm2njNLkgkke5v4Itzs=,tag:wgWNF/898loKryGpv3hdPQ==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS09SZXVFTjRaVjBSWHlm
            aDFjTVZlTTRpdC9YdGNucy9vMlh5dEJvUWxJClNnU3I0U2NvdkVZeE02N1ZqT0l3
            ZVRhYjRaNSt4aWkwV2pRQndMeGc2cXcKLS0tIG9iVW84YXNYU2dLaEJLS2daZFRI
            Vk5EMG9TUWVscCttb2k4RFllemhZRlUKBuK18Pe88VGL3i+DYcLERdYYjAUvK5nL
            MX8raB3WMktYVIP4yLABumQOJD0laUp4mjDPOGiniXsD8w3cGuIZtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T17:35:02Z"
    mac: ENC[AES256_GCM,data:ru0XBNyNQ6b9zGhhexQbYvVR40VF7fNW418bhLvsnKlTYI8m1flmfOj3A3aKSoTBFC85A19uBoH/QxyUEv59W0Aw8nOMXUmsdN6jRfpJfiD8/DReMoABG5YNP6BhLMPt8ci+IXWcDMHG+XRJN8dIojwZOH3OAOPg8N/EmeKwCIY=,iv:MTBe765fdrxucqvL2WAIPOKiaYxvsy3sb5UHCmSZsws=,tag:Qq+PA4eSxJ8cc+rIM9YTXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
