# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cliproxyapi-config
    namespace: cliproxyapi
type: Opaque
stringData:
    config.yaml: ENC[AES256_GCM,data:xhqi5N+OobmrGq/3b9rvO00kp7IIcgUeEPdMW1RTEnT2lB/GD888htXgpaXT3RPOJ/1mggsMbFdnjV4ONx9NwyI+TsuGMSCC+R1pKJZi8v+mGedPPtPkW3SZlvPUgTLUfhRYywUN6ixCmX25eKk9x0fGQBo3jvrbUSbBxaCivM8nuNgtM4zDaxnE4ahz+azMIVH5Nm/1CQwAZLMWYQ/kSISVixkD0f15DJ0sJZ5jOX1I1mx06CnYkXebNerRZEPvUJKCGIYr1lhG/cYZd9dfM0CQVXR+DRbBtf/29L7Nh66TlrPTlfEdXGGsMVCdY4VgTR/1MVcmgiE9UMVyJxHbPjz7VgU5BqvSWCUsapLzcWMs8D+lCABje/Zp6pbV5ntdzWLtWlJ5ypoDeaUp5yViIGTAYFRjKt9rJvlry8yFkq44uA3bHy0rolOOPC6hx6hxekeqp6g7uu5fHQNinvBsVR5WbE2+jn9ZvfpLXMc8IKvSplWxrJ3hz9U4w1CBauiU3WfAhYr5KDmWflib0Xz/XuRWwBGYEpVKAACFGlOWCfTQKly80WJdjslstkfpxKYGAZt+i1GcqzNzZNYANQ2OfrcNv0H2kiu4baEuUMACJ4Ssj8zRFB6qXmRE2Z/hFEFVJ0D0ELgJiHtnUBCwxkmXVJs8pn98kWlJ/3t8NlXympLTH1DXJ4Vx+1U8rWzJUEf7JAGdPFVRkGnHR9xXsdkwHAE6Rd2U+3GTpx5gP/9FfTxfTRdG+iRiNjwxL9Bw/+1FpUuXvIU/GqIqIB/SiYfrrYxy8qU5KHkRV1OYWxOHK1PVyFU57wTIknFpafDgo3pMq3/kx99WqxE0v7/wk9JxNHUTux9mqICI5+iGihvj5zxC1rGGQre9tk4CnVQ/0PKu7azQSgM4dYf/s6NiiqSOwqHsXapd2W+rWRWBeHz7B7T5KCuoTkUwM3Fp+DAStQ7qIjqiAqu4ulviZTRtW4MTYNzfZtVT3sRt9AXp9sZ42vn8C/kshckpVoyG5WTnQTXg36HsKjIBFzbeAEInHPl2lkJCNOpRav3iymZZpK1Ky3qwj0R//q3ybMH6LdAw1KYqICc=,iv:+A4GnhrdOkeJ53EtQy+IU+pxnPXNyR1cTKwK1NKoPMQ=,tag:B5uUt4gXG6baonZc72tZ5g==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS09SZXVFTjRaVjBSWHlm
            aDFjTVZlTTRpdC9YdGNucy9vMlh5dEJvUWxJClNnU3I0U2NvdkVZeE02N1ZqT0l3
            ZVRhYjRaNSt4aWkwV2pRQndMeGc2cXcKLS0tIG9iVW84YXNYU2dLaEJLS2daZFRI
            Vk5EMG9TUWVscCttb2k4RFllemhZRlUKBuK18Pe88VGL3i+DYcLERdYYjAUvK5nL
            MX8raB3WMktYVIP4yLABumQOJD0laUp4mjDPOGiniXsD8w3cGuIZtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T11:15:03Z"
    mac: ENC[AES256_GCM,data:XA/IjIafRYq/Ce/LQOllfhyhBhaQmlAA8oovuwARtZIXt+O5izu0gVl7ogxSLiiuyKq0AFRjmwsUBQucr9wkVt/ttUc4EVFY7o8DZYaramJsDGKgoprkocdrCX0RwyYePqhQ2hbkk56tut+d+a6S44sdM6ddTbjPuMFsPi1fSSk=,iv:j+66vkFKAG76kDTCs9m4adVdvzVK6Xy3OZaCyG62Aqo=,tag:rmKwRQZD38Phwtq7hg078A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
