---
apiVersion: v1
kind: Service
metadata:
  name: cliproxyapi
  namespace: cliproxyapi
spec:
  type: ClusterIP
  selector:
    app: cliproxyapi
  ports:
    - name: http
      port: 8317
      targetPort: http
