---
apiVersion: v1
kind: Namespace
metadata:
  name: remote-hetzner
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-api
  namespace: remote-hetzner
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kubernetes-api
  namespace: remote-hetzner
  labels:
    kubernetes.io/service-name: kubernetes-api
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - 10.53.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: docs-site
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: docs-site-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cod-zombies-pap-checklist
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: cod-zombies-pap-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cv-web
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: cv-web-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rudy-website
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: rudy-website-hetzner.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dartbingo
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: dartbingo-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: prowlarr-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 9696
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-site
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: docs.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs-site
                port:
                  number: 80
  tls:
    - hosts:
        - docs.jensvanzutphen.com
      secretName: docs-site-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cod-zombies-pap-checklist
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pap.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cod-zombies-pap-checklist
                port:
                  number: 3000
  tls:
    - hosts:
        - pap.jensvanzutphen.com
      secretName: cod-zombies-pap-checklist-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-web
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: cv.tunetap.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-web
                port:
                  number: 3000
    - host: cv.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cv-web
                port:
                  number: 3000
  tls:
    - hosts:
        - cv.tunetap.xyz
        - cv.jensvanzutphen.com
      secretName: cv-web-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rudy-website
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: rudy.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rudy-website
                port:
                  number: 3000
  tls:
    - hosts:
        - rudy.jensvanzutphen.com
      secretName: rudy-website-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dartbingo
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: dart.tunetap.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dartbingo
                port:
                  number: 3000
  tls:
    - hosts:
        - dart.tunetap.xyz
      secretName: dartbingo-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: prowlarr.tunetap.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prowlarr
                port:
                  number: 9696
  tls:
    - hosts:
        - prowlarr.tunetap.xyz
      secretName: prowlarr-tls
---
apiVersion: v1
kind: Service
metadata:
  name: nzbdav
  namespace: remote-hetzner
  annotations:
    tailscale.com/tailnet-fqdn: nzbdav-hetzner-1.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 3000
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbdav
  namespace: remote-hetzner
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: nzbdav.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nzbdav
                port:
                  number: 3000
  tls:
    - hosts:
        - nzbdav.jensvanzutphen.com
      secretName: nzbdav-tls
