---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spottarr-data
  namespace: spottarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
