# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: spottarr-secrets
    namespace: spottarr
type: Opaque
stringData:
    USENET__HOSTNAME: ENC[AES256_GCM,data:wG0K6u8hQ7siIClniQ==,iv:X8Y7wTTl3lsTMk3AfEtIgbPzMQiYc9xRU/QpusNoBq0=,tag:00oURsSIB3dtWsNFdZD0ow==,type:str]
    USENET__USERNAME: ENC[AES256_GCM,data:gu8kOS+MVgqWJ5sk8O3u+A==,iv:TewLPLyYrWkFuVBdNwRjMODXa/a++hchVSxdirTl9d0=,tag:zQctkLP84N9b5r7QCx6OYg==,type:str]
    USENET__PASSWORD: ENC[AES256_GCM,data:VnHnsANIejLLz4E=,iv:wNNogWVlre9dUdlYbqKt7dNCIRMysBuH3oKImq8XPUo=,tag:gz67TdDx4l+axk004Tp+rw==,type:str]
    USENET__PORT: ENC[AES256_GCM,data:QD6g,iv:8A1secgtkPnO5rpBynsgkkHn7XVeTrgXEq/GjgfFGG8=,tag:Dl0FAUWVluyaXo7IGYY2HQ==,type:str]
    USENET__USETLS: ENC[AES256_GCM,data:M5JWJw==,iv:SsFcZ9/rv14CSzK+8bK0kIyaC135+qvEGwKhLslRHKQ=,tag:VOneNq5Mw8KPVQ+++jcU8Q==,type:str]
    NEWZNAB__APIKEY: ENC[AES256_GCM,data:UQ20WVdpLy6YvtgDAWdjk/Foiehbzbbf/xAI03D2mSdngYsnz/LGhbtTpRYSZ2ufoUsJMNXgHywuwn3fjoJ3KA==,iv:dPDEDiA7L8lrXs+XZT3P46Rqk8O1V/JRpmxa/Pka2UA=,tag:2yD8RyHfoOjPQ+VQMhdJDg==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQlR5SHROOVFLUVZ3OENU
            b1N2blBnU3dkdnFxSUJkeUk5VWp6UU9obGl3CnZ5b0hMeTNwN2k3RDJ2VVBacGVL
            M1pWRmhnODhXVU1UMVhnYktuU1E3WlkKLS0tIGZTZ0FvKzVPMkdPeElKdU9oOVV6
            ZW1rcFBGS1pQNjE2cWROUGZVTmsrWlUKi8Fv4mVyM01pKyWQbfSSBSCa/bGSFBN3
            EABJgr2OWraDCR0oKLX1RnrVWEzJpu923mqxoeskIeU3Ym1ZCD1epw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T15:30:37Z"
    mac: ENC[AES256_GCM,data:rXHeDIKMUx7Kc9Y0+D/GSFMMQaH2DwaqXRWTRazKRFOOVp8KxXWJ0ehHelbPytf2t0YnYOa2fI1YhqINAkkV8nJiqW/Ryq6rYwuYJfK5eV7WOO7Is8tPNriqOYHSdY9F2mjosGgsrQD5hVn95lpohhQotQy3b1pjiK4jquo7DgI=,iv:x703BdvWH7MiqYyDkzpoe1kqwNMLrYRRv5xa1U8lHnU=,tag:XnRHsckKntqXJGILWLWidA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
