# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: strikers
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6lQUAxHgakDj/iLyyux7j6AJiLcCrt8XX5DzUpomFd1oVJOcUs64DO/JpjKvKcig0XXYRXkj7nx/n+wdf9AwK45dO7PDJQ9BHBhgFlPLq8BnLfCDB8RkNxT9q31/vwpLSd8p,iv:rSQlPSBKzLJDGF66SBOT5RLSDJJfN+1luWtDtIDqBnE=,tag:VqVDitXLijFC9/X0EbqntA==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV0lOejZBaktnQVVScHBp
            N0duTVNRbWF6UDdKV3dIaDkwdmFrNnMyVlFNCnFjTlZGM2ZYanNGNndMeTdmdVdW
            Y2svKzE1VTR3amdkLzc3UThlckxjTnMKLS0tIENIRzVmdGVlNUZBbVljdkJrMy9u
            cnJUUzg1UzJkRkcwU3c4Y2drZ2t3QlEKEF5C008vpjDq6mUSgmG8b/LXGoq92i4i
            kTvS/1n2eyuajO6O17Y9kEqGTwRHUBpkXGa1iscR7mQw0IEGf02cYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T18:02:58Z"
    mac: ENC[AES256_GCM,data:YhmFQ2jmWO3kqry6BPknj48GHkbaILZ8msryHBFEAPK8DlgA/p13nX/Z9c8idyAt1EP+zm6UuUMqaHG+ApCMsBEulSMGt+anqTG6KI70EDYSiWhsMOu01S1ohuJIG7cAZBxvbIUm6gIQbycjx4daEzCphk3VZ9IEn9PFikyxsvI=,iv:gm6d6Vm5MtqJNvNgmgPoOWpIpzFbLFa68e4sopG689A=,tag:p6Gt/I+GXv0h0EhpUG/X7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
