apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strikers-data
  namespace: strikers
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
