# yamllint disable-file
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:9hNTwwGVy8uJweJ1Q/Hfodw=,iv:RE5VQP++BauS59R5hq8/iemMwPYIA9chiCVhqrVocg0=,tag:nWbHcKc8Sb2QcZ+iPaNB+Q==,type:str]
    client_secret: ENC[AES256_GCM,data:UhbLJt4KlNBaWGU74aB3Ge0Ug3pQpS/fUCamPkcWrHc869/jw4chQ8rbBYZqy4oFd4NQf8oqHL/F4INrY6m1lA==,iv:w/qTGJ3ab/6Rj6t9RrWdY0lmZRjIgxqPKGmuy2hgN+k=,tag:AtbDsaEExz5WGL1Z7eHy5A==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcFExT25UYlpRR0xUekFS
            aWdiQ2dvVWpVZlRDdXhZek5YZE8vcFRFb3pJCktsR2pocW8xTUhaanJrTDVIVy9m
            THYzcWpUcEIwdC9zQk90cmRHVld6eGsKLS0tIHBFU0hRZDhhTXNGR3NacFV0R3hL
            cjBmSTlwdmM0V1pZbGwxdkkyM3R2N1kKv1T+QL31SgH8vQJnHS4b16RU4umpwu/o
            TqnQxBaxDxNpA9hT8i/xdLEzXs6IyRmDJQWrJnufsl3bq5o2MngItg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T21:06:41Z"
    mac: ENC[AES256_GCM,data:sLNWk2v/XlpfZQ512g76qSxRj6bcGl8bo5/YW9uAddbMDVSv5dxsHK83FFvxhT4ZIRbkbMk3n33Fhw16KS1MpiFm/A94n4LBP37Q6WpfUJbS9k216HhqBSQhpO2/KAeqP1NSOCwgOxBVd29NNVvZb1jUqll2bZzPWJxcPBh18gU=,iv:PG4BAGJW5F3TAIQxZzwZ4MeQ6gMjRV1O3gmpkNaeQ9U=,tag:ATO8kc+02vfPxt6tkGQM4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
