---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # CNI
  - cilium/namespace.yaml
  - cilium/helmrelease.yaml
  # Load balancer
  - metallb/namespace.yaml
  - metallb/helmrelease.yaml
  # Ingress
  - traefik/namespace.yaml
  - traefik/helmrelease.yaml
  # Certificate management
  - cert-manager/namespace.yaml
  - cert-manager/helmrelease.yaml
  # Cloudflare Tunnel
  - cloudflared/namespace.yaml
  - cloudflared/deployment.yaml
  - cloudflared/configmap.yaml
  - cloudflared/secret.yaml
  # NAS storage
  - nas/namespace.yaml
  - nas/secret.yaml
  - nas/deployment.yaml
