# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:F2TLBlhpSS1Vhb71JMYwag1mdaogaTDk4IKudDskmOx88C+po9evgDUXTvLnKOfGj8mPSg==,iv:Q4Yhyb+SIKyEGkUAxg1MBjdVxRZN3YapSvII8dlmFR0=,tag:ovdzzRn+/lca9FXeRZKKmQ==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:EcSmMbuUTER8fytaWKTfHMRlI2SDAD/STTuYRNlEbRwPKynapde8khzYzNTrSzjsnqk1obAp5NHS8yN+EABOoQ==,iv:dOYgtS99LspCMSt5geTznoRT04IVfOpl0Zm2TCLHGpc=,tag:YmewtQS4j4WDp8zWDKB0DQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:NZj0Q4QMiwpKVmpeNrJWmWJ3ON0wL5Lu5tDM7iUTUzncm14UeZT6XpYY1OSs9ZTMC87vBiV30qB/pVJOrDaIItgWsOpRHkgZ,iv:BY7lp5JuJMN2BtygIwNiXuqyHO25aUNkCd9bwsHjbO4=,tag:RO+MIg8IFOVcyD3kLm2bcQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kQne9z1sNYSeO2yz6rgQ+ZBGQ2nRU1BgO0hFp7vYNQS6EQg=,iv:of6enFS21hiwHfUIJj3lV0CqSQTHRTz61CKoFKSdEbM=,tag:xr+bQBXAU33p06tGnelv6Q==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQmVsTkVXbzRxZmpNMnlp
            UjlHWGlVcUdDOHNHdXAwb0NzT1BFdUVZK1ZJCnBDaGdnSTlFQzQxS2N1N1BpbFZF
            QmRiRGlUL09HOWh2bll6cW53Z21Kc0EKLS0tIFpqNVJ3a2VuRk50WEVYdlVlbjBh
            Y09FaXNlSEtreFE2dVhCRGRZMkdGcDgKZCQajdFB7Ehs8knnrnza9RC3yppMze6o
            O/TlM9R1nia/2wrHTH7e0MjkGoRGdBCvgViSstcOQbB/rGRt9xJzyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T17:36:11Z"
    mac: ENC[AES256_GCM,data:id1j7B5MG85tbRe4XAnVZ7t4/+IX7PC1YExkFm2dxi20Hxb2bODUXYcpXRHFaC33HpXNR7mJXnLTeNrfcxsxJwYGWxXF0HI5TytkSA85GhHmUY9NE8XW7phEl/pIF8yt6rhxd+pCuBsWfhH+s26+7REgxjKmzBz4zIHvt3HZ97g=,iv:3qo26ttr3kHLeaSWbwS5cb7A4sPGK3doj2mSOqb55O8=,tag:MWpcOXBZ23f4Iw28itMqmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
