---
apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: openwebui
  annotations:
    tailscale.com/tailnet-fqdn: openwebui-hetzner.zebu-dorian.ts.net
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
