# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:bwfkTsAbxOxg5LrwQV1Row3F8kwfiYdiJSB+cph1V0O8ePAg67mqOEmMCSC2UgeU5D07DjJHrttKirp9WadtBvYllUhRnbLbMOTb+E9AqD3WEJuflb4iCgMI1ebVA72hBbf4JzET8nBGCaj+cyPRH/s7GdXTORmMKk/ywXe2AbG5MMPGka6u+hQOl4/zP6Surwht96b6q0zSaUzGCq7Fso4k0cUR/90M3M57p/crsPXVxLLEZ51VCQ==,iv:ocuKRIsSG37qCTnR9AiOlV/zA1Eq23hGtJAuRWQovJ4=,tag:96F6Wnl5/sspT75YeWux1A==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFam1GbVZUcXp1aWhUeitT
            alJ1Ly9EaU1lTnZ0Z0Q3Tk05cTZyV1hKRG1VCkdMS0xld2NVMEFuTC9tMCtuZXU2
            YlFDWkwyMXowOHJZc05raG9tenpnczAKLS0tIHhCbS9QMGMrR0hsQlFpYm1KUWVN
            UStwZ2NXa1hsNkxlcFBVS2loc2E5eXMK3mMR1dWlsqUesCwN4wGEyzqYzE0g/+zW
            RjCtcOTUvShmdRm4tdov1kdnrAONw0fKJy3C6zcurFNu/K9ZtZydMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-08T18:19:44Z"
    mac: ENC[AES256_GCM,data:6KAiQl0ACPY7sXW5l1o1wsS+7cPwlFHIabzQksWrqiFeIVlpNPvhiEuIBdnHrvgSyYa/mrWj8mNdvHPA0lt5YB8HaQTloCf3B68sESOs9iZhZY8gFRgmfHtbXj554y8mXh+DWk8kQRmmiWNl+Wv3KGXJZw3WFkqkHr4Xm++k38o=,iv:Qp8eHIFUNYCDpIWSMlXIa32tvHKWCjR2S4W/pdsdQOQ=,tag:7JpostRd3C70vkaCw+FU5Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
