---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve-website
  namespace: steve-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: steve-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: steve-website
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: steve-website
          image: ghcr.io/jvz-devx/steve-website:main@sha256:5a8143342a94e9c20939f17fadfa6cfa47bca858a119d983296451fb5e908dbb # {"$imagepolicy": "flux-system:steve-website"}
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: 0.0.0.0
            - name: NODE_ENV
              value: production
            - name: ORIGIN
              value: https://steve.jensvanzutphen.com
            - name: PORT
              value: "3000"
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
