# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: steve-website
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:9z84jZurFeT6Vup8UedTT6etFVa5rMxPYC4cKOCvk7TqxhoyKiAv/Fayr1R6OKXKhRzF3L/IrPS24akr8OgXhAHZ0dkap2JvitEGkW/o1F+mDvJx8lau8zO2tC6GyxwazS0j,iv:cbv6l7n3M2zqqTnGeGOuSb1y7Y5EhjmV5qT0JcnDZL8=,tag:iYqb45DKbqRDSTuZ4na1+A==,type:str]
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK2FPbHRMc3krMklkS2VR
            RlROYWJTSkc4L0pXTHZLM3A3dnBNRzYzUmhFCmRJRVYvU3BERkRIR1hxaWhQRTVw
            eFVrbTVZajRkZDNpM2lQaEZHUGtHNXMKLS0tIDRpcnNwZzcrZ3NpU21hWmN6MWtl
            VFlYaVNOSGpvZkJWTGh0UWM4b3FINkUKdnykKABfTAHzgWPZ6C8xCHVQIpg35f0D
            R0EVEWKNDk1hN3S594jrEySbR1NTauw+QnY5xGLmzKbmmkkU8lHa5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-02T17:53:01Z"
    mac: ENC[AES256_GCM,data:IR8Ns230K6PHxX/wsp0F6iVyAfwQCEDbopIQB/2L7EN5t/OF9CHbaXhzORDMjDvkkIZeEUX6Bq3ZIx+Od2vI4KsI9kdSb+t1ILQKmsaZMY4nQP9zNhxOD2bH+kKv3MyqWg09lX0leacQv1dcOOq5U0jozf20bsu778KeMHk8VUY=,iv:3k1POLcccLQUJr5Ef8P2D8E9BjmmIeQvDPIRJSx39SY=,tag:Wx/jh4B6f0qt7rPn3iIoVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
