# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: steve-website-secrets
    namespace: steve-website
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KqF7WJCp7i2+oIiox/BuBq3AifynZeHAsk2YHp3eDi43CIGudmiCCR/5jG/NMRu8,iv:zpOlUgnfidLYkrg9s29BwrMAy3nnOU5ydeIJvh+k5jA=,tag:wLeHZcZN33myo9dShUggiw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mG8dt1FZZ37CR2BGbPnYaK2t162n85pgtEENbp35dl27p1N/JLJoLDGsvvfoQ14XtC7EEB88WEBLSbYUqne6iY2pL5GnNw9asG+EMhM8J71szQZyKCVccoZHVYhcU2iUBp0mCokHDC1SeRUb3vpdGlEY7+J/,iv:29cgq3CpHpw8PoQtudoNtYvk/tWRkYADyKg89jfn4gE=,tag:gCtY8R1Y+2Vl12xVqZys/Q==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:YLwCOm3Ba85gQHMq2cx0OL7QobbmcGI/yujOcY0iuMHqq795yiV8wN/Fzln+TiyLQEgA7wpbq91qg7fXg6oUQw==,iv:41Q5Ufcm1f7nWwusor6mG66qea9ol/N2ZwkKXQICXz4=,tag:eHnyQHOavXL99udkaHxgSw==,type:str]
    CLOUDFLARE_PURGE_TOKEN: ENC[AES256_GCM,data:ccycjukO+gVb0SlNmGaF6DceoPzhnwA8lNIBJH+SR4vJli4ukYiKmI1vfWZ52N2Q+I0xXZA=,iv:SNnGcDfM9uenJqd+dACSRVk4zBDQLhqvBFgPVVe+bXA=,tag:ghS/JbVISUtaZXEFfs6E+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cVp1YWE4OXR4eWI3M0ZP
            WW0rSjVuMGx0aFF5MjNxVGJBVk14b01YbjFzClFJLzlJMU1Ic0JWeTZpWnNmSElZ
            RWJPSm5jdFoxcVlaNnZuZE5pT0FwNFEKLS0tIHYzSWpzNkZLSkNDc2NzMVhnY1o2
            cUFyWjV3WmJRUFkvazhaNmpLcjQyZFkK6vs1AM/cLMX0WQQCqJOZxczu65GQXUYw
            rZus2DVMQoGfvesr15Wi18W5eyDxHeyvSiUsQj/e6aa6pd1FQegP1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:47:27Z"
    mac: ENC[AES256_GCM,data:oSRqqn5SlsKgaKS8YJ3wWGzyL8RwO+c8pfcveUw6arUUeeqlGzy5/64mHL0oNkHmJF6AMHuHB4A/6yRyGCFvAl4IQoTYpnBd1/wYDL/hkCtViYTiyxsYqrU8CMxvz/w4O9/k7yCdvvFCLZuX/O07bwVey7c0c6pGoECtANUcnlI=,iv:w8RJK0vaA0ofc64X5JSONP3Xe7yofZ7wXSSEGZH6k1s=,tag:tyJvOnSw+Ovg9OdXOZH3BQ==,type:str]
    version: 3.13.3
