# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: steve-website-secrets
    namespace: steve-website
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:KqF7WJCp7i2+oIiox/BuBq3AifynZeHAsk2YHp3eDi43CIGudmiCCR/5jG/NMRu8,iv:zpOlUgnfidLYkrg9s29BwrMAy3nnOU5ydeIJvh+k5jA=,tag:wLeHZcZN33myo9dShUggiw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:mG8dt1FZZ37CR2BGbPnYaK2t162n85pgtEENbp35dl27p1N/JLJoLDGsvvfoQ14XtC7EEB88WEBLSbYUqne6iY2pL5GnNw9asG+EMhM8J71szQZyKCVccoZHVYhcU2iUBp0mCokHDC1SeRUb3vpdGlEY7+J/,iv:29cgq3CpHpw8PoQtudoNtYvk/tWRkYADyKg89jfn4gE=,tag:gCtY8R1Y+2Vl12xVqZys/Q==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:YLwCOm3Ba85gQHMq2cx0OL7QobbmcGI/yujOcY0iuMHqq795yiV8wN/Fzln+TiyLQEgA7wpbq91qg7fXg6oUQw==,iv:41Q5Ufcm1f7nWwusor6mG66qea9ol/N2ZwkKXQICXz4=,tag:eHnyQHOavXL99udkaHxgSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cVp1YWE4OXR4eWI3M0ZP
            WW0rSjVuMGx0aFF5MjNxVGJBVk14b01YbjFzClFJLzlJMU1Ic0JWeTZpWnNmSElZ
            RWJPSm5jdFoxcVlaNnZuZE5pT0FwNFEKLS0tIHYzSWpzNkZLSkNDc2NzMVhnY1o2
            cUFyWjV3WmJRUFkvazhaNmpLcjQyZFkK6vs1AM/cLMX0WQQCqJOZxczu65GQXUYw
            rZus2DVMQoGfvesr15Wi18W5eyDxHeyvSiUsQj/e6aa6pd1FQegP1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T11:22:15Z"
    mac: ENC[AES256_GCM,data:HiVW/hgF+I/08xPlvJfimfJyJDCLV9IKUhT2TdLPRyAwcH0cy6xDwd1dkcmNC/fxOYKuFXFB+xiRAVnQcD6zWyqwTK0JMB33mwwl1KJWfw3iQjnZLUa+H6qINH1U4rvYMdPL9dw4oOcV+8G/BvjN7ILLIldzdCfJ7ZDZzouR11g=,iv:xJIYykmCWs19ZAv3AY4lO4huK4Ihx5YT/B7jkFsUpSI=,tag:OfPbgkOC+sAVMJnXSDI+KQ==,type:str]
    version: 3.13.3
