---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - copyparty
  - cliproxyapi
  - cod-zombies-pap-checklist
  - hetzner-firewall-home-ip
  - liverpc-docs
  - openwebui
  - resonance
  - termix
