# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-auth
    namespace: klavier
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:neOU5roZk6RmL6+UhMWUa49FfzweqZdmwnI9XWeJIzkgI12ZnSlS0iLY7mh3Oj0xvAMw5It3a9UpWbkcQFsji/TfvZwWW3OdjZxMYVxLJkFdMhBlYQCj4XyoM2IEcwSaQlAV,iv:yHSMuuTWVirc6VC4o+/jBe3+SJosVceT1OMlg8gm0R4=,tag:LhyRQKVLqPxSyn9n61QbfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOCtFbFBGcDZUS2d1eHF2
            OUdHS3hFQytjMkMvSnRBd01yUXFCaWZHdGdBCks1US9qWTlGeTFPeTBKRkJmK0JP
            RmtvajFia3dNRDAxSXlQaTl3T3laMkUKLS0tIC9WbFlBdjNlOXJacE1Rcm82TFA3
            d21wZCtleklQaGFtM1diNXo1Nnk3ZFkKsU28M5zNgIPSaA+IbZqBvr1AK09YkcSg
            OJiCKicdfDGo7C3whBwDoNgB6G1XbqNkr70jLuxmfaFtKEHecmfNeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:54:42Z"
    mac: ENC[AES256_GCM,data:iucY4xJCEmphncDk2SWPPUb8YDPAal+aZ2PQ3ooCS9feVtTLF8EPSvtgbsPJqvwhxJ4Fqow00WMsuGtBlubrMPDZ9PX3ADfSQqPPTZfn2yTTIwQPW/5G4D8CNU74F3S9VNrAI9plLvv4Ohyb+h1w4oyPNxjxf4YjWt+BC/Wjlyc=,iv:p2kYGvggDx2vkDQHHqyFmBRK3f8zjmi/I4meOu7yVxU=,tag:g0n6hOgm+kONBXPAsB+YYw==,type:str]
    version: 3.13.3
