apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ghcr-auth-secret.yaml
  - secret.yaml
  - r2-secret.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - app.yaml
  - ws-server.yaml
  - ingress.yaml
