# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: klavier-r2
    namespace: klavier
type: Opaque
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:VHoR5CpSmijX6I+APS/mNeZTBs33L9tix8tbC7reoCQ=,iv:fTkBeLIBpZnD9rZUKOiECdiEMdE7cMp+D4NPz6UFk8Q=,tag:IuDn8TUccBkW3GB85onqJg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:k/oUVjsNAyPG3GNgKUjWSjpS5TEXFLIDscMaTm3ZEJmzQJ/a8jVd5xRox0YtuzaLbhUNZdbySTGhdhxd+aHPZQ==,iv:ATpNqZOYD/zRhbLcnf8oO9nS/JPyOoBxF9/hH2/ONEk=,tag:ChrbpdVJfL40zhWgOcvAdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVi8rYmRQREdSanNsclVm
            RkVOWjYvZzBydHA0aUN6SkhUSVhqSGJPY2hzCmUvb3c2MnllWGxsSXBhMDJ0M0p3
            L0hVZENBdEpnOENMRXhSdkZFRTVkeWsKLS0tIHZrcXBIc1F6UDNMa3NoVFgwNHRT
            d1pVZEE4NFVqSHBDVTRTQW1xRmtPa2cKaRDLF/7kvlHlLBr7AWqJ6SLV2JZqNajy
            BkRNxnbbSzguJNUET3oFD9rgVN1W9y6jj//nVnNzolK8wRyYJQGzgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T11:00:36Z"
    mac: ENC[AES256_GCM,data:zMX3GXcbv6mpbgJWiCyLMF2BesDdcuvMfFNOWYF/d2XjxEpXftwQKlEGBwYfOUnkXxHPNzbIdW/j07dGk//M1LxnRBaeMAbv0kiBrfY3WhdBcr8vUYKKnix5VZBuGy2zs/GQ5MCALaS7vq7Rs3VCoP6s9e4Vy7y05JdN6XWuSvY=,iv:6Vyycyn/CoMYgsPpRIChyZ/5CVlrOuJz6go/xfx0AE4=,tag:PfZHAA8r6HvhhCj8IYcY+Q==,type:str]
    version: 3.13.3
