# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: klavier-r2
    namespace: klavier
type: Opaque
stringData:
    R2_ACCESS_KEY_ID: ENC[AES256_GCM,data:m2Zh5HF+pk9evA==,iv:wRKEtRrcWFejoFWHCLGUqVLfU5I2ln6jOS5juc5yG0c=,tag:05penAdGv1JKBZy36ZgFeg==,type:str]
    R2_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:tMPJi4cD6RwKHg==,iv:s+hDpQNyl2TSc8wYz1SCPHKa52fQ4LgLUpibB4/z04Q=,tag:TOqn5IyhK+f0kjLT8TjvqA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVi8rYmRQREdSanNsclVm
            RkVOWjYvZzBydHA0aUN6SkhUSVhqSGJPY2hzCmUvb3c2MnllWGxsSXBhMDJ0M0p3
            L0hVZENBdEpnOENMRXhSdkZFRTVkeWsKLS0tIHZrcXBIc1F6UDNMa3NoVFgwNHRT
            d1pVZEE4NFVqSHBDVTRTQW1xRmtPa2cKaRDLF/7kvlHlLBr7AWqJ6SLV2JZqNajy
            BkRNxnbbSzguJNUET3oFD9rgVN1W9y6jj//nVnNzolK8wRyYJQGzgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:54:42Z"
    mac: ENC[AES256_GCM,data:brdseC5H44wOVOXYxqQJUXWiK19f81vHVqEmL1+jUDuyQkJ9KPLaAQMLMaeuju5FXsYg5flZrz3XFl6FdKrp5VK6Qemnz3p6QAsBfiqI+jVIuLMub4u78plZ8FMYJQlBzG8I/0Viuqwvje2qcy2N8QjCNvR5jgXfkgM56OTKAFc=,iv:gZTCv1if5CTZoIq1wLWVm4oFCD4doc96cUDuNGQ6SBg=,tag:5i9u5M9ILOkIhMt7NnJb3w==,type:str]
    version: 3.13.3
