# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: klavier-secrets
    namespace: klavier
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:s/26ro6fkuaN9gFLsaIv1R9j5XZV5kUQ6OxWFMQ2ZaPCIKS5Zpay7SVANvQ6AXu9Vh1y/n8I+1v6GbEJ96R9Gw==,iv:6GP9IDSees1YQBsM7HFASIUbCHj64bawV6c/l8NoKtY=,tag:wAALQKWh+TsTjqwNam0h2g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CMR+BjaBRzPZgNHgIQR0UM81Nqsw7YmQElk2RTDermz3IUPXIJoKvjITdkz3NonpBznc/YpnS5O22YsxcD56nh/ONh9TeCXuF8a0cM5G1rwI6trmcEK52Zre890wHO8WUhvhA0+pcSsv,iv:igT8Z9EMBn+zPMtyatDEWyEbCmQ+t7mvIq5qy2jw6lw=,tag:xEcWsLS8HW6Rk6P4+wrOMA==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:Qs9IBYcBXZ72GhqZlv13/xwFZusWvgL4wQEkmYc3FrCtgLyfhNLZ7v+d4UWIisR6u5JNP4U3JAovKLClQNKaQQ==,iv:Us71eAWhxesJ+O1KL4LEThk+rrCdTUf5H8GgrGAH2lU=,tag:Wv6YO+YVqpm6qGFXxe6KuQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:nWsLk1NeFGqOyq+ECHSEVaddm8/9DieZxOla4gHAW3mE65UJqOJsKjpUri18cUyaIz4EURHoyQO7P8gjImj1O/CCCCOQl+LZ7j8Hh22fsmLBAkI9,iv:aADJQUSPwkVrnSJjwD39sU44vYLthFw7Ky7TJZfn2KM=,tag:UyY0cSVAfC4YAFW69/aZMw==,type:str]
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:TPk2EQI6MeG6wcbtoUBcB/8fXF4D1Xd5/9SwsVCBD7pk+AmOpDNFFQxWdsAfv7gkxBzNKY6jgIhh5126w0ghkg==,iv:tRG5ER1Y+ggo8eW3OPRocrYzrVp7z83Fs4VwPb3iz3I=,tag:gQR6aIu+wam8mKVP7JDr9g==,type:str]
    JOB_SECRET: ENC[AES256_GCM,data:5z7msAmbplN+tA9XoJHSMhJT74En904JrtSK0drI8ckvDKyOeKEoJciXSdGn98MBxAEFldVmVXwFy2v5TPgdWA==,iv:r7QB584Mzpd/yGl64vNfuVWhzuy/eeDD5bxX0tsENpk=,tag:2bAXcR6DQ+hq7wK+QMCVAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR2lsUkh6anhGN1lhRVRZ
            OG1GZWN1NlBRSTNxRkNxTFJIMUxhb00zZ2hnCmhNL1N5MHVUTW9VV3NlZDg3SGhi
            REg0ejcxRCtYQ2FocE1uMlNPdTFmYkEKLS0tIG4rRVNrYldnUGx4TElDVkY1WnhL
            UVk3ZFkvb01VSDA4S3NjUDhpdDlNVmcKY7wPSIic2UdIxT24yY54LMgeLDpfB3Jw
            pKtDD6eESNFmU22eCEumd0NrKtZA1SITAfrHI5X0OSAGgjeT/i0ybQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T10:54:42Z"
    mac: ENC[AES256_GCM,data:2W2Fh8U9rSChieivg7QMnqbB7joYn1ivrQ1FuWynisiFu/FHGok9Ho2O8iA/m9KZq/cmzt+fSahP1HREzrtqNVTt9fJUDOzaKGwTFUt9Ur+TWUBP167ycy+Bru+ZDQzfyVgGirGmtndoMHpfPUfacPLcsojZgUp6x1Ky+7Lb4js=,iv:9klA+i7PVsD7QD0+DLO9+TL1622hIRMj/GfQTrLVspA=,tag:dGM8JqD1NauCpyIfCLKm/g==,type:str]
    version: 3.13.3
