---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustdesk-server
  namespace: rustdesk-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustdesk-server
  template:
    metadata:
      labels:
        app: rustdesk-server
    spec:
      containers:
        - name: rustdesk-server
          image: rustdesk/rustdesk-server-s6:1.1.15
          env:
            - name: RELAY
              value: "192.168.1.112:21117"
            - name: ENCRYPTED_ONLY
              value: "1"
          ports:
            - containerPort: 21115
              protocol: TCP
            - containerPort: 21116
              protocol: TCP
            - containerPort: 21116
              protocol: UDP
            - containerPort: 21117
              protocol: TCP
            - containerPort: 21118
              protocol: TCP
            - containerPort: 21119
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            allowPrivilegeEscalation: false
          readinessProbe:
            tcpSocket:
              port: 21116
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 21116
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rustdesk-server-data
