---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rustdesk-server-data
  namespace: rustdesk-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
