---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-web
  namespace: cv-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cv-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cv-web
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: cv-web
          image: ghcr.io/jvz-devx/coolify-cv-web@sha256:62d9688c2b471b931770e0f8ab6d7f8058e1589e6beace9405a3a6bda76310bb
          imagePullPolicy: IfNotPresent
          env:
            - name: HOST
              value: 0.0.0.0
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 512Mi
