---
apiVersion: v1
kind: Service
metadata:
  name: cv-web
  namespace: cv-web
spec:
  selector:
    app.kubernetes.io/name: cv-web
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
