---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # MetalLB CRD resources (requires MetalLB HelmRelease to be ready)
  - ../metallb/config.yaml
  # cert-manager ClusterIssuer (requires cert-manager HelmRelease to be ready)
  - ../cert-manager/clusterissuer.yaml
