# yamllint disable
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HCuLp8/jUR2u+S89hqO1O7B5NPVmQri9Og2eVcxFudqfjdPPdRLN4HyVggaJw7gRSBjXrgI4oi5ebzy1FGKfRwTWkdmjqyAAKPX2y7FqbNN0qovGddpXfuL0UJLrHkEHvi56TRjJZW4vrADa11Ln+YFYQunwF4uvJK4oGgt1KvpZG45Su1OPsL4iTCBD1lzVySMWIx6dQFWwOw41Bd738319I4COk7d5dk0vGnaDJTgHzsCABUn6U7BNrCs6AlfOSWGp2T3qyiOuHO3gYcNEB1nbZMu3tgHPyubBlNeFCqyb34ccoXfU0JrS/ko=,iv:c+n/bnLhIG76IvCCzQwqGd0jCDC8YRZFIGLXAzyseNk=,tag:XCVqIanOitk5SQCy92rcZQ==,type:str]
kind: Secret
metadata:
    name: ghcr-auth
    namespace: dartbingo
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13mpnc9r9ykh406nwqzgtqketnvkpnxj02sx3qv5pae4txzynvscsjpum3s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YnBvcXpxNjVXU1h5U1N2
            NmVQd3JkY29udDJpOGxNTzkwdk93bkR6UzBzCjE4Zis5MUFockdUbTdLR1hhcWs1
            NmUxZXp0QmxlZFN1R0Z4dUZ3UzFSRjQKLS0tIHJXSmkyejYzZG44bVovQ3ZEaEM2
            ejkvL1FPM0FOSXU1S2xHVnFzYkJYbGsKoqS9l0aQ3jImUJIkhxx0zedGGpCLtzCF
            XBQgwTdv+zULbBtJoLVv2ph1LguAFh1JYYw+M5lbA4i/veqetnNIcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T07:24:45Z"
    mac: ENC[AES256_GCM,data:qUxymlWE1A3G/7kPAvJxG8MymcYU4i2Yp3+V66VRU71ZhIgK6jeyW0U52r2YxsfexyCG8IxrDHCHChJus+BsEuS2EFUCZtlNfx15F5Z5xLSv2GALktn9hGa6Acd+ETIE7F0q9wbZObhYdM5M2KfI70IP0PyQL+e8JzJsF+w/Mlg=,iv:mcD60TfXJPzYeiIyGMM871IEq8nHfM19AsDYu38U67Y=,tag:NF92iyVPZUtTLoym+zyVNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
