---
apiVersion: v1
kind: Service
metadata:
  name: dartbingo
  namespace: dartbingo
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: dartbingo-hetzner
spec:
  selector:
    app.kubernetes.io/name: dartbingo
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
