---
# Public via Cloudflare Tunnel.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cod-zombies-pap-checklist
  namespace: cod-zombies-pap-checklist
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    external-dns.alpha.kubernetes.io/target: f4f59044-cc55-41f0-a76a-96fdfeb42dc9.cfargotunnel.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: pap.jensvanzutphen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cod-zombies-pap-checklist
                port:
                  number: 3000
  tls:
    - hosts:
        - pap.jensvanzutphen.com
      secretName: cod-zombies-pap-checklist-tls
