---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cod-zombies-pap-checklist
resources:
  - namespace.yaml
  - ghcr-auth-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
